//! people_parity.rs — GENERATED by tools/extract_people.mjs. Golden vectors from the
//! LIVE js people.js: identity/taste/birthday/line formulas must match bit-for-bit.

use wriftheart::people;

#[test]
fn identity_matches_js() {
    let golden: &[(u32, &str, &str, &str)] = &[ // seed, gender, name, title(blacksmith)
        (0, "M", "DUN", "DUN THE SMITH"),
        (1, "M", "DUN", "DUN THE SMITH"),
        (1337, "M", "EAMON", "EAMON THE SMITH"),
        (42, "M", "CASPER", "CASPER THE SMITH"),
        (90210, "F", "SAFFRON", "SAFFRON THE SMITH"),
        (3735928559, "M", "DUN", "DUN THE SMITH"),
        (2654435769, "M", "STELLAN", "STELLAN THE SMITH"),
        (123456789, "F", "TILLY", "TILLY THE SMITH"),
        (7, "M", "DUN", "DUN THE SMITH"),
        (4294967295, "M", "DREW", "DREW THE SMITH"),
    ];
    for (seed, gender, name, title) in golden {
        assert_eq!(people::gender_for(*seed), *gender, "seed={seed}");
        assert_eq!(people::name_for(*seed), *name, "seed={seed}");
        assert_eq!(people::title_for(*seed, "blacksmith"), *title, "seed={seed}");
    }
}

#[test]
fn tastes_and_birthdays_match_js() {
    let golden: &[(u32, &str, &str, i32, i32)] = &[ // seed, love, hate, season, day
        (0, "FISH", "CROP", 0, 1),
        (1, "FISH", "CROP", 0, 1),
        (1337, "MAP", "TRINKET", 2, 25),
        (42, "CROP", "FISH", 0, 22),
        (90210, "CROP", "FOOD", 0, 26),
        (3735928559, "FISH", "GEM", 2, 23),
        (2654435769, "FOOD", "GEM", 2, 1),
        (123456789, "MAP", "GEM", 1, 9),
        (7, "FISH", "CROP", 0, 4),
        (4294967295, "FISH", "CROP", 0, 9),
    ];
    for (seed, love, hate, season, day) in golden {
        let t = people::taste_for(*seed);
        assert_eq!(t.love, *love, "seed={seed}");
        assert_eq!(t.hate, *hate, "seed={seed}");
        let b = people::birthday_for(*seed);
        assert_eq!((b.season, b.day), (*season, *day), "seed={seed}");
    }
}

#[test]
fn lines_match_js() {
    let golden: &[(u32, i32, i64, &str)] = &[ // seed, pts, day, line
        (0, 0, 3, "WELCOME IN."),
        (0, 350, 5, "YOU LOOK WELL. THE ROAD SUITS YOU."),
        (0, 780, 11, "WHATEVER THE CASTLE TOOK FROM US, YOU GIVE SOME OF IT BACK."),
        (0, 1000, 28, "IF I WERE YOUNGER I WOULD BE OUT THERE WITH YOU."),
        (1, 0, 3, "WELCOME IN."),
        (1, 350, 5, "YOU LOOK WELL. THE ROAD SUITS YOU."),
        (1, 780, 11, "WHATEVER THE CASTLE TOOK FROM US, YOU GIVE SOME OF IT BACK."),
        (1, 1000, 28, "IF I WERE YOUNGER I WOULD BE OUT THERE WITH YOU."),
        (1337, 0, 3, "WELCOME IN."),
        (1337, 350, 5, "THE TOWN FEELS SAFER WITH YOU ABOUT."),
        (1337, 780, 11, "I KEEP A LITTLE COIN UNDER THE THIRD FLOORBOARD. NOW YOU KNOW."),
        (1337, 1000, 28, "I BURIED SOMETHING ONCE. NEVER FOUND IT AGAIN. KEEP A SHOVEL."),
        (42, 0, 3, "WELCOME IN."),
        (42, 350, 5, "YOU ALWAYS TURN UP ON THE FINE DAYS."),
        (42, 780, 11, "I KEEP A LITTLE COIN UNDER THE THIRD FLOORBOARD. NOW YOU KNOW."),
        (42, 1000, 28, "I BURIED SOMETHING ONCE. NEVER FOUND IT AGAIN. KEEP A SHOVEL."),
        (90210, 0, 3, "WELCOME IN."),
        (90210, 350, 5, "THE TOWN FEELS SAFER WITH YOU ABOUT."),
        (90210, 780, 11, "THE OLD FOLK SAY THE STONES SING IF YOU KNOW THE TUNE."),
        (90210, 1000, 28, "IF I VANISH ONE DAY, CHECK THE DEEP ROADS FIRST."),
        (3735928559, 0, 3, "WELCOME IN."),
        (3735928559, 350, 5, "HEARD YOU WERE BACK - GLAD OF IT."),
        (3735928559, 780, 11, "YOU COULD KNOCK AT MIDNIGHT AND I WOULD STILL POUR TEA."),
        (3735928559, 1000, 28, "THE OLD FOLK SAY THE STONES SING IF YOU KNOW THE TUNE."),
        (2654435769, 0, 3, "WELCOME IN."),
        (2654435769, 350, 5, "YOU ALWAYS TURN UP ON THE FINE DAYS."),
        (2654435769, 780, 11, "WHEN THE BELLS RING WRONG, STAY INDOORS. TRUST ME."),
        (2654435769, 1000, 28, "SOME NIGHTS I HEAR THE HEART BEATING UNDER EVERYTHING. DO YOU?"),
        (123456789, 0, 3, "WELCOME IN."),
        (123456789, 350, 5, "I KEPT AN EAR OUT FOR NEWS OF YOU."),
        (123456789, 780, 11, "IF I WERE YOUNGER I WOULD BE OUT THERE WITH YOU."),
        (123456789, 1000, 28, "I KEEP A LITTLE COIN UNDER THE THIRD FLOORBOARD. NOW YOU KNOW."),
        (7, 0, 3, "WELCOME IN."),
        (7, 350, 5, "MY DOOR IS ALWAYS OPEN TO YOU."),
        (7, 780, 11, "I ONLY TELL MY REAL FRIENDS THIS SORT OF THING."),
        (7, 1000, 28, "YOU ARE THE BEST THING TO HAPPEN TO THIS TOWN IN YEARS."),
        (4294967295, 0, 3, "WELCOME IN."),
        (4294967295, 350, 5, "I KEPT AN EAR OUT FOR NEWS OF YOU."),
        (4294967295, 780, 11, "I BURIED SOMETHING ONCE. NEVER FOUND IT AGAIN. KEEP A SHOVEL."),
        (4294967295, 1000, 28, "MY GRANDMOTHER SWORE THE RIFTS BREATHE IN WINTER."),
    ];
    for (seed, pts, day, line) in golden {
        assert_eq!(people::line_for(*seed, *pts, *day, "WELCOME IN."), *line, "seed={seed} pts={pts}");
    }
}
