//! stock_parity.rs — GENERATED by tools/extract_stock.mjs. Golden vectors from the
//! LIVE js shopStock: the fixed id selection (guaranteed + curated 4, procedural '~'
//! wares stripped) must match the js rng draw-for-draw, for every kind × seed.

#[test]
fn shop_stock_selection_matches_js() {
    let golden: &[(&str, u32, &[&str])] = &[
        ("general", 1337, &["herb", "meat", "bpcook", "bpfarmtable", "pocketwatch", "bombs", "tonic", "greaterpotion"]),
        ("general", 42, &["herb", "meat", "bpcook", "bpfarmtable", "greaterpotion", "tonic", "pocketwatch", "antidote"]),
        ("general", 90210, &["herb", "meat", "bpcook", "bpfarmtable", "satchel", "potion", "bombs", "pocketwatch"]),
        ("general", 7, &["herb", "meat", "bpcook", "bpfarmtable", "lantern", "tonic", "greaterpotion", "bombs"]),
        ("general", 3735928559, &["herb", "meat", "bpcook", "bpfarmtable", "tonic", "lantern", "chicken", "satchel"]),
        ("blacksmith", 1337, &["copper", "bpforge", "bpchainmail", "shield", "bpmace"]),
        ("blacksmith", 42, &["copper", "bpforge", "shield", "bpmace", "bpchainmail"]),
        ("blacksmith", 90210, &["copper", "bpforge", "bpchainmail", "shield", "bpmace"]),
        ("blacksmith", 7, &["copper", "bpforge", "shield", "bpchainmail", "bpmace"]),
        ("blacksmith", 3735928559, &["copper", "bpforge", "bpmace", "bpchainmail", "shield"]),
        ("armory", 1337, &["leather"]),
        ("armory", 42, &["leather"]),
        ("armory", 90210, &["leather"]),
        ("armory", 7, &["leather"]),
        ("armory", 3735928559, &["leather"]),
        ("magic", 1337, &["gem", "bpenchanter", "bpmanacrystal", "manaelixir", "wand", "manapotion"]),
        ("magic", 42, &["gem", "bpenchanter", "magerobe", "magehat", "frostrune", "stormrune"]),
        ("magic", 90210, &["gem", "bpenchanter", "arcanesigil", "firerune", "magehat", "magefocus"]),
        ("magic", 7, &["gem", "bpenchanter", "manaelixir", "arcanesigil", "bpmanacrystal", "firerune"]),
        ("magic", 3735928559, &["gem", "bpenchanter", "bpmanacrystal", "manaelixir", "manapotion", "elixir"]),
        ("alchemist", 1337, &["herb", "bpalchemy", "elixir", "potion", "manapotion", "bpmanaelixir"]),
        ("alchemist", 42, &["herb", "bpalchemy", "bpmanapotion", "greaterpotion", "elixir", "antidote"]),
        ("alchemist", 90210, &["herb", "bpalchemy", "tonic", "bpmanapotion", "manaelixir", "potion"]),
        ("alchemist", 7, &["herb", "bpalchemy", "bpmanaelixir", "bombs", "elixir", "greaterpotion"]),
        ("alchemist", 3735928559, &["herb", "bpalchemy", "bpelixir", "manapotion", "bombs", "antidote"]),
        ("jeweler", 1337, &["gem", "copper", "bpjeweler", "vampirefang", "bpluckamulet", "bubblering", "regenring"]),
        ("jeweler", 42, &["gem", "copper", "bpjeweler", "greedcharm", "swiftcharm", "ironheart", "vigorpendant"]),
        ("jeweler", 90210, &["gem", "copper", "bpjeweler", "compass", "ironheart", "phoenixfeather", "luckamulet"]),
        ("jeweler", 7, &["gem", "copper", "bpjeweler", "critring", "regenring", "bubblering", "vampirefang"]),
        ("jeweler", 3735928559, &["gem", "copper", "bpjeweler", "ironheart", "bpluckamulet", "swiftcharm", "powerring"]),
        ("fletcher", 1337, &["leather", "bpfletcher", "arrow", "bpgrapple", "bpspringboots", "boomerang", "bow"]),
        ("fletcher", 42, &["leather", "bpfletcher", "arrow", "springboots", "bow", "bpgrapple", "boomerang"]),
        ("fletcher", 90210, &["leather", "bpfletcher", "arrow", "bpgrapple", "boomerang", "bow", "bpspringboots"]),
        ("fletcher", 7, &["leather", "bpfletcher", "arrow", "bow", "bpspringboots", "springboots", "bpgrapple"]),
        ("fletcher", 3735928559, &["leather", "bpfletcher", "arrow", "springboots", "bpgrapple", "bpspringboots", "boomerang"]),
        ("trader", 1337, &["satchel", "lantern", "satchel2", "arrow"]),
        ("trader", 42, &["shovel", "pocketwatch", "satchel", "potion"]),
        ("trader", 90210, &["tonic", "shovel", "lodestone", "lantern"]),
        ("trader", 7, &["arrow", "bombs", "satchel", "pocketwatch"]),
        ("trader", 3735928559, &["treasuremap", "satchel2", "bombs", "potion"]),
        ("farm", 1337, &["bpfarmtable", "bpwell", "hoe", "wateringcan", "milkpail", "chicken", "carrotseed", "wheatseed", "pepperseed"]),
        ("farm", 42, &["bpfarmtable", "bpwell", "hoe", "wateringcan", "milkpail", "carrotseed", "potatoseed", "tomatoseed", "pepperseed"]),
        ("farm", 90210, &["bpfarmtable", "bpwell", "hoe", "wateringcan", "milkpail", "wheatseed", "pumpkinseed", "turnipseed", "cranberryseed"]),
        ("farm", 7, &["bpfarmtable", "bpwell", "hoe", "wateringcan", "milkpail", "cow", "wheatseed", "potatoseed", "tomatoseed"]),
        ("farm", 3735928559, &["bpfarmtable", "bpwell", "hoe", "wateringcan", "milkpail", "chicken", "wheatseed", "tomatoseed", "cow"]),
        ("produce", 1337, &["herb", "egg", "pumpkinseed", "wheat", "turnip", "tomato"]),
        ("produce", 42, &["herb", "egg", "pumpkin", "potato", "carrotseed", "carrot"]),
        ("produce", 90210, &["herb", "egg", "turnipseed", "cranberry", "wheat", "carrotseed"]),
        ("produce", 7, &["herb", "egg", "pepper", "tomatoseed", "potato", "turnipseed"]),
        ("produce", 3735928559, &["herb", "egg", "wheat", "carrotseed", "tomato", "pepper"]),
    ];
    for (kind, seed, want) in golden {
        let got = wriftheart::stock::shop_stock_ids(kind, *seed);
        assert_eq!(&got, want, "kind={kind} seed={seed}");
    }
}
