//! logo.rs — the WRIFTHEART word-art wordmark (art/logo_pixel.png).
//! GENERATED — edit the png and regenerate with tools/logoconv, not by hand.

pub const LOGO_PAL: &[(char, u32)] = &[
    ('a', 0xfcfc84),
    ('b', 0xfcc42c),
    ('c', 0x442404),
    ('d', 0xfcf46c),
    ('e', 0xfce454),
    ('f', 0x5c3404),
    ('g', 0x744404),
    ('h', 0x84540c),
    ('i', 0x0c0404),
    ('j', 0xe49c14),
    ('k', 0xc47404),
    ('l', 0xfcd43c),
    ('m', 0x644c2c),
    ('n', 0x7c643c),
    ('o', 0xecdcac),
    ('p', 0xdcc494),
    ('q', 0xfcfcec),
    ('r', 0xfcf4d4),
    ('s', 0x8c7444),
    ('t', 0xfcecbc),
    ('u', 0x9c3c9c),
    ('v', 0xf4b41c),
    ('w', 0xd48404),
    ('x', 0x9c3c94),
];

pub const LOGO: &[&str] = &[
    ".............................................................................................ab.........................................................................................................",
    "............................................................................................cdef........................................................................................................",
    "...........................................................................................fgdeff.......................................................................................................",
    "...........................................................................................haddefc......................................................................................................",
    "..........................................................................................ccccccccc.....................................................................................................",
    "..........................................................................................cccccccci.....................................................................................................",
    "..........................................................................................iccijkci......................................................................................................",
    "...........................................................................................ihilii.......................................................................................................",
    "...........................................................................................iiccii.......................................................................................................",
    "...........................................................................................iiicii.......................................................................................................",
    "...........................................................................................iiccci.......................................................................................................",
    "............................................................................................ccmci.......................................................................................................",
    "...........................................................................................icnmci.......................................................................................................",
    "op.........................................................................................iiicci.......................................................................................................",
    ".imqqqqqqqqqqqqqqqqqqqqqqqqqii.............................................................iimmci.......................................................................................................",
    "..iimmrrrrrrrrrqrqqqrrrmmmiii..............................................................iiciii.......................................................................................................",
    "...iimmpppppppppppppmmmmiii................................................................iiimci.......................................................................................................",
    "....iimmpppppppppppmmmmii..............qqqqrrrr............................................iirqdi.......................................................................................................",
    ".....immmoppppopppmmmii............mqqrrrrrrrmcp..........................................irqrrspp......................................................................................................",
    "......inmooppooopqnnmi.............icrrpoppommii..............................t...........inrqrrii...........q..........................................................................................",
    ".......immpppppotmnni...............icrpooonmi................................rrr........rrrriitprr........qrri.........................................................................................",
    ".......inmpppppponni.......q.........iqoootnii...............................ipqrrqqrrrqrrtriuuiosrrrrqrqqqrrmi.........................................................................................",
    "........innppppponni.......qs.........qooosci................................ipqrqqrrrrrrrrruuuirtrrrrrrrrrrrmi...........rti...........................................................................",
    "........innoppppossi......iqsi.......iqooosci.................................ipssssppsssmriiuuirsnsssssssspmni....qqtrtttbii...........................................................................",
    ".........inopppoossi......irqs........rtttsi..................................ipsppppsssssnoiiiitcmsssjsjjspni...irtatttjjffi....................................................a.....................h",
    ".........inropooossi......irqsi.......rttrsi..................................ipsccccccccssriccicfssicicccccni....iffvvvvbfi....................................................ivta................eari",
    ".........innoooooqsi......itrsi......crttrsi...................................ipfiiiiiiiissriiocniiiiiiiiccii.....fhvbbvff....................................................evkttaaaatllljljaaaddati.",
    ".........isnooooonsi......qttssi.....irttrsiqrqqrrrrrrrrp.....rqqqqqqq.........inii.....iimsqsrcmmi..irtatebaas....ihtbblfg....................................................iwkrtdeaaaaaaadedaddkwfi.",
    "..........inooooorsi.....prttrsi.....prttsiimroooottotttrn...qqrqrrqqciqrqqqqqqqqiqqrrc..imssppfmii..iftleaaaii.....kallbfh................ld..................................ikkadeelbvvjjwwwwwwkwcc..",
    "..........inoooootsi.....irttrsi.....irttsiiimoooommmrotrqm..imqoottmimqqrrrrrrrrrrrrmi..inssppfmci..iffeelefi......jkelefi.cgddaaaaaaataaari....dqrrrrrqi.....jraaaaaaaaaaae..ihjdeeeelbvjjjjjjjjwwci..",
    "..........inoooooosi.....ittttqsi....irttsi..mrootniimnttrci..isrtomiiiimrtrtrrrrrttrmi..isoppommci...igdlllgi......kaelefi.iffavdaaaaajvvlfi....iiabbbbfg.....igebalbbwjjjaaa.ikeccccccfjjfffcfffcci...",
    "..........isnooooosi.....irtttrsi....irttsi..iqttrm..inrttqi...srttri..isrtttrmmfqrtrmi..isroocmmfi...ihheetgi......haelafi..ighllbljlllllff......ifllllff......ihleeecfibbbvviiecfiiiiiwvjjiiiiiific...",
    "...........sstooootsi....qrrtrrsi....irttsi..iqttrn...irttrni..irttmi...irtttmiimmfmrii..isrttmmnmi...ihheeefi......whelbfi...khellffffffehi......iheeeeef.......hkdeeciiiglbbaiccii..iicvvjc....iii....",
    "...........isrooooosi...irtttttssi...irttsi..irttrn...irttrni..srttmi...isrttmiiiiicrii..issttqnnmi...ihheeegi......gkellfi...ikeeffiiiiicvi......ihdedeef.......gtdeef...gllblfii.....ffbvvci...iii....",
    "...........isoooooosi...crtttttrsi...qtttsi..isttrmi..irrtrmi..srttmi...isrtrmi....icii..isqrtqsnmi...ihheeefi......htellfi...ckeedfi..iiiii......kheedeefi......fheeef...cglllgi......fvlbvfi....i.....",
    "...........isnooooosi...irtttttrsi...qttrsi..irttrn...irttrmi..srttmi...isrtrmi.....ii...ipprrnssmi...ihkeedgi......vjellfi...ckeeefi.....ii......hqedtdefi......hkeeef...ihellgi......iglbbfi..........",
    "............snooooori...qttqttttssi..qttsss..isttrmi..qrttmmi..srttmi...iqrrrmi......i...ipprrsssmi...ihkeedgi......vjellgi...ikeeefi......i.....ihelfgdedg......gwelef...hwelefi......ggbbbfi..........",
    "............inoooooos..crttsrtttrsi.irttni...sttttm...rttrmii..prttni...iqrtrmi..........ipqrrsssmi...ihaeedaartrrrttellbgf...ikeeefi....w.......ihllfhaedgi.....gkellf...irllefi......ggellfi..........",
    "............inopoooosi.crotsrttttsi.crttsi...irooomi.rttrfci...srtori..sirtttqqqsqq......itprrsssmi...qddeedddddddddeeeedah...ikeeefi..atfi......hrleihadefi.....ikelef...irbeffi......ghlbbfi..........",
    "............innooooori.itonsstootrsicrttni...roootqrrtttccii...srtosm.sqrttttttrttri.....ioprrsssmiideadelleddaaaadadellldci..tellledeeleff.....ihblcikheeaf.....ikelefk..rbblfi.......gglbbfi..........",
    ".............inoooootiiqttsssrooorsiirttni..inttttttttrmmii....qtoopc.imfrtottttotqi.....ipsrrssimihggggdbblfffffffffebblffi.ceallleeeellfi.....ihblciihelegi....ckbblfiwqbbbffi.......ffdvbfi..........",
    ".............inooooooiirtrsinroootsiitttni...irtttrtoorni......nrooqi.iimmtttccffpfi.....issrrssimiiiiigdlblgiiiiiiiiabvbff..icfbbefgffclfc.....hrllfiihellfi....cebblblbbblfgi........gfbvvfi..........",
    ".............inoooooositorsiimtooorsqtotni...istotmntttqi......srtori..inrtotciimmfi.....issrrssimi...ifdbbbgiiiiiiiihbvbff...ihbbefiiiffdi...jrtteatathdleegi..igelbbbbbblfiii........fgjvvfi..........",
    ".............inooppptqroossiimrtoorsqootni...istooniqttrsi.....srtomi....stormi.icmi.....iosrtssimi...igebvlgi......hhvvvfi...igvvefiiiifai..ifadeeddeeelllldi...igevbfcbvbfii.........fevjjfi..........",
    "..............inoopoortoosciinmoooorrootni...iqtotnimrtrsi.....irtori....stooci..ic......issrtssimi...igdvvlfi......havvvfi...ihvvdfi...iii...icaelffecelbbbci...ihvvbcfvvvdg..........fejjwfi..........",
    "..............isopoootooosci.imtooottoonnn...istooniimttrp.....sroomi....srorci...i......ipsrtssini...ihjvvlfi......hevvjfi...ijjjefi....ii...iclbffiiiffbvvcc...ihvjvfifvvjgi.........fdjwwfi..........",
    "..............isroroooppssci.imrooooooonii...jstooniintorsi....sropni....sooofi..........iisrtqscmi...ihgbjlfi......hevjbfi...ihjjefi.........ifbbfiiiiifevjdf...ihjjefifbvjdf.........fdjwwfi..........",
    "..............isroooooppscci..imoooooooni....istooniinrttri....iropni....soprci..........iisrtqscmi...ihejjefi......gdvjjff...ikjjefi.......i.glvvfi...ifejjdfi..ihjjefigljjdfi........ffjwwci..........",
    "...............iroopppppsci...imoooooponi....intorni.imrorni...sroori....sooofi..........iisrtnspmi...iggvjefi......kdjjlfg...igjjlfi.....jti.iajjfi...ifejjjfi..ikjwbfiiljjjgi........fejwwci..........",
    "...............inopppppnsci...immopopppni....intopni.isqotqi...srppoi...isoppmi..........iisrtsscmi...igljjefi......kevjlfg...iijjlfi...jdaciiiajvfi...igljjjdf..ihjjlfiifljjjg........glwwwfi..........",
    "...............inopppppncci....imopppppni....snoposi..inootqi.isoppnn...srpppfi..........issrtnsimi...ifajjjfi......chjjjfg...iejjvllddedekciigjjlfi....iljjwwf..ihjjlfi.fljjwhi.......ggwwwci..........",
    "...............inopppppsci.....imopppppsi....sppppsi..inqppriiistoppni..ippppmi..........iisrtssimi...iijjjjfi......idjjwff..iijjjjvjvjjjjwcicwjjlf.....ggjjwwff.idjjjfi.ifjwwdf.......fewwwci..........",
    "................nqppppncci......mqppppqsi....rpppprii..inrppqii..tptri.iqppoorc.....iiiiiiisrtqscmiiiiiidlvveai.....idjwwefiiiebbevbelejbjkiilbbvlci...icjjjjjlcirblbvji..ffwwwdc......fewwwci..........",
    "................inppppmcci......impppprqsi..qqmmmmffii.iimpptri......iiifcfcccci..iiivjehiinronsciiiiekhhfcccfii....gdwwwlfiiiicccccccccccciicccffchi..vk..............ei.ifwwwwf......gdkkkci..........",
    "................inppppnci.......imrpppprnc..cciiiiiiii..iifopotiiiiiiiiiiiiiiiiiiiijllllllbfromniielllelvwiiiiii...ijawwkweiiiiiiiiiiiiiiiiiiiiiiiii......................ifcwwwec....igbwkwci..........",
    ".................npppncci........impppprpriiiiii.........iiccpopriiicccciiiiiiiiiwjleiiiifeeeommldeiifiiikkiiiic...ivkkkjjvjiiiiiiiiiiiiiiiiiii............................icwwwwd....cewkkkci..........",
    ".................nmppnci.........imppppppptqi.............iiicccaatiiiiiiiiiiiiiwkliiiimcccijrneviicciiiiikhiiiic.iivvbccciiiiiiiiiiiiiiiiiiiiiii.............iiii.........iccwkkef..iejwkkkci..........",
    ".................imppnci.........iipppppffcii...edkvaweedeliiiiiccccccciiiiiiiiijleiiirrmcccilcaixxxcciiiiihkiiic.ieiccciiiiiiiiiieededjvtiiiiiiiiiiiiiiiiiiiiiiiiii........ickwkkec.icccjwwei..........",
    ".................inppcci.........itppccfiii.illljiiiiiiiiieeeiiiiiiiiiiiieiiiiiikeiiccrrrmxxmhlxxuuxucciiiikhiiiiiiiiiiiiiiiiiieedebibvvigkwjediiiiiiaieiiiiiiquxiiii........ickkkkei.iicccjvc..........",
    ".................inrnci..........iocciii...ibiiiii...iiiiiiiiedbiiiiiiiiliiiiiikheiiccxrxxxxxxiuuiuuuuciiiidhiiiiiiiiiiiiiiilldiiiiiiiiiiiiiiiiwiiiiiiiiiiiiiixmxxiiii.......icckkkbii..iicccei.........",
    "..................snnci.........isccii...iiii...........iiiiiiieleliiiiihiiiiiikhiiiccmxxuxuuuuppippuuciiiilhiiiiiiiiiiiiiddiiiiiiiiiiiiiiiiiiiiiiiiiiiiiquuiiiccxxiiii.......icckkklei...iiici.........",
    "..................ismci..........ii.....idi............iiiiiiiiiiillbiiifiiiiiiheiicccmxxuuuupqqpiqqpccciiiehhiiiiiiiiiewliiiiiiiiciiiiiiiiicc..iiiiuiiiiuuuxm.iii.............icckkkkli.....ii.........",
    "..................ifmi..iiim...........iii.............iciiiiiiiiiifildiiiiiiiicjiicccxxuuuurrqiuiuuxcccciibhhiiiiiiiielieddiiiiiiiiiiiiiicccc...iimxxiiiuxuux..................iickkhkbi...............",
    "...................ii...hi.i..........iii..........iiiiieiiiiiiiiiiiiikddiiiiiiifiicmcxuuupprqqmxicummmcciiehiiiiiiijeiiiiiiiiiiiiidiiiiiiiii.....iuxuxiiiixmmi..................iicckkklbi.............",
    "...................i....i.............ii..........mxxxiiiiiiiiuuuciiiiidkbbiiiiifeiiiccxxuuqqqqxmccccxxmiiiegiiiiiiviiiiiciiiqxxiiiiiii...........iixxxx...iiii....................iicccgflelielii......",
    "........................ii...........ii..........iiiqpuiipuiipumxiiiiiiiiibviiiicdiiiiccmxuuuuccccccimiiiiefgiiiideiiiiiicccmxxxmi...ii...........iiimxx............................iiiifchffjkii.......",
    "........................ie..........ii..........iicixxxiixuxiiiiiiiiiiiiiiivviiiigdiicccmqpqcccccccmiiiiiiefiiiiajiiiiiiiiiccixmci....ii...........iiccx...............................iiiiiii..........",
    ".........................iii......iii..........iiccmxmiimuxxi..iiiiiiiiiiiiiiviiifaiiiccicqqqqqxcxiciiiiidffiiibbiiiixqxxxmi..........ii.............iii................................................",
    "..........................iiiaasdii............ccccmii.imiuii...iiiiiiiiiiiiiijjiicaiiiiiiuppcicciiiiiiiiafiibbliiiiiiuuuxuxi.........ii................................................................",
    ".............................iii.......................ixii.......iiiixuuuiiiiilbiiaiiiicpxuuqiiiiiiiiiiaciiibdiiiiiiiixxxmcx.........i.................................................................",
    "........................................................i...........imuxxxiiiiiiijiidiiiicciippuuiiiiiiacfivbiiiliuuii.iiiiii...........................................................................",
    "....................................................................cicxxi.....iiiviidiiiicccciuuxuiiiiacijjiiiiiixuxc..................................................................................",
    "....................................................................iiii.........iidigaiiiicciuxuxxciaaciijiii...iixmmi.................................................................................",
    "...................................................................................iiiieiiicccummmmiaaiiidii.......iiii.................................................................................",
    "....................................................................................iiiidiiiccccccitiiiiii..............................................................................................",
    ".....................................................................................iiiiiiiiiacciaiiiiii...............................................................................................",
    "......................................................................................iiiiiaieeiiiiiiiii................................................................................................",
    ".......................................................................................i..iicethciiiie..................................................................................................",
    "........................................................................................i...dddwiii.i...................................................................................................",
    "...........................................................................................ideeeli......................................................................................................",
    "...........................................................................................iiwecci......................................................................................................",
    "............................................................................................cssci.......................................................................................................",
    ".............................................................................................fcc........................................................................................................",
    ".............................................................................................nsi........................................................................................................",
    "..............................................................................................i.........................................................................................................",
];
