//! capital.rs — THE CASTLE TOWN v3: a 5x5 walled capital with a TRUE CENTRE
//! (Baz: "5 wide... a middle room without splitting"). The ROYAL WAY runs the
//! centre column from the S gate to the castle mouth; the CROSS WAY runs the
//! centre row gate to gate; they meet at the GRAND PLAZA. Castle keep dead-
//! centre north with curtain wings; twin pond parks, parterres, market pair,
//! commons, a residential district, orchards, and the cathedral quarter.
//! Every tile authored + protected; dressing is authored props only.

use super::generate::RoomMap;
use std::collections::{HashMap, HashSet};
use std::sync::{OnceLock, RwLock};

#[rustfmt::skip]
static TEMPLATES: [[&str; 13]; 25] = [
    [ // room (0,0)
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
        "WW.kkkkkkkkkkkkk...",
        "WW.kpppppppppppk...",
        "WW.kp~~~~~~~~~pkkkk",
        "WW.kp~~~~~~~~~ppppp",
        "WW.kp~~~~~~~~~ppppp",
        "WW.kp~~~~~~~~~pkkkk",
        "WW.kp~~~~~~~~~pk...",
        "WW.kp~~~~~~~~~pk...",
        "WW.kp~~~~~~~~~pk...",
        "WW.kpppppppppppk...",
        "WW.kkkkkpppkkkkk...",
    ],
    [ // room (1,0)
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
        "ppppppppppppppppppp",
        "ppppppppppppppppppp",
        "...................",
        "...................",
        "...................",
        "...................",
        "...................",
        "...................",
    ],
    [ // room (2,0)
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWkpppkWWWWWWW",
        "WWWWWWWkpppkWWWWWWW",
        "WWWWWWWkpppkWWWWWWW",
        "pppppppk___kppppppp",
        "pppppppk___kppppppp",
        "pppppppk___kppppppp",
        "pppppppk___kppppppp",
        "pppppppk___kppppppp",
    ],
    [ // room (3,0)
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
        "ppppppppppppppppppp",
        "ppppppppppppppppppp",
        "...................",
        "...................",
        "...................",
        "...................",
        "...................",
        "...................",
    ],
    [ // room (4,0)
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
        "...kkkkkkkkkkkkk.WW",
        "...kpppppppppppk.WW",
        "kkkkp~~~~~~~~~pk.WW",
        "ppppp~~~~~~~~~pk.WW",
        "ppppp~~~~~~~~~pk.WW",
        "kkkkp~~~~~~~~~pk.WW",
        "...kp~~~~~~~~~pk.WW",
        "...kp~~~~~~~~~pk.WW",
        "...kp~~~~~~~~~pk.WW",
        "...kpppppppppppk.WW",
        "...kkkkkpppkkkkk.WW",
    ],
    [ // room (0,1)
        "WW.....kpppk.......",
        "WWhhhhhkpppkhhhhh..",
        "WWh...hkpppkh...h..",
        "WWhhhhhkpppkhhhhh..",
        "WWkkkkkkpppkkkkkk..",
        "WWpppppkpppkppppp..",
        "WWkkkkkkpppkkkkkk..",
        "WWhhhhhkpppkhhhhh..",
        "WWh...hkpppkh...h..",
        "WWhhhhhkpppkhhhhh..",
        "WW.....kpppk.......",
        "WW.................",
        "WW.................",
    ],
    [ // room (1,1)
        "...................",
        "...................",
        "....kkkkkkkkkkk....",
        "....kpppppppppk....",
        "....kpppppppppkkkkk",
        "....kpppppppppppppp",
        "....kpppppppppppppp",
        "....kpppppppppkkkkk",
        "....kpppppppppk....",
        "....kkkkkpkkkkk....",
        "........kpk........",
        "........kpk........",
        "........kpk........",
    ],
    [ // room (2,1)
        ".......k___k.......",
        ".......k___k.......",
        ".......k___k.......",
        ".......k___k.......",
        "kkkkkkkk___kkkkkkkk",
        "ppppppp_____ppppppp",
        "ppppppp_____ppppppp",
        "kkkkkkkk___kkkkkkkk",
        ".......k___k.......",
        ".......k___k.......",
        ".......k___k.......",
        ".......k___k.......",
        ".......k___k.......",
    ],
    [ // room (3,1)
        "...................",
        "...................",
        "....kkkkkkkkkkk....",
        "....kpppppppppk....",
        "kkkkkpppppppppk....",
        "ppppppppppppppk....",
        "ppppppppppppppk....",
        "kkkkkpppppppppk....",
        "....kpppppppppk....",
        "....kkkkkpkkkkk....",
        "........kpk........",
        "........kpk........",
        "........kpk........",
    ],
    [ // room (4,1)
        ".......kpppk.....WW",
        "..hhhhhkpppkhhhhhWW",
        "..h...hkpppkh...hWW",
        "..hhhhhkpppkhhhhhWW",
        "..kkkkkkpppkkkkkkWW",
        "..pppppkpppkpppppWW",
        "..kkkkkkpppkkkkkkWW",
        "..hhhhhkpppkhhhhhWW",
        "..h...hkpppkh...hWW",
        "..hhhhhkpppkhhhhhWW",
        ".......kpppk.....WW",
        ".................WW",
        ".................WW",
    ],
    [ // room (0,2)
        "WW.................",
        "WW.................",
        "WW.................",
        "WW.................",
        "WW.................",
        "kkkkkkkkkkkkkkkkkkk",
        "___________________",
        "___________________",
        "kkkkkkkkkkkkkkkkkkk",
        "WW.................",
        "WW.................",
        "WW.................",
        "WW.................",
    ],
    [ // room (1,2)
        "..kkkkkk___kkkkkk..",
        "..k_____________k..",
        "..k_____________k..",
        "..k_____________k..",
        "..k_____________k..",
        "kkk_____________kkk",
        "___________________",
        "___________________",
        "kkk_____________kkk",
        "..k_____________k..",
        "..k_____________k..",
        "..k_____________k..",
        "..kkkkkkkkkkkkkkk..",
    ],
    [ // room (2,2)
        ".......k___k.......",
        ".......k___k.......",
        "...kkkkk___kkkkk...",
        "...k___________k...",
        "...k___________k...",
        "kkkk____ppp____kkkk",
        "________ppp________",
        "________ppp________",
        "kkkk___________kkkk",
        "...k___________k...",
        "...kkkkk___kkkkk...",
        ".......k___k.......",
        ".......k___k.......",
    ],
    [ // room (3,2)
        "..kkkkkk___kkkkkk..",
        "..k_____________k..",
        "..k_____________k..",
        "..k_____________k..",
        "..k_____________k..",
        "kkk_____________kkk",
        "___________________",
        "___________________",
        "kkk_____________kkk",
        "..k_____________k..",
        "..k_____________k..",
        "..k_____________k..",
        "..kkkkkkkkkkkkkkk..",
    ],
    [ // room (4,2)
        ".................WW",
        ".................WW",
        ".................WW",
        ".................WW",
        ".................WW",
        "kkkkkkkkkkkkkkkkkkk",
        "___________________",
        "___________________",
        "kkkkkkkkkkkkkkkkkkk",
        ".................WW",
        ".................WW",
        ".................WW",
        ".................WW",
    ],
    [ // room (0,3)
        "WW.................",
        "WW.................",
        "WW...kkkkkkkkkk....",
        "WW...kppppppppk....",
        "WW...kppppppppk....",
        "WW...kppppppppkkkkk",
        "WW...kppppppppppppp",
        "WW...kppppppppppppp",
        "WW...kppppppppkkkkk",
        "WW...kkkkkkkkkk....",
        "WW.................",
        "WW.................",
        "WW.................",
    ],
    [ // room (1,3)
        "...................",
        "...................",
        "...................",
        "...................",
        "...................",
        "kkkkkkkkkkkkkkkkkkk",
        "ppppppppppppppppppp",
        "ppppppppppppppppppp",
        "kkkkkkkkkpkkkkkkkkk",
        "........kpk........",
        "........kpk........",
        "........kpk........",
        "........kpk........",
    ],
    [ // room (2,3)
        ".......k___k.......",
        ".......k___k.......",
        ".......k___k.......",
        ".......k___k.......",
        ".......k___k.......",
        "kkkkkkkk___kkkkkkkk",
        "___________________",
        "___________________",
        "kkkkkkkk___kkkkkkkk",
        ".......k___k.......",
        ".......k___k.......",
        ".......k___k.......",
        ".......k___k.......",
    ],
    [ // room (3,3)
        "...................",
        "...................",
        "...................",
        "...................",
        "...................",
        "kkkkkkkkkkkkkkkkkkk",
        "ppppppppppppppppppp",
        "ppppppppppppppppppp",
        "kkkkkkkkkkkkkkkkppk",
        "...............kppk",
        "...............kppk",
        "...............kppk",
        "...............kppk",
    ],
    [ // room (4,3)
        ".................WW",
        ".................WW",
        "....kkkkkkkkkk...WW",
        "....kppppppppk...WW",
        "....kppppppppk...WW",
        "kkkkkppppppppk...WW",
        "pppppppppppppk...WW",
        "pppppppppppppk...WW",
        "kkkkkppppppppk...WW",
        "....kkkkkkkkkk...WW",
        ".................WW",
        ".................WW",
        ".................WW",
    ],
    [ // room (0,4)
        "WW.................",
        "WW.................",
        "WW.......=.........",
        "WW.================",
        "WW.......=.........",
        "WW.......=.........",
        "WW.......=.........",
        "WW.......=.........",
        "WW.......=.........",
        "WW.......=.........",
        "WW.................",
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
    ],
    [ // room (1,4)
        "........kpk........",
        "........kpk........",
        "kkkkkkkkkpkkkkkkkkk",
        "ppppppppppppppppppp",
        "kkkkkkkkkpkkkkkkkkk",
        "........kpk........",
        "........kpk........",
        "kkkkkkkkkpkkkkkkkkk",
        "ppppppppppppppppppp",
        "kkkkkkkkkpkkkkkkkkk",
        "...................",
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
    ],
    [ // room (2,4)
        ".......k___k.......",
        ".......k___k.......",
        "kkkkkkkk___kkkkkkkk",
        "pppppppk___kppppppp",
        "kkkkkkpk___kpkkkkkk",
        ".......k___k.......",
        ".......k___k.......",
        "kkkkkkkk___kkkkkkkk",
        "pppppppk___kppppppp",
        "kkkkkkkk___kkkkkkkk",
        ".......k___k.......",
        "WWWWWWWk___kWWWWWWW",
        "WWWWWWWk___kWWWWWWW",
    ],
    [ // room (3,4)
        "...............kppk",
        ".hhhhh.WWWWWWWWkppk",
        ".h...h.WWWWWWWWkpkk",
        "ph...h.WWWWWWWWkppp",
        "ph..khkWWWWppWWkpkk",
        "ph..kppppppppppppk.",
        "ph..kppppppppppppk.",
        "pkkkkppppppppppppk.",
        "pppppppppppppppppk.",
        "kkkkkhkkkkkkkkkkkk.",
        ".hhhhh.............",
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
    ],
    [ // room (4,4)
        ".................WW",
        ".................WW",
        ".........=.......WW",
        "================.WW",
        ".........=.......WW",
        ".........=.......WW",
        ".........=.......WW",
        ".........=.......WW",
        ".........=.......WW",
        ".........=.......WW",
        ".................WW",
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
    ],
];

/// The authored room. The capital is ITS OWN biome: walls bake to CASTLE
/// STONE ('K') no matter the surrounding biome, and every path/pad bakes to
/// the capital's cobble ('q'); 'k' kerbs pass through.
/// DEV TILE PAINTER overrides: (kx, ky, idx) -> final tile char (idx = r*19+c).
static TILE_EDITS: OnceLock<RwLock<HashMap<(i32, i32, usize), char>>> = OnceLock::new();
pub fn tile_edits() -> &'static RwLock<HashMap<(i32, i32, usize), char>> {
    TILE_EDITS.get_or_init(|| RwLock::new(HashMap::new()))
}

pub fn room_map(kx: i32, ky: i32, _wall: char) -> RoomMap {
    let t = &TEMPLATES[(ky * 5 + kx) as usize];
    let mut map: Vec<String> = t.iter().map(|r| r.chars().map(|c| match c { 'W' => 'K', 'p' | '_' => 'q', other => other }).collect()).collect();
    if let Ok(ed) = tile_edits().read() {
        if !ed.is_empty() {
            let mut rows: Vec<Vec<char>> = map.iter().map(|r| r.chars().collect()).collect();
            for ((ekx, eky, idx), ch) in ed.iter() {
                if *ekx == kx && *eky == ky && idx / 19 < 13 {
                    rows[idx / 19][idx % 19] = *ch;
                }
            }
            map = rows.into_iter().map(|r| r.into_iter().collect()).collect();
        }
    }
    let prot: HashSet<usize> = (0..13 * 19).collect();
    RoomMap { map, prot }
}
