//! capital.rs — THE CASTLE TOWN v3: a 5x5 walled capital with a TRUE CENTRE
//! (Baz: "5 wide... a middle room without splitting"). The ROYAL WAY runs the
//! centre column from the S gate to the castle mouth; the CROSS WAY runs the
//! centre row gate to gate; they meet at the GRAND PLAZA. Castle keep dead-
//! centre north with curtain wings; twin pond parks, parterres, market pair,
//! commons, a residential district, orchards, and the cathedral quarter.
//! Every tile authored + protected; dressing is authored props only.

use super::generate::RoomMap;
use std::collections::HashSet;

#[rustfmt::skip]
static TEMPLATES: [[&str; 13]; 25] = [
    [ // room (0,0)
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
        "WW.................",
        "WW....ppppppppp....",
        "WW....p~~~~~~~pkkkk",
        "WW....p~~~~~~~ppppp",
        "WW....p~~~~~~~ppppp",
        "WW....p~~~~~~~pkkkk",
        "WW....p~~~~~~~p....",
        "WW....p~~~~~~~p....",
        "WW....p~~~~~~~p....",
        "WW....ppppppppp....",
        "WW.....kpppk.......",
    ],
    [ // room (1,0)
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
        "ppppppppppppppppppp",
        "ppppppppppppppppppp",
        "...................",
        "...................",
        "...................",
        "...................",
        "...................",
        "...................",
    ],
    [ // room (2,0)
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWkpppkWWWWWWW",
        "WWWWWWWkpppkWWWWWWW",
        "WWWWWWWkpppkWWWWWWW",
        "pppppppk___kppppppp",
        "pppppppk___kppppppp",
        "pppppppk___kppppppp",
        "pppppppk___kppppppp",
        "pppppppk___kppppppp",
    ],
    [ // room (3,0)
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
        "ppppppppppppppppppp",
        "ppppppppppppppppppp",
        "...................",
        "...................",
        "...................",
        "...................",
        "...................",
        "...................",
    ],
    [ // room (4,0)
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
        ".................WW",
        "....ppppppppp....WW",
        "kkkkp~~~~~~~p....WW",
        "ppppp~~~~~~~p....WW",
        "ppppp~~~~~~~p....WW",
        "kkkkp~~~~~~~p....WW",
        "....p~~~~~~~p....WW",
        "....p~~~~~~~p....WW",
        "....p~~~~~~~p....WW",
        "....ppppppppp....WW",
        ".......kpppk.....WW",
    ],
    [ // room (0,1)
        "WW.....kpppk.......",
        "WWhhhhhkpppkhhhhh..",
        "WWh...hkpppkh...h..",
        "WWhhhhhkpppkhhhhh..",
        "WWkkkkkkpppkkkkkk..",
        "WWpppppkpppkppppp..",
        "WWkkkkkkpppkkkkkk..",
        "WWhhhhhkpppkhhhhh..",
        "WWh...hkpppkh...h..",
        "WWhhhhhkpppkhhhhh..",
        "WW.....kpppk.......",
        "WW.................",
        "WW.................",
    ],
    [ // room (1,1)
        "...................",
        "...................",
        "....kkkkkkkkkkk....",
        "....kpppppppppk....",
        "....kpppppppppkkkkk",
        "....kpppppppppppppp",
        "....kpppppppppppppp",
        "....kpppppppppkkkkk",
        "....kpppppppppk....",
        "....kkkkkpkkkkk....",
        "........kpk........",
        "........kpk........",
        "........kpk........",
    ],
    [ // room (2,1)
        ".......k___k.......",
        ".......k___k.......",
        ".......k___k.......",
        ".......k___k.......",
        "kkkkkkkk___kkkkkkkk",
        "ppppppp_____ppppppp",
        "ppppppp_____ppppppp",
        "kkkkkkkk___kkkkkkkk",
        ".......k___k.......",
        ".......k___k.......",
        ".......k___k.......",
        ".......k___k.......",
        ".......k___k.......",
    ],
    [ // room (3,1)
        "...................",
        "...................",
        "....kkkkkkkkkkk....",
        "....kpppppppppk....",
        "kkkkkpppppppppk....",
        "ppppppppppppppk....",
        "ppppppppppppppk....",
        "kkkkkpppppppppk....",
        "....kpppppppppk....",
        "....kkkkkpkkkkk....",
        "........kpk........",
        "........kpk........",
        "........kpk........",
    ],
    [ // room (4,1)
        ".......kpppk.....WW",
        "..hhhhhkpppkhhhhhWW",
        "..h...hkpppkh...hWW",
        "..hhhhhkpppkhhhhhWW",
        "..kkkkkkpppkkkkkkWW",
        "..pppppkpppkpppppWW",
        "..kkkkkkpppkkkkkkWW",
        "..hhhhhkpppkhhhhhWW",
        "..h...hkpppkh...hWW",
        "..hhhhhkpppkhhhhhWW",
        ".......kpppk.....WW",
        ".................WW",
        ".................WW",
    ],
    [ // room (0,2)
        "WW.................",
        "WW.................",
        "WW.................",
        "WW.................",
        "WW.................",
        "kkkkkkkkkkkkkkkkkkk",
        "___________________",
        "___________________",
        "kkkkkkkkkkkkkkkkkkk",
        "WW.................",
        "WW.................",
        "WW.................",
        "WW.................",
    ],
    [ // room (1,2)
        "..kkkkkk___kkkkkk..",
        "..k_____________k..",
        "..k_____________k..",
        "..k_____________k..",
        "..k_____________k..",
        "kkk_____________kkk",
        "___________________",
        "___________________",
        "kkk_____________kkk",
        "..k_____________k..",
        "..k_____________k..",
        "..k_____________k..",
        "..kkkkkkkkkkkkkkk..",
    ],
    [ // room (2,2)
        ".......k___k.......",
        ".......k___k.......",
        "...kkkkk___kkkkk...",
        "...k___________k...",
        "...k___________k...",
        "kkkk____ppp____kkkk",
        "________ppp________",
        "________ppp________",
        "kkkk___________kkkk",
        "...k___________k...",
        "...kkkkk___kkkkk...",
        ".......k___k.......",
        ".......k___k.......",
    ],
    [ // room (3,2)
        "..kkkkkk___kkkkkk..",
        "..k_____________k..",
        "..k_____________k..",
        "..k_____________k..",
        "..k_____________k..",
        "kkk_____________kkk",
        "___________________",
        "___________________",
        "kkk_____________kkk",
        "..k_____________k..",
        "..k_____________k..",
        "..k_____________k..",
        "..kkkkkkkkkkkkkkk..",
    ],
    [ // room (4,2)
        ".................WW",
        ".................WW",
        ".................WW",
        ".................WW",
        ".................WW",
        "kkkkkkkkkkkkkkkkkkk",
        "___________________",
        "___________________",
        "kkkkkkkkkkkkkkkkkkk",
        ".................WW",
        ".................WW",
        ".................WW",
        ".................WW",
    ],
    [ // room (0,3)
        "WW.................",
        "WW.................",
        "WW...kkkkkkkkkk....",
        "WW...kppppppppk....",
        "WW...kppppppppk....",
        "WW...kppppppppkkkkk",
        "WW...kppppppppppppp",
        "WW...kppppppppppppp",
        "WW...kppppppppkkkkk",
        "WW...kkkkkkkkkk....",
        "WW.................",
        "WW.................",
        "WW.................",
    ],
    [ // room (1,3)
        "...................",
        "...................",
        "...................",
        "...................",
        "...................",
        "kkkkkkkkkkkkkkkkkkk",
        "ppppppppppppppppppp",
        "ppppppppppppppppppp",
        "kkkkkkkkkpkkkkkkkkk",
        "........kpk........",
        "........kpk........",
        "........kpk........",
        "........kpk........",
    ],
    [ // room (2,3)
        ".......k___k.......",
        ".......k___k.......",
        ".......k___k.......",
        ".......k___k.......",
        ".......k___k.......",
        "kkkkkkkk___kkkkkkkk",
        "___________________",
        "___________________",
        "kkkkkkkk___kkkkkkkk",
        ".......k___k.......",
        ".......k___k.......",
        ".......k___k.......",
        ".......k___k.......",
    ],
    [ // room (3,3)
        "...................",
        "...................",
        "...................",
        "...................",
        "...................",
        "kkkkkkkkkkkkkkkkkkk",
        "ppppppppppppppppppp",
        "ppppppppppppppppppp",
        "kkkkkkkkkkkkkkkkppk",
        "...............kppk",
        "...............kppk",
        "...............kppk",
        "...............kppk",
    ],
    [ // room (4,3)
        ".................WW",
        ".................WW",
        "....kkkkkkkkkk...WW",
        "....kppppppppk...WW",
        "....kppppppppk...WW",
        "kkkkkppppppppk...WW",
        "pppppppppppppk...WW",
        "pppppppppppppk...WW",
        "kkkkkppppppppk...WW",
        "....kkkkkkkkkk...WW",
        ".................WW",
        ".................WW",
        ".................WW",
    ],
    [ // room (0,4)
        "WW.................",
        "WW.................",
        "WW.......=.........",
        "WW.================",
        "WW.......=.........",
        "WW.......=.........",
        "WW.......=.........",
        "WW.......=.........",
        "WW.......=.........",
        "WW.......=.........",
        "WW.................",
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
    ],
    [ // room (1,4)
        "........kpk........",
        "........kpk........",
        "kkkkkkkkkpkkkkkkkkk",
        "ppppppppppppppppppp",
        "kkkkkkkkkpkkkkkkkkk",
        "........kpk........",
        "........kpk........",
        "kkkkkkkkkpkkkkkkkkk",
        "ppppppppppppppppppp",
        "kkkkkkkkkpkkkkkkkkk",
        "...................",
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
    ],
    [ // room (2,4)
        ".......k___k.......",
        ".......k___k.......",
        "kkkkkkkk___kkkkkkkk",
        "ppppppp_____ppppppp",
        "kkkkkkpk___kpkkkkkk",
        ".......k___k.......",
        ".......k___k.......",
        "kkkkkkkk___kkkkkkkk",
        "ppppppp_____ppppppp",
        "kkkkkkkk___kkkkkkkk",
        ".......k___k.......",
        "WWWWWWWk___kWWWWWWW",
        "WWWWWWWk___kWWWWWWW",
    ],
    [ // room (3,4)
        "...............kppk",
        ".hhhhhWWWWWWWWWkppk",
        ".h...hWWWWWWWWWkpkk",
        "ph...hWWWWWWWWWkppp",
        "ph..khWWWWppWWWkpkk",
        "ph..kppppppppppppk.",
        "ph..kppppppppppppk.",
        "pkkkkppppppppppppk.",
        "pppppppppppppppppk.",
        "kkkkkhkkkkkkkkkkkk.",
        ".hhhhh.............",
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
    ],
    [ // room (4,4)
        ".................WW",
        ".................WW",
        ".........=.......WW",
        "================.WW",
        ".........=.......WW",
        ".........=.......WW",
        ".........=.......WW",
        ".........=.......WW",
        ".........=.......WW",
        ".........=.......WW",
        ".................WW",
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
    ],
];

/// The authored room. The capital is ITS OWN biome: walls bake to CASTLE
/// STONE ('K') no matter the surrounding biome, and every path/pad bakes to
/// the capital's cobble ('q'); 'k' kerbs pass through.
pub fn room_map(kx: i32, ky: i32, _wall: char) -> RoomMap {
    let t = &TEMPLATES[(ky * 5 + kx) as usize];
    let map: Vec<String> = t.iter().map(|r| r.chars().map(|c| match c { 'W' => 'K', 'p' | '_' => 'q', other => other }).collect()).collect();
    let prot: HashSet<usize> = (0..13 * 19).collect();
    RoomMap { map, prot }
}
