//! capital.rs — THE CASTLE TOWN's authored floor (Baz: "its own biome... every
//! floor tile placed specifically"). Sixteen 19x13 templates: the castle across
//! the north wall (no north gate — the keep IS the north face), forecourt and
//! market on the avenue, a pond park, a hedge garden, lanes and a commons.
//! 'W' bakes to the rampart wall char; everything is protected ground — the
//! capital's dressing is authored props, never biome scatter.

use super::generate::RoomMap;
use std::collections::HashSet;

#[rustfmt::skip]
static TEMPLATES: [[&str; 13]; 16] = [
    [ // room (0,0)
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
        "WW.................",
        "WW...pppppppppp....",
        "WW...p~~~~~~~~p....",
        "WW...p~~~~~~~~p....",
        "WW...p~~~~~~~~p....",
        "WW...p~~~~~~~~p....",
        "WW...p~~~~~~~~p....",
        "WW...pppppppppp....",
        "WW.................",
        "WW.................",
        "WW.................",
    ],
    [ // room (1,0)
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWpp",
        "WWWWWWWWWWWWWWWWWpp",
        "WWWWWWWWWWWWWWWWWpp",
        "ppppppppppppppppppp",
        "ppppppppppppppppppp",
        "ppppppppppppppppppp",
        "ppppppppppppppppppp",
        "ppppppppppppppppppp",
    ],
    [ // room (2,0)
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
        "ppWWWWWWWWWWWWWWWWW",
        "ppWWWWWWWWWWWWWWWWW",
        "ppWWWWWWWWWWWWWWWWW",
        "pppppppp____ppppppp",
        "pppppppp____ppppppp",
        "pppppppp____ppppppp",
        "pppppppp____ppppppp",
        "pppppppp____ppppppp",
    ],
    [ // room (3,0)
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
        ".........=.......WW",
        ".........=.......WW",
        ".........=.......WW",
        ".........=.......WW",
        "..==============.WW",
        ".........=.......WW",
        ".........=.......WW",
        ".........=.......WW",
        ".........=.......WW",
        ".........=.......WW",
        ".................WW",
    ],
    [ // room (0,1)
        "WW.................",
        "WW.......pp........",
        "WW.WWWWWWppWWWWWW..",
        "WW.WWWWWWppWWWWWW..",
        "WW.......pp........",
        "WW_________________",
        "WW_________________",
        "WW_________________",
        "WW_________________",
        "WW.......pp........",
        "WW.WWWWWWppWWWWWW..",
        "WW.WWWWWWppWWWWWW..",
        "WW.................",
    ],
    [ // room (1,1)
        "...................",
        "..ppppppppppppppppp",
        "..ppppppppppppppppp",
        "..ppppppppppppppppp",
        "..ppppppppppppppppp",
        "___________________",
        "___________________",
        "___________________",
        "___________________",
        "...................",
        "...................",
        "...................",
        "...................",
    ],
    [ // room (2,1)
        "........____.......",
        "ppppppppppppppppp..",
        "ppppppppppppppppp..",
        "ppppppppppppppppp..",
        "ppppppppppppppppp..",
        "___________________",
        "___________________",
        "___________________",
        "___________________",
        "........____.......",
        "........____.......",
        "........____.......",
        "........____.......",
    ],
    [ // room (3,1)
        ".................WW",
        ".................WW",
        ".................WW",
        ".................WW",
        ".................WW",
        "___________________",
        "___________________",
        "___________________",
        "___________________",
        ".................WW",
        ".................WW",
        ".................WW",
        ".................WW",
    ],
    [ // room (0,2)
        "WW.................",
        "WW.................",
        "WW.................",
        "WW.................",
        "WW.................",
        "___________________",
        "___________________",
        "___________________",
        "___________________",
        "WW.................",
        "WW.................",
        "WW.................",
        "WW.................",
    ],
    [ // room (1,2)
        "...................",
        "...................",
        ".._________________",
        ".._________________",
        ".._________________",
        "___________________",
        "___________________",
        "___________________",
        "___________________",
        ".._________________",
        ".._________________",
        ".._________________",
        "...................",
    ],
    [ // room (2,2)
        "........____.......",
        "........____.......",
        "_________________..",
        "_________________..",
        "_________________..",
        "___________________",
        "___________________",
        "___________________",
        "___________________",
        "_________________..",
        "_________________..",
        "_________________..",
        "........____.......",
    ],
    [ // room (3,2)
        ".................WW",
        ".................WW",
        ".....pppppppppp..WW",
        ".....pppppppppp..WW",
        ".....pppppppppp..WW",
        "_________________WW",
        "_________________WW",
        "_________________WW",
        "_________________WW",
        "........====.....WW",
        "........====.....WW",
        "........====.....WW",
        ".................WW",
    ],
    [ // room (0,3)
        "WW.................",
        "WW.................",
        "WW.................",
        "WW===============..",
        "WW.................",
        "WW.................",
        "WW.................",
        "WW.................",
        "WW.................",
        "WW===============..",
        "WW.................",
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
    ],
    [ // room (1,3)
        "...................",
        "...................",
        "....=..........=...",
        "....=..........=...",
        "....=..pppppp..=...",
        "..===============..",
        "....=..pppppp..=...",
        "....=..pppppp..=...",
        "....=..........=...",
        "....=..........=...",
        "...................",
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
    ],
    [ // room (2,3)
        "........____.......",
        "........____.......",
        "........____.......",
        "........____.......",
        "........____.......",
        "........____.......",
        "........____.......",
        "........____.......",
        "........____.......",
        "........____.......",
        "........____.......",
        "WWWWWWWW____WWWWWWW",
        "WWWWWWWW____WWWWWWW",
    ],
    [ // room (3,3)
        ".................WW",
        ".................WW",
        ".................WW",
        "..===============WW",
        ".................WW",
        ".................WW",
        ".................WW",
        ".................WW",
        ".................WW",
        "..===============WW",
        ".................WW",
        "WWWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWWWWW",
    ],
];

/// The authored room, walls baked to this biome's rampart char. Every tile is
/// protected: nothing procedural may scatter inside the walls.
pub fn room_map(kx: i32, ky: i32, wall: char) -> RoomMap {
    let t = &TEMPLATES[(ky * 4 + kx) as usize];
    let map: Vec<String> = t.iter().map(|r| r.chars().map(|c| if c == 'W' { wall } else { c }).collect()).collect();
    let prot: HashSet<usize> = (0..13 * 19).collect();
    RoomMap { map, prot }
}
