// GENERATED from js/enemies.js + js/items.js — do not edit.

pub const GOBLIN_FRAMES: &[(&str, [[&str; 16]; 2])] = &[
    ("down", [["................", "..K..........K..", "..Kq........qK..", "...KqqqqqqqqK...", "...KQqqqqqqQK...", "...KqrqqqqrqK...", "...KqqqqqqqqK...", "...KqQKKKKQqK...", "..KQqqqqqqqqQK..", "..KqqqqqqqqqqK..", "..KqKddddddKqK..", "....KDddddDK....", ".....qq..qq.....", ".....qq..dd.....", ".....dd.........", "................"], ["................", "..K..........K..", "..Kq........qK..", "...KqqqqqqqqK...", "...KQqqqqqqQK...", "...KqrqqqqrqK...", "...KqqqqqqqqK...", "...KqQKKKKQqK...", "..KQqqqqqqqqQK..", "..KqqqqqqqqqqK..", "..KqKddddddKqK..", "....KDddddDK....", ".....qq..qq.....", ".....dd..qq.....", ".........dd.....", "................"]]),
    ("up", [["................", "..K..........K..", "..Kq........qK..", "...KqqqqqqqqK...", "...KQQqqqqQQK...", "...KqqqqqqqqK...", "...KqqQqqQqqK...", "...KqqqqqqqqK...", "..KQqqqqqqqqQK..", "..KqqqqqqqqqqK..", "..KqKddddddKqK..", "....KDdDDdDK....", ".....qq..qq.....", ".....qq..dd.....", ".....dd.........", "................"], ["................", "..K..........K..", "..Kq........qK..", "...KqqqqqqqqK...", "...KQQqqqqQQK...", "...KqqqqqqqqK...", "...KqqQqqQqqK...", "...KqqqqqqqqK...", "..KQqqqqqqqqQK..", "..KqqqqqqqqqqK..", "..KqKddddddKqK..", "....KDdDDdDK....", ".....qq..qq.....", ".....dd..qq.....", ".........dd.....", "................"]]),
    ("left", [["................", "...........K....", "..........KqK...", ".......KKqqqK...", "......KqqqqqqK..", ".....KqqrqqqqK..", "...KKqqqqqqqqK..", ".....KqqqqqqqK..", ".....KqqqqqqQKK.", "....KqqqqqqqqqK.", "....KKddddddKqK.", ".....KDddddDK...", "......qq..qq....", "......dd..qq....", "..........dd....", "................"], ["................", "...........K....", "..........KqK...", ".......KKqqqK...", "......KqqqqqqK..", ".....KqqrqqqqK..", "...KKqqqqqqqqK..", ".....KqqqqqqqK..", ".....KqqqqqqQKK.", "....KqqqqqqqqqK.", "....KKddddddKqK.", ".....KDddddDK...", "......qq..qq....", "......qq..dd....", ".....dd.........", "................"]]),
    ("right", [["................", "....K...........", "...KqK..........", "...KqqqKK.......", "..KqqqqqqK......", "..KqqqqrqqK.....", "..KqqqqqqqqKK...", "..KqqqqqqqK.....", ".KKQqqqqqqK.....", ".KqqqqqqqqqK....", ".KqKddddddKK....", "...KDddddDK.....", "....qq..qq......", "....qq..dd......", "....dd..........", "................"], ["................", "....K...........", "...KqK..........", "...KqqqKK.......", "..KqqqqqqK......", "..KqqqqrqqK.....", "..KqqqqqqqqKK...", "..KqqqqqqqK.....", ".KKQqqqqqqK.....", ".KqqqqqqqqqK....", ".KqKddddddKK....", "...KDddddDK.....", "....qq..qq......", "....dd..qq......", ".........dd.....", "................"]]),
];

pub const SPEAR_FRAMES: &[(&str, [[&str; 16]; 2])] = &[
    ("down", [["................", "..K..........K..", "..Ku........uK..", "...KuuuuuuuuK...", "...KUuuuuuuUK...", "...KuruuuuruK...", "...KuuuuuuuuK...", "...KuUKKKKUuK...", "..KUuuuuuuuuUK..", "..KuuuuuuuuuuK..", "..KuKddddddKuK..", "....KDddddDK....", ".....uu..uu.....", ".....uu..dd.....", ".....dd.........", "................"], ["................", "..K..........K..", "..Ku........uK..", "...KuuuuuuuuK...", "...KUuuuuuuUK...", "...KuruuuuruK...", "...KuuuuuuuuK...", "...KuUKKKKUuK...", "..KUuuuuuuuuUK..", "..KuuuuuuuuuuK..", "..KuKddddddKuK..", "....KDddddDK....", ".....uu..uu.....", ".....dd..uu.....", ".........dd.....", "................"]]),
    ("up", [["................", "..K..........K..", "..Ku........uK..", "...KuuuuuuuuK...", "...KUUuuuuUUK...", "...KuuuuuuuuK...", "...KuuUuuUuuK...", "...KuuuuuuuuK...", "..KUuuuuuuuuUK..", "..KuuuuuuuuuuK..", "..KuKddddddKuK..", "....KDdDDdDK....", ".....uu..uu.....", ".....uu..dd.....", ".....dd.........", "................"], ["................", "..K..........K..", "..Ku........uK..", "...KuuuuuuuuK...", "...KUUuuuuUUK...", "...KuuuuuuuuK...", "...KuuUuuUuuK...", "...KuuuuuuuuK...", "..KUuuuuuuuuUK..", "..KuuuuuuuuuuK..", "..KuKddddddKuK..", "....KDdDDdDK....", ".....uu..uu.....", ".....dd..uu.....", ".........dd.....", "................"]]),
    ("left", [["................", "...........K....", "..........KuK...", ".......KKuuuK...", "......KuuuuuuK..", ".....KuuruuuuK..", "...KKuuuuuuuuK..", ".....KuuuuuuuK..", ".....KuuuuuuUKK.", "....KuuuuuuuuuK.", "....KKddddddKuK.", ".....KDddddDK...", "......uu..uu....", "......dd..uu....", "..........dd....", "................"], ["................", "...........K....", "..........KuK...", ".......KKuuuK...", "......KuuuuuuK..", ".....KuuruuuuK..", "...KKuuuuuuuuK..", ".....KuuuuuuuK..", ".....KuuuuuuUKK.", "....KuuuuuuuuuK.", "....KKddddddKuK.", ".....KDddddDK...", "......uu..uu....", "......uu..dd....", ".....dd.........", "................"]]),
    ("right", [["................", "....K...........", "...KuK..........", "...KuuuKK.......", "..KuuuuuuK......", "..KuuuuruuK.....", "..KuuuuuuuuKK...", "..KuuuuuuuK.....", ".KKUuuuuuuK.....", ".KuuuuuuuuuK....", ".KuKddddddKK....", "...KDddddDK.....", "....uu..uu......", "....uu..dd......", "....dd..........", "................"], ["................", "....K...........", "...KuK..........", "...KuuuKK.......", "..KuuuuuuK......", "..KuuuuruuK.....", "..KuuuuuuuuKK...", "..KuuuuuuuK.....", ".KKUuuuuuuK.....", ".KuuuuuuuuuK....", ".KuKddddddKK....", "...KDddddDK.....", "....uu..uu......", "....dd..uu......", ".........dd.....", "................"]]),
];

pub const GOB_AXE: &[&str] = &["..aAAa..", ".aAAAAa.", ".aAAAAa.", "..aAAa..", "...DD...", "...DD...", "...DD...", "........"];

pub const PEBBLE: &[&str] = &["........", "..aaa...", ".aAaan..", ".aaaan..", ".aaann..", "..nnn...", "........", "........"];

pub const SWORD: &[&str] = &["...WW...", "...AA...", "...AA...", "...AA...", "...AA...", "...AA...", "...AA...", "...AA...", ".DDDDDD.", "...dd...", "...dd...", "...dd...", "...yy...", "........", "........", "........"];

pub const SWORD_ICON: &[&str] = &["......WW", ".....WAW", "....WAW.", "...WAW..", "..WAW...", ".DAWD...", "DDDW....", "yD......"];
