// GENERATED by tools/extract_mobs.mjs from js/enemies.js — do not edit.
//! mobs_art.rs — base-roster mob sprites (right-facing grids; flip left at bake) + the
//! bestiary names/descs. Wolf carries per-facing frames like the goblins.

pub struct MobFrame {
    pub grid: &'static [&'static str],
    pub pal: &'static [(char, u32)],
}

pub static BOAR_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", "....ddddddd.....", "..ddDDDDDDDDd...", ".dDDDDDDDDDDDds.", ".dDDDDKDDDDDDss.", ".dDDDDDDDDDDDDW.", ".dDDDDDDDDDDDsW.", "..dDDDDDDDDDDd..", "..d.dd...dd.d...", "................"], pal: &[] }];
pub static WASP_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", "...A.......A....", "..A.A.....A.A...", "...AA.....AA....", ".....yyyyy......", "....yKyyKy......", "....yyyyyy......", ".....yyyy.......", "......oo........", "................"], pal: &[] }, MobFrame { grid: &["................", "................", "...AA.....AA....", "..A.A.....A.A...", ".....yyyyy......", "....yKyyKy......", "....yyyyyy......", ".....yyyy.......", "......oo........", "................"], pal: &[] }];
pub static THORNLING_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", ".....ggg........", "...gglllgg......", "..gllWllWlg.....", "..gllKllKlg.....", "..glllllllg.....", "..gGlllllGg.....", "...gG...Gg......", "....g...g.......", "................"], pal: &[] }];
pub static BEAR_FRAMES: &[MobFrame] = &[MobFrame { grid: &["...dddd.........", "..dDDDDdd..dd...", ".dDDDDDDDDdDDd..", ".dDDDDDDDDDDDDd.", ".dDDDDDDDDDKDSS.", ".dDDDDDDDDDDDSs.", "..dDDDDDDDDDDd..", "..dDDd..dDDd....", "..dDDd..dDDd....", "..ddd....ddd...."], pal: &[] }, MobFrame { grid: &["...dddd.........", "..dDDDDdd..dd...", ".dDDDDDDDDdDDd..", ".dDDDDDDDDDDDDd.", ".dDDDDDDDDDKDSS.", ".dDDDDDDDDDDDSs.", "..dDDDDDDDDDDd..", "...dDDd.dDDd....", "...dDDd.dDDd....", "....ddd..ddd...."], pal: &[] }];
pub static SPIDER_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", ".n..........n...", "..nn......nn....", "...nnnnnnnn.....", "..nnnnnnnnnn....", "..nlnnnnnnln....", "..nnnnnnnnnn....", "...nn....nn.....", "..n........n....", "................"], pal: &[] }];
pub static SCORPION_FRAMES: &[MobFrame] = &[MobFrame { grid: &["..Srr...........", ".SS.............", ".SS.............", ".SS.........SSS.", "..SSSSSSSSS.S...", "..SySSSSSSySSS..", "..SSSSSSSSS.S...", ".n.n..n..n..SSS.", "................", "................"], pal: &[] }, MobFrame { grid: &["...Srr..........", "..SS............", "..SS............", "..SS........SSS.", "..SSSSSSSSS.S...", "..SySSSSSSySSS..", "..SSSSSSSSS.S...", "..n.n..n..n.SSS.", "................", "................"], pal: &[] }];
pub static BURROWER_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", "......yy........", ".....yYYy.......", ".....yKKy.......", "....yYYYYy......", "....yYYYYy......", "...yYYYYYYy.....", "...dYYYYYYd.....", "....dddddd......", "................"], pal: &[] }];
pub static VULTURE_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", "A..........A....", "AAA......AAA....", ".AAAA..AAAA.....", "....sss.s.......", "....nnnn........", "....nnnn........", ".....nn.........", "................", "................"], pal: &[] }, MobFrame { grid: &["................", "................", ".AAA....AAA.....", "..AAA..AAA......", "....sss.s.......", "....nnnn........", "....nnnn........", ".....nn.........", "................", "................"], pal: &[] }];
pub static GOLEM_FRAMES: &[MobFrame] = &[MobFrame { grid: &["...aaaaaaaa.....", "..aAAAAAAAAa....", ".aAAAAAAAAAAa...", ".aAArAAAArAAa...", ".aAAAAAAAAAAa...", ".aAAAAAAAAAAa...", ".aaAAAAAAAaaa...", "..aaAAAAaaaa....", "..aa...aaaa.....", "..aa...aa......."], pal: &[] }];
pub static BAT_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", "..n........n....", ".nnn......nnn...", ".nnnnn..nnnnn...", "...nnnnnnnn.....", "...nrnnnnrn.....", "....nnnnnn......", ".....n..n.......", "................", "................"], pal: &[] }, MobFrame { grid: &["................", "................", ".n..........n...", ".nnn......nnn...", "..nnnnnnnnnn....", "...nrnnnnrn.....", "....nnnnnn......", ".....n..n.......", "................", "................"], pal: &[] }];
pub static HURLER_FRAMES: &[MobFrame] = &[MobFrame { grid: &["...ggg.....aa...", "..gGGGg...aAAa..", "..gGKGg...aAAa..", "..gGGGg....aa...", "...ggg.q........", "..qgggq.........", "...ggg..........", "...g.g..........", "................", "................"], pal: &[] }];
pub static ZOMBIE_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", "....KKKKKK......", "...KggggggK.....", "...KgKggKgK.....", "...KgGgggGK.....", "...KgKWWKgK.....", "....KGGGGK......", "..gKddddddKg....", "..gKddrdddKg....", "..gKdDDDDdKg....", "..GKddddddKG....", "...KddddddK.....", "...KggKKggK.....", "...Kgg..ggK.....", "...KGG..GGK.....", "................"], pal: &[('g', 0x74925a), ('G', 0x46603a), ('W', 0xcfc8a0)] }, MobFrame { grid: &["................", "................", "....KKKKKK......", "...KggggggK.....", "...KgKggKgK.....", "...KgGgggGK.....", "...KgKWWKgK.....", "....KGGGGK......", "..gKddddddKg....", "..gKddrdddKg....", "..gKdDDDDdKg....", "..GKddddddKG....", "...KddddddK.....", "...KggKKggK.....", "...Kgg..ggK.....", "...KGG..GGK....."], pal: &[('g', 0x74925a), ('G', 0x46603a), ('W', 0xcfc8a0)] }];
pub static SKELETON_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", ".....AAAA.......", "....AAAAAA......", "....AKAAKA......", "....AAAAAA......", ".....AKKA.......", "......AA........", "...A..AA..A.....", "...A.AAAA.A.....", "....AAAAAA......", "....A.AA.A......", "....AAAAAA......", ".....A..A.......", ".....A..A.......", "....AA..AA......", "................"], pal: &[] }];
pub static ARCHER_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", ".....AAAA...D...", "....AAAAAA..DD..", "....AKAAKA..Dd..", "....AAAAAA..Dd..", ".....AKKA...Dd..", "......AA....Dd..", "...A..AAAAAADd..", "...A.AAAA...Dd..", "....AAAAAA..Dd..", "....A.AA.A..Dd..", "....AAAAAA..DD..", ".....A..A...D...", ".....A..A.......", "....AA..AA......", "................"], pal: &[] }];
pub static LEECH_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", "................", "................", "....ddSSdd......", "...dSSSSSSd.....", "...dSrSSrSd.....", "...dSSSSSSd.....", "....dSSSSd......", "................", "................"], pal: &[] }, MobFrame { grid: &["................", "................", ".....dSSd.......", "....dSSSSd......", "...dSSSSSSd.....", "...dSSrrSSd.....", "...dSSSSSSd.....", "....dSSSSd......", ".....dSSd.......", "................"], pal: &[] }];
pub static GNAT_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", "................", "................", ".....A.n.A......", "......nnn.......", ".......n........", "......n.n.......", "................", "................", "................"], pal: &[] }, MobFrame { grid: &["................", "................", "................", "......AnA.......", "......nnn.......", ".......n........", "......n.n.......", "................", "................", "................"], pal: &[] }];
pub static LURKER_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", "..E..E..E..E....", ".EGGGGGGGGGGE...", ".GGKGGGGGGKGG...", ".GGGGGGGGGGGG...", "WGGGGGGGGGGGGW..", ".GGqGGGGGGqGG...", ".GGGGGGGGGGGG...", "..GG.GG.GG.G....", "................"], pal: &[] }, MobFrame { grid: &["................", "..E..E..E..E....", ".EGGGGGGGGGGE...", ".GGKGGGGGGKGG...", ".GGGGGGGGGGGG...", "WWGGGGGGGGGGWW..", ".GGqGGGGGGqGG...", ".GGGGGGGGGGGG...", ".G..GG.GG..GG...", "................"], pal: &[] }];
pub static GHOUL_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", "....qq..qq......", "...qQqGGqQq.....", "...qKqGGqKq.....", "...qqqGGqqq.....", "..qqqqGGqqqq....", "...qqGGGGqq.....", "....qq..qq......", "................", "................"], pal: &[] }];
pub static WRAITH_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", ".....AAAA.......", "....AWWWWA......", "....WKWWKW......", "....WWWWWW......", "....AWWWWA......", "...A.WWWW.A.....", "....A.WW.A......", ".....W..W.......", "................"], pal: &[] }];
pub static REVENANT_FRAMES: &[MobFrame] = &[MobFrame { grid: &["....aaaa........", "...aAKKAa.......", "...aAAAAa.......", "..aaAAAAaa......", "..nAAAAAAn......", "..nAAAAAAn......", "..nAAAAAAn......", "...AA..AA.......", "..AA....AA......", "................"], pal: &[] }];
pub static FROSTMITE_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", ".......B........", "......BFB.......", ".....BFFFB......", "....BFWFWFB.....", "....BFFFFFB.....", ".....BFFFB......", "......BFB.......", ".......B........", "................"], pal: &[] }];
pub static ICETROLL_FRAMES: &[MobFrame] = &[MobFrame { grid: &["....FFFFFF......", "...FWWWWWWF.....", "..FWWffffWWF....", "..FWfKffKfWF....", "..FWffffffWF....", "..FWWffffWWF....", "..FFWWWWWWFF....", "...FF.FF.FF.....", "...FF.FF.FF.....", "................"], pal: &[] }];
pub static FROSTWYRM_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", ".....fFFf.......", "....fWWWWf......", "....fWKWKf......", "....fWWWWf......", ".....fFFf..fF...", "......fFFffFf...", ".......fFFFf....", "........fff.....", "................"], pal: &[] }];
pub static CINDERHOUND_FRAMES: &[MobFrame] = &[MobFrame { grid: &["..n.......n.....", ".nKn.....nKn....", "..nKKKKKKKKn....", ".nKKKKKKKKKKn...", "nKKrKKKKKKrKn...", ".oKKKKKKKKo.....", "..nKKKKKKn......", "..n.nn.nn.n.....", "................", "................"], pal: &[] }];
pub static CHARBRUTE_FRAMES: &[MobFrame] = &[MobFrame { grid: &["...K........K...", "..KnK......KnK..", "..KnnnnnnnnnK...", ".KnnnnnnnnnnnK..", ".KnrnnnnnnrnnK..", ".KnnnnooonnnnK..", ".KnnnnnnnnnnnK..", "..KnnnnnnnnnK...", "..Knn...nnnK....", "..K.K...K.K....."], pal: &[] }];
pub static PYREWRAITH_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", ".....KKKK.......", "....KrrrrK......", "...KroooorK.....", "...KrooooK......", "....Krrrr.......", "....KK.KK.......", "...K..o..K......", "......o.........", "................"], pal: &[] }];
pub static SPORELING_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", "......mmm.......", "....mmWmmWm.....", "...mmmmmmmm.....", "...mmmmmmmm.....", "....WWWWWW......", ".....WKKW.......", ".....WWWW.......", "......WW........", "................"], pal: &[] }];
pub static MYCONID_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", ".....mmmm.......", "...mmWmmWmm.....", "...mmmmmmmm.....", "....uuuuuu......", "....uKuuKu......", "....uuuuuu......", "...u.uuuu.u.....", "....u....u......", "....l....l......"], pal: &[] }];
pub static SPOREMOTHER_FRAMES: &[MobFrame] = &[MobFrame { grid: &["....mmmmmm......", "..mmmWmmWmmm....", ".mmmmmmmmmmmm...", ".mmWmmmmmmWmm...", ".mmmmmmmmmmmm...", "...uuuuuuuu.....", "...uuKuuKuu.....", "...uuuuuuuu.....", "...uu....uu.....", "................"], pal: &[] }];
pub static CHAOSWISP_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", ".......x........", "......xXx.......", ".....xXmXx......", "....xXmmmXx.....", ".....xXmXx......", "......xXx.......", ".....x.x.x......", "................", "................"], pal: &[] }];
pub static VOIDLING_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", ".....xXXx.......", "....xKKKKx......", "...xKKKKKKx.....", "...xKWKKWKx.....", "...xKKKKKKx.....", "...xKKKKKKx.....", "....xKKKKx......", ".....x..x.......", "................"], pal: &[] }];
pub static RIFTLORD_FRAMES: &[MobFrame] = &[MobFrame { grid: &["....xXXXXx......", "...xXmmmmXx.....", "..xXmWmmWmXx....", "..xXmmmmmmXx....", "..xXmmmmmmXx....", "..xXXmmmmXXx....", "...xXmmmmXx.....", "...xX....Xx.....", "..xX......Xx....", "................"], pal: &[] }];
pub static CULTIST_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", ".....KKKKK......", "....KXXXXXK.....", "...KXXXXXXXK....", "...KXmXXXmXK....", "...KXXXXXXXK....", "..KXXXXXXXXXK...", "..KXXXxxxXXXK...", "..KXXXXXXXXXK...", "..KXXXXXXXXXK...", "...KXXXXXXXK....", "....KXXXXXK.....", ".....KKKKK......"], pal: &[] }];
pub static MIREFLY_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", "....W...W.......", "...W.W.W.W......", ".....KKK........", "....KlWlK.......", "....KWlWK.......", ".....KKK........", "......K.........", "................", "................"], pal: &[] }];
pub static BOGLIGHT_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", "......ll........", ".....lWWl.......", "....lWwwWl......", "....lWwwWl......", ".....lWWl.......", "......ll........", ".....l..l.......", "................", "................"], pal: &[] }];
pub static HONEYDRONE_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", "....W...W.......", "...WWW.WWW......", "....KPPPPK......", "...KPKPPKPK.....", "...KPPKKPPK.....", "....KPPPPK......", ".....KKKK.......", "......KK........", "................"], pal: &[] }, MobFrame { grid: &["................", "................", "....KPPPPK......", "...KPKPPKPK.....", "..WWKPPKKPPKWW..", "...WKPPPPKW.....", ".....KKKK.......", "......KK........", "................", "................"], pal: &[] }];
pub static GRAVEWARDEN_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", ".....KKKK.......", "....KnnnnK......", "...KnnnnnnK.....", "...KnWnnWnK.....", "...KnnnnnnK.....", "..KnnnnnnnnK....", "..KnnKnnKnnK....", "...Kn.nn.nK.....", "....P..........."], pal: &[] }, MobFrame { grid: &["................", ".....KKKK.......", "....KnnnnK......", "...KnnnnnnK.....", "...KnWnnWnK.....", "...KnnnnnnK.....", "..KnnnnnnnnK....", "..KnnKnnKnnK....", "...Kn.nn.nK.....", "..........P....."], pal: &[] }];
pub static PALEHOWLER_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", "..KK............", ".KAAK...KKK.....", "..KAAKKKAAAK....", "...KAAAAAAAK....", "...KAKAAAKAK....", "....KAAAAAK.....", "....KA.KA.K.....", "................", "................"], pal: &[] }, MobFrame { grid: &["...KAK..........", "..KAAK..........", "..KAAKKKKK......", "...KAAAAAAK.....", "...KAKAAAKK.....", "....KAAAAAK.....", "....KA.KA.K.....", "................", "................", "................"], pal: &[] }];
pub static SANDMAW_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", "................", "....yyyyyy......", "...yYWyyWYy.....", "..yYKKKKKKYy....", "..yWKddddKWy....", "..yYKddddKYy....", "...yYWKKWYy.....", "....yyyyyy......", "................"], pal: &[] }, MobFrame { grid: &["................", "................", "....yyyyyy......", "...yYWWyWYy.....", "..yYKKKKKKYy....", "..yWKdddKKWy....", "..yYKKdddKYy....", "...yYWWKWYy.....", "....yyyyyy......", "................"], pal: &[] }];
pub static STORMCALLER_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", ".....KKKK.......", "....KaAAaK......", "....KAwwAK......", "....KaAAaK......", "...KaaAAaaK.....", "...KaAAAAaK.....", "...KaaaaaaK.....", "....Ka..aK......", "................"], pal: &[] }, MobFrame { grid: &["................", ".w...KKKK...w...", "..w.KaAAaK.w....", "...KKAwwAKK.....", "...KaaAAaaK.....", "....KaAAaK......", "....KAAAAK......", "....KaaaaK......", "....Ka..aK......", "................"], pal: &[] }];
pub static SWITCHSHADE_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", ".....xXXx.......", "....XKKKKX......", "...XKKKKKKX.....", "...XKWKKWKX.....", "...XKKKKKKX.....", "....XKKKKX......", "...X.XKKX.X.....", "......XX........", "................"], pal: &[] }, MobFrame { grid: &["................", ".....xXXx.......", "....XKKKKX......", "...XKKKKKKX.....", "...XKWKKWKX.....", "...XKKKKKKX.....", "....XKKKKX......", "...X.XKKX.X.....", ".....X..X.......", "................"], pal: &[] }];
pub static TIDECRAB_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", "..KK........KK..", ".KYYK......KYYK.", ".KYK..KKKK..KYK.", "....KYyyyyK.....", "...KYyyyyyyK....", "...KyyKyyKyK....", "....KyyyyyK.....", "...K.K..K.K.....", "................"], pal: &[] }, MobFrame { grid: &["................", "..KK........KK..", ".KYYK......KYYK.", ".KYK..KKKK..KYK.", "....KYyyyyK.....", "...KYyyyyyyK....", "...KyyKyyKyK....", "....KyyyyyK.....", "....K.K..K.K....", "................"], pal: &[] }];
pub static VINESNARE_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", "...l......l.....", "..lGl....lGl....", "..lGGl..lGGl....", "...lGGllGGl.....", "....GGWWGG......", "...GGGGGGGG.....", "..GGGllllGGG....", "...GGGGGGGG.....", "................"], pal: &[] }, MobFrame { grid: &["................", "................", "................", "................", "....l..l........", "...lGllGl.......", "..lGGllGGl......", "...GGGGGG.......", "................", "................"], pal: &[] }];
pub static BELLSNAIL_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", ".....KKKK.......", "....KbBBbK......", "...KbBbbBbK.....", "...KbbBBbbK.....", "..WKBbbbbBK.....", ".WlWbBBBBb......", ".lllllKKKK......", "..lllll.........", "................"], pal: &[] }, MobFrame { grid: &["................", ".....KKKK.......", "....KbBBbK......", "...KbBbbBbK.....", "...KbbBBbbK.....", "...KBbbbbBK.....", "...KbBBBBbK.....", "....KKKKKK......", "................", "................"], pal: &[] }];
pub static SALTSTATUE_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", ".....AWWA.......", "....AWWWWA......", "....AWrrWA......", "...AWWWWWWA.....", "..AWWAWWAWWA....", "...AWWWWWWA.....", "...AWW..WWA.....", "...AW....WA.....", "................"], pal: &[] }, MobFrame { grid: &["................", ".....AWWA.......", "....AWWWWA......", "....AWKKWA......", "....AWWWWA......", "...AWWWWWWA.....", "...AWWWWWWA.....", "...AWWWWWWA.....", "....AW..WA......", "................"], pal: &[] }];
pub static GLIMMERLING_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", "......PP........", ".....PWWP.......", "....PPWWPP......", "....KPPPPK......", ".....PPPP.......", "....P.PP.P......", "......PP........", ".....P..P.......", "................"], pal: &[] }, MobFrame { grid: &["................", "......PP...W....", ".....PWWP.......", "....PPWWPP......", "....KPPPPK......", ".....PPPP.......", "....P.PP.P......", "......PP........", "....P....P......", "................"], pal: &[] }];
pub static WITHERHEART_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", "...KK...KK......", "..KqqK.KqqK.....", "..KqqqKqqqK.....", "..KqQqqqQqK.....", "...KqqqqqK......", "....KqQqK.......", ".....KqK........", "......K.........", "................"], pal: &[] }, MobFrame { grid: &["................", "...KK...KK......", "..KqqK.KqqK.....", "..KqWqKqqqK.....", "..KqQqqqQqK.....", "...KqqqqqK......", "....KqQqK.......", ".....KqK........", "......K.........", "................"], pal: &[] }];
pub static SLIME_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", "................", "................", "................", ".....wwww.......", "...wwwwwwww.....", "..wwwwwwwwww....", "..wwKwwwwKww....", "..wwwwwwwwww....", "..VwwwwwwwwV....", "..VVwwwwwwVV....", "...VVVVVVVV.....", "................", "................", "................", "................"], pal: &[] }];
pub static FROSTSLIME_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", "................", "................", "................", ".....wwww.......", "...wwwwwwww.....", "..wwwwwwwwww....", "..wwKwwwwKww....", "..wwwwwwwwww....", "..VwwwwwwwwV....", "..VVwwwwwwVV....", "...VVVVVVVV.....", "................", "................", "................", "................"], pal: &[('w', 0xcfeeff), ('V', 0x5f9fd0)] }];
pub static EMBERSLIME_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", "................", "................", "................", ".....wwww.......", "...wwwwwwww.....", "..wwwwwwwwww....", "..wwKwwwwKww....", "..wwwwwwwwww....", "..VwwwwwwwwV....", "..VVwwwwwwVV....", "...VVVVVVVV.....", "................", "................", "................", "................"], pal: &[('w', 0xfc9838), ('V', 0xd82800)] }];
pub static SPARKSLIME_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", "................", "................", "................", ".....wwww.......", "...wwwwwwww.....", "..wwwwwwwwww....", "..wwKwwwwKww....", "..wwwwwwwwww....", "..VwwwwwwwwV....", "..VVwwwwwwVV....", "...VVVVVVVV.....", "................", "................", "................", "................"], pal: &[('w', 0xfce84a), ('V', 0xe0a020), ('K', 0xfffbd0)] }];
pub static TOXICSLIME_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", "................", "................", "................", ".....wwww.......", "...wwwwwwww.....", "..wwwwwwwwww....", "..wwKwwwwKww....", "..wwwwwwwwww....", "..VwwwwwwwwV....", "..VVwwwwwwVV....", "...VVVVVVVV.....", "................", "................", "................", "................"], pal: &[('w', 0x9be86a), ('V', 0x3a8a2a)] }];
pub static FROG_FRAMES: &[MobFrame] = &[MobFrame { grid: &["................", "...G....G.......", "..GWG..GWG......", "..GKG..GKG......", "..GGGGGGGG......", ".GGGGGGGGGG.....", ".GGqGGGGqGG.....", ".GGGGGGGGGG.....", "..GG.GG.GG......", "................"], pal: &[] }, MobFrame { grid: &["................", "...G....G.......", "..GWG..GWG......", "..GKG..GKG......", "..GGGGGGGG......", ".GGGGGGGGGG.....", "GGGqGGGGqGGG....", "G.GGGGGGGG.G....", "....G..G........", "................"], pal: &[] }, MobFrame { grid: &["................", "...G....G.......", "..GWG..GWG......", "..GKG..GKG......", "..GGGGGGGG......", ".GGGGGGGGGG.....", ".GGooooooGG.....", ".GooooooooG.....", "..GG.GG.GG......", "................"], pal: &[] }];
pub static THORN_DORM: MobFrame = MobFrame { grid: &["................", ".....ggg........", "...gglllgg......", "..glllllllg.....", "..glllllllg.....", "..glllllllg.....", "..gGlllllGg.....", "...gGlllGg......", "....ggggg.......", "................"], pal: &[] };
pub static ARROW_SPR: MobFrame = MobFrame { grid: &["................", "................", "................", "................", ".........A......", "....dddddAAAA...", "....dddddAAAA...", ".........A......", "................", "................", "................", "................", "................", "................", "................", "................"], pal: &[] };
pub static WOLF_DOWN: &[MobFrame] = &[MobFrame { grid: &["................", "..n........n....", "..nn......nn....", "..naa....aan....", "...naaaaaaan....", "...naPaaPaan....", "...naaaaaaan....", "....naAAan......", ".....nAAn.......", "...naaaaaaan....", "..naaaaaaaaan...", "..na.aaaa.an....", "...n.n..n.n.....", "................", "................", "................"], pal: &[] }, MobFrame { grid: &["................", "..n........n....", "..nn......nn....", "..naa....aan....", "...naaaaaaan....", "...naPaaPaan....", "...naaaaaaan....", "....naAAan......", ".....nAAn.......", "...naaaaaaan....", "..naaaaaaaaan...", "..naaaaaaaaan...", "..nn.a..a.nn....", "................", "................", "................"], pal: &[] }];
pub static WOLF_UP: &[MobFrame] = &[MobFrame { grid: &["................", "..n........n....", "..nn......nn....", "..naa....aan....", "...naaaaaaan....", "...nananaann....", "...naaaaaaan....", "..naaaaaaaaan...", "..naaaaaaaaan...", "..naaaaaaaaan...", "...na.nn.an.....", "...nn.nn.nn.....", "......nn........", ".....nnn........", "......nn........", "................"], pal: &[] }, MobFrame { grid: &["................", "..n........n....", "..nn......nn....", "..naa....aan....", "...naaaaaaan....", "...nananaann....", "...naaaaaaan....", "..naaaaaaaaan...", "..naaaaaaaaan...", "..naaaaaaaaan...", "..nn.a..a.nn....", "...n.nn.n.n.....", "......nn........", ".....nnn........", "......nn........", "................"], pal: &[] }];
pub static WOLF_RIGHT: &[MobFrame] = &[MobFrame { grid: &["................", "................", "................", ".n........n.n...", "nna......nnannn.", "naan....naaaaan.", ".nan...naaaPaaAn", "..naaaaaaaaaaaAn", "..naaaaaaaaaan..", "..naaaaaaaan....", "...aa...aa......", "...nn...nn......", "................", "................", "................", "................"], pal: &[] }, MobFrame { grid: &["................", "................", "................", ".n........n.n...", "nna......nnannn.", "naan....naaaaan.", ".nan...naaaPaaAn", "..naaaaaaaaaaaAn", "..naaaaaaaaaan..", "..naaaaaaaan....", "..aa.....aa.....", "..nn.....nn.....", "................", "................", "................", "................"], pal: &[] }];

// These four enemies had unique AI but NO body art (never added to ALL_FRAMES), so they
// fired bolts / erupted / detonated while INVISIBLE (Baz). Sprites ported 1:1 from the JS
// reference (enemies.js pixel grids), padded from the JS 16x10 to our 16x16 convention.

/// Rooted crystal (prismshard): a faceted violet kite with a cyan edge + a moving white glint.
pub static PRISMSHARD_FRAMES: &[MobFrame] = &[
    MobFrame {
        grid: &[
            "................", "................", "................",
            "................", ".......c........", "......cvc.......",
            ".....cvWvc......", ".....cvvvc......", "....cvvWvvc.....",
            "....cvvvvvc.....", ".....cvvvc......", "......ccc.......",
            "................", "................", "................", "................",
        ],
        pal: &[('c', 0x6fe6e0), ('v', 0xb388ff), ('W', 0xfcfcfc)],
    },
    MobFrame {
        grid: &[
            "................", "................", "................",
            "................", ".......c........", "......cvc.......",
            ".....cvvvc......", ".....cWvvc......", "....cvvvWvc.....",
            "....cvvvvvc.....", ".....cvvvc......", "......ccc.......",
            "................", "................", "................", "................",
        ],
        pal: &[('c', 0x6fe6e0), ('v', 0xb388ff), ('W', 0xfcfcfc)],
    },
];

/// Rooted vent (ashgeyser): a dark mound with a red-hot core; frame B flings embers up.
pub static ASHGEYSER_FRAMES: &[MobFrame] = &[
    MobFrame {
        grid: &[
            "................", "................", "................",
            "................", "......nn........", ".....nrrn.......",
            "....nnrrnn......", "....nKnnKn......", "...nnKnnKnn.....",
            "...nnnKKnnn.....", "..nnnnnnnnnn....", "..KnnnnnnnnK....",
            "................", "................", "................", "................",
        ],
        pal: &[('n', 0x585858), ('r', 0xd82800), ('K', 0x000000), ('o', 0xfc7460)],
    },
    MobFrame {
        grid: &[
            "................", "................", "................",
            ".....o..o.......", "....o.oo.o......", ".....nrrn.......",
            "....nnrrnn......", "....nKnnKn......", "...nnKnnKnn.....",
            "...nnnKKnnn.....", "..nnnnnnnnnn....", "..KnnnnnnnnK....",
            "................", "................", "................", "................",
        ],
        pal: &[('n', 0x585858), ('r', 0xd82800), ('K', 0x000000), ('o', 0xfc7460)],
    },
];

/// Blind beetle (deepcrawler): a wide gray shell with black eye-spots + shifting violet legs.
pub static DEEPCRAWLER_FRAMES: &[MobFrame] = &[
    MobFrame {
        grid: &[
            "................", "................", "................",
            "................", "..v..v..v..v....", "...vvvvvvvv.....",
            "..vAAAAAAAAv....", "..vAKAAAAKAv....", "...vAAAAAAv.....",
            "..v.vvvvvv.v....", "...v..vv..v.....", "................",
            "................", "................", "................", "................",
        ],
        pal: &[('v', 0xb388ff), ('A', 0xbcbcbc), ('K', 0x000000)],
    },
    MobFrame {
        grid: &[
            "................", "................", "................",
            "................", "...v..v..v..v...", "...vvvvvvvv.....",
            "..vAAAAAAAAv....", "..vAKAAAAKAv....", "...vAAAAAAv.....",
            ".v.vvvvvv.v.....", "..v..vv..v......", "................",
            "................", "................", "................", "................",
        ],
        pal: &[('v', 0xb388ff), ('A', 0xbcbcbc), ('K', 0x000000)],
    },
];

/// Walking bomb (emberling): a small lump of smoldering coal (idle body; it swells + blows).
pub static EMBERLING_FRAMES: &[MobFrame] = &[MobFrame {
    grid: &[
        "................", "................", "................",
        "................", "................", ".....KKKK.......",
        "....KnrnrK......", "....KrnrnK......", "....KnrnrK......",
        ".....KKKK.......", "....K.KK.K......", "................",
        "................", "................", "................", "................",
    ],
    pal: &[('K', 0x000000), ('n', 0x585858), ('r', 0xd82800)],
}];

/// Every simple-frame kind -> its animation strip (wolf is per-facing, above).
pub static ALL_FRAMES: &[(&str, &[MobFrame])] = &[
    ("prismshard", PRISMSHARD_FRAMES),
    ("ashgeyser", ASHGEYSER_FRAMES),
    ("deepcrawler", DEEPCRAWLER_FRAMES),
    ("emberling", EMBERLING_FRAMES),
    ("boar", BOAR_FRAMES),
    ("wasp", WASP_FRAMES),
    ("thornling", THORNLING_FRAMES),
    ("bear", BEAR_FRAMES),
    ("spider", SPIDER_FRAMES),
    ("scorpion", SCORPION_FRAMES),
    ("burrower", BURROWER_FRAMES),
    ("vulture", VULTURE_FRAMES),
    ("golem", GOLEM_FRAMES),
    ("bat", BAT_FRAMES),
    ("hurler", HURLER_FRAMES),
    ("zombie", ZOMBIE_FRAMES),
    ("skeleton", SKELETON_FRAMES),
    ("archer", ARCHER_FRAMES),
    ("leech", LEECH_FRAMES),
    ("gnat", GNAT_FRAMES),
    ("lurker", LURKER_FRAMES),
    ("ghoul", GHOUL_FRAMES),
    ("wraith", WRAITH_FRAMES),
    ("revenant", REVENANT_FRAMES),
    ("frostmite", FROSTMITE_FRAMES),
    ("icetroll", ICETROLL_FRAMES),
    ("frostwyrm", FROSTWYRM_FRAMES),
    ("cinderhound", CINDERHOUND_FRAMES),
    ("charbrute", CHARBRUTE_FRAMES),
    ("pyrewraith", PYREWRAITH_FRAMES),
    ("sporeling", SPORELING_FRAMES),
    ("myconid", MYCONID_FRAMES),
    ("sporemother", SPOREMOTHER_FRAMES),
    ("chaoswisp", CHAOSWISP_FRAMES),
    ("voidling", VOIDLING_FRAMES),
    ("riftlord", RIFTLORD_FRAMES),
    ("cultist", CULTIST_FRAMES),
    ("mirefly", MIREFLY_FRAMES),
    ("boglight", BOGLIGHT_FRAMES),
    ("honeydrone", HONEYDRONE_FRAMES),
    ("gravewarden", GRAVEWARDEN_FRAMES),
    ("palehowler", PALEHOWLER_FRAMES),
    ("sandmaw", SANDMAW_FRAMES),
    ("stormcaller", STORMCALLER_FRAMES),
    ("switchshade", SWITCHSHADE_FRAMES),
    ("tidecrab", TIDECRAB_FRAMES),
    ("vinesnare", VINESNARE_FRAMES),
    ("bellsnail", BELLSNAIL_FRAMES),
    ("saltstatue", SALTSTATUE_FRAMES),
    ("glimmerling", GLIMMERLING_FRAMES),
    ("witherheart", WITHERHEART_FRAMES),
    ("slime", SLIME_FRAMES),
    ("frostslime", FROSTSLIME_FRAMES),
    ("emberslime", EMBERSLIME_FRAMES),
    ("sparkslime", SPARKSLIME_FRAMES),
    ("toxicslime", TOXICSLIME_FRAMES),
    ("frog", FROG_FRAMES),
];

/// (kind, bestiary name, bestiary desc) — js Enemies.BESTIARY, the ported subset.
pub static BESTIARY_INFO: &[(&str, &str, &str)] = &[
    ("boar", "TUSK BOAR", "Charges straight; stuns on walls."),
    ("wasp", "MEADOW WASP", "Fast, erratic; flies over water."),
    ("thornling", "THORNLING", "Hides as a bush, then ambushes."),
    ("bear", "FOREST BEAR", "Slow bruiser; shrugs off knockback."),
    ("spider", "SPITTING SPIDER", "Spits webbing that slows you."),
    ("scorpion", "DUSTBACK SCORPION", "Armored stalker; its sting leaves venom."),
    ("burrower", "SAND BURROWER", "Tunnels unseen, surfaces to strike."),
    ("vulture", "CARRION VULTURE", "Circles, then dives from above."),
    ("golem", "STONE GOLEM", "Immovable tank; crits stagger it."),
    ("bat", "CAVE BAT", "Erratic swarms of the dark."),
    ("prismshard", "PRISM SHARD", "Rooted crystal; fires a turning cross of light."),
    ("ashgeyser", "ASH GEYSER", "Rooted vent; lobs a spread of arcing rocks."),
    ("deepcrawler", "DEEP CRAWLER", "Blind; hunts by the sound of your footfalls."),
    ("emberling", "EMBERLING", "Walking bomb; swells, then detonates."),
    ("hurler", "CRAG HURLER", "Lobs rocks in an arc - dodge it."),
    ("zombie", "ZOMBIE", "Slow, relentless, hard to repel."),
    ("skeleton", "SKELETON", "Bones that chase and lunge."),
    ("archer", "SKELETON ARCHER", "Bones with a bow; kites you and looses arrows."),
    ("leech", "BOG LEECH", "Slow crawler; hard to knock back."),
    ("gnat", "GNAT SWARM", "Tiny clouds that drift over water."),
    ("lurker", "BOG LURKER", "Tanky stalker with a sudden lunge."),
    ("ghoul", "GHOUL", "Feral undead; creeps then lunges."),
    ("wraith", "WRAITH", "Drifts through walls; chills the soul."),
    ("revenant", "REVENANT", "Armored undead knight - slow, unyielding."),
    ("frostmite", "FROST MITE", "A flitting ice shard; its touch numbs."),
    ("icetroll", "ICE TROLL", "A frozen brute; chills and shrugs off blows."),
    ("frostwyrm", "FROST WYRM", "A serpent of ice; spits chilling bolts."),
    ("cinderhound", "CINDER HOUND", "A charred beast; lunges from the ash."),
    ("charbrute", "CHAR BRUTE", "Smouldering bulk; charges, hits like a log."),
    ("pyrewraith", "PYRE WRAITH", "A burning spectre; hurls embers from afar."),
    ("sporeling", "SPORELING", "A hopping toadstool; its touch is venomous."),
    ("myconid", "MYCONID", "A fungal brute; oozes poison spores."),
    ("sporemother", "SPORE MOTHER", "A bloated mushroom; spits a venom volley."),
    ("chaoswisp", "CHAOS WISP", "A darting mote of unmade reality."),
    ("voidling", "VOIDLING", "A void-thing; blinks to your blind side."),
    ("riftlord", "RIFT LORD", "A chaos warlord; flings bolts and endures."),
    ("cultist", "CULTIST", "A robed zealot; hurls dark bolts from afar."),
    ("mirefly", "MIREFLY", "A bog lantern that blooms into a ring of venom."),
    ("boglight", "BOGLIGHT", "Only half in this world at a time; strike the bright half."),
    ("honeydrone", "HONEY DRONE", "Circles patiently; darts the moment you look away."),
    ("gravewarden", "GRAVE WARDEN", "A sexton of the dead; the ground answers its call."),
    ("palehowler", "PALE HOWLER", "Its howl rolls out in a ring of freezing dread."),
    ("sandmaw", "SANDMAW", "The dune that drinks; the sand slides you to its teeth."),
    ("stormcaller", "STORMCALLER", "Marks the ground beneath you; the sky does the rest."),
    ("switchshade", "SWITCHSHADE", "It does not come to you. It puts you where it was."),
    ("tidecrab", "TIDE CRAB", "Scuttles around you, never at you; the pincer grips."),
    ("vinesnare", "VINE SNARE", "A patient loop of jungle; step close and it has you."),
    ("bellsnail", "BELL SNAIL", "Sealed tight in its bell; it only bleeds while it walks."),
    ("saltstatue", "SALT SENTINEL", "It only walks unwatched. Do not look away."),
    ("glimmerling", "GLIMMERLING", "A skittish coin-spirit; its light lances down a line — sidestep the shimmer."),
    ("witherheart", "WITHERHEART", "A rotted heart that mends itself; its hunger hunts you."),
    ("slime", "SLIME", "Hops along; splits when slain."),
    ("frostslime", "RIME SLIME", "A slime of living ice; its touch chills you stiff. Splits when slain."),
    ("emberslime", "EMBER SLIME", "Molten ooze; touching it sets you ablaze. Splits when slain."),
    ("sparkslime", "SPARK SLIME", "A crackling charge given form; its jolt locks you up. Splits when slain."),
    ("toxicslime", "ACID SLIME", "A caustic bog-ooze; its venom clings. Splits when slain."),
    ("frog", "BOG FROG", "Leaps in arcs; snaps when close."),
    ("wolf", "DIRE WOLF", "Packs that circle and lunge."),
];
