// extract_entrance.mjs — the shard-dungeon monument art (js/entities.js entranceBmp):
// ten archetype builders x per-land palettes, eyes stamped, outline pass applied, glow
// in the land's SHARD colour (js/relics.js). Emits src/actors/entrance_art.rs.
//
// Regenerate: node tools/extract_entrance.mjs
import { readFileSync, writeFileSync } from 'fs';

const JS = '/Users/brettbazaar/Code/Game Dev/Wriftheart/js';
const RS = '/Users/brettbazaar/Code/Game Dev/wriftheart-rs';
const ent = readFileSync(`${JS}/entities.js`, 'utf8');

// Shard colours straight off the relics table (Relics.byBiome(b).col).
const SHARD_COL = {};
for (const m of readFileSync(`${JS}/relics.js`, 'utf8').matchAll(/R\('(\w+)',\s*'[^']*',\s*'(#[0-9a-fA-F]{6})'/g)) SHARD_COL[m[1]] = m[2];
const DEFAULT_GLOW = '#c8a0ff';

// Slice-eval the builder region (mPx .. ENTRANCE_STYLES) + the blank/outlined helpers.
const helpers = ent.match(/const blank = [^\n]*\n/)[0] + ent.match(/function outlined\(g\) \{[\s\S]*?\n  \}/)[0];
const a = ent.indexOf('const mPx =');
const b = ent.indexOf('const entranceStyle =');
const builders = ent.slice(a, b);
const STYLES = new Function(`${helpers}\n${builders}\nreturn ENTRANCE_STYLES;`)();

// Shard-eligible biomes beyond the styles table fall back to the colossus (mountains)
// build with their OWN shard glow — mirror the js entranceStyle default.
const EXTRA = Object.keys(SHARD_COL).filter((k) => !STYLES[k]);

const hex = (s) => `0x${s.slice(1)}`;
const rows = [];
for (const biome of [...Object.keys(STYLES), ...EXTRA]) {
  const st = STYLES[biome] || STYLES.mountains;
  const g = st.build();
  for (const [ex, ey] of st.eyes) for (const [dx, dy] of [[0, 0], [1, 0], [0, 1], [1, 1]]) {
    if (g[ey + dy] && g[ey + dy][ex + dx] !== undefined) g[ey + dy][ex + dx] = 'W';
  }
  // outlined() returns joined strings.
  const helpersEval = new Function(`${helpers}\nreturn outlined;`)();
  const grid = helpersEval(g);
  const glow = SHARD_COL[biome] || DEFAULT_GLOW;
  const pal = Object.assign({ W: glow }, st.pal);
  const palRs = Object.entries(pal).map(([ch, col]) => `('${ch}', ${hex(col)})`).join(', ');
  const eyesRs = st.eyes.map(([x, y]) => `(${x}, ${y})`).join(', ');
  rows.push(`    EntranceArt {
        biome: "${biome}",
        grid: &[${grid.map((r) => JSON.stringify(r)).join(', ')}],
        pal: &[${palRs}],
        eyes: &[${eyesRs}],
        glow: ${hex(glow)},
    },`);
}

const out = `// GENERATED by tools/extract_entrance.mjs from js/entities.js + js/relics.js — do not edit.
//! entrance_art.rs — the shard-dungeon monument bitmaps (64x56), one per land: the
//! archetype silhouette in the land's palette, mouth + outline baked, eye pixels ('W')
//! and glow in the land's SHARD colour. The live breathing pulse draws over \`eyes\`.

pub struct EntranceArt {
    pub biome: &'static str,
    pub grid: &'static [&'static str],
    pub pal: &'static [(char, u32)],
    pub eyes: &'static [(i32, i32)],
    pub glow: u32,
}

pub static ENTRANCES: &[EntranceArt] = &[
${rows.join('\n')}
];

/// The land's monument (unknown biomes wear the mountains colossus, like the js).
pub fn entrance(biome: &str) -> &'static EntranceArt {
    ENTRANCES.iter().find(|e| e.biome == biome).unwrap_or_else(|| {
        ENTRANCES.iter().find(|e| e.biome == "mountains").unwrap()
    })
}
`;
writeFileSync(`${RS}/src/actors/entrance_art.rs`, out);
console.log(`wrote ${rows.length} entrance bitmaps`);
