// extract_recipes.mjs — the crafting RECIPES table from the live JS. Output:
//   src/recipes_data.rs — GENERATED: every { out, cost, station, bp, outN } recipe as a
//     Recipe literal. items::recipes_for filters to registered outputs + learned blueprints,
//     so unported outputs simply don't show yet (the same fill-in-as-it-ports rule as loot).
// craftGen rolled-item PREVIEWS (craftw*/crafta*) are DEFINE'd items, not recipes — handled
// separately (the forge's "commission a rolled item" flow).
import { readFileSync, writeFileSync } from 'fs';

const JS = '/Users/brettbazaar/Code/Game Dev/Wriftheart';
const RS = '/Users/brettbazaar/Code/Game Dev/wriftheart-rs';
let src = readFileSync(`${JS}/js/items.js`, 'utf8');

globalThis.Assets = { PALETTE: {}, bake: (g, p) => ({ grid: g, pal: p || null }), flipH: (g) => g };
globalThis.window = globalThis;
globalThis.Sound = { sfx: () => {} };
globalThis.Input = { held: () => false, pressed: () => false };
// Expose the module-private RECIPES on the return (like extract_stock's STOCK trick).
src = src.replace('return { define,', 'return { __RECIPES: RECIPES, define,');
if (!src.includes('__RECIPES')) throw new Error('items.js return-shape changed — update the patch');
eval(src + '\nglobalThis.__I = Items;');
const RECIPES = globalThis.__I.__RECIPES;

const costRs = (cost) => cost.map(([id, q]) => `("${id}", ${q})`).join(', ');
let out = `//! recipes_data.rs — GENERATED by tools/extract_recipes.mjs from js/items.js. Every
//! crafting recipe (out, cost, station, blueprint gate, output count). items::recipes_for
//! filters to REGISTERED outputs + LEARNED blueprints. Do not hand-edit; re-run the extractor.
#![allow(clippy::all)]

use crate::items::Recipe;

pub static RECIPES: &[Recipe] = &[
`;
let n = 0;
for (const r of RECIPES) {
  if (!r.out || !r.cost) continue; // craftGen previews have no cost — skip here
  const station = r.station || 'hand';
  const bp = r.bp ? `Some("${r.bp}")` : 'None';
  const nn = r.outN || 1;
  out += `    Recipe { out: "${r.out}", n: ${nn}, cost: &[${costRs(r.cost)}], station: "${station}", bp: ${bp} },\n`;
  n++;
}
out += `];\n`;
writeFileSync(`${RS}/src/recipes_data.rs`, out);
console.log(`recipes_data.rs: ${n} recipes`);
