// extract_interiors.mjs — building-interior extraction from the live JS. Output:
//   src/actors/interiors_art.rs — GENERATED: per building kind, the painted scene as a
//   fillRect DISPLAY LIST (a recording canvas shim captures every rect Interiors.make
//   paints, translate-adjusted) + the solid grid, exit, spawn, interactables, lights and
//   people. Rust replays the rects into one Image per kind and spawns the people live.
//
// The furniture rng is seeded per BUILDING in the js; we extract with iseed=1 per kind
// (DEVIATION: all instances of a kind share furniture pixels — the folk still vary).
import { readFileSync, writeFileSync } from 'fs';

const JS = '/Users/brettbazaar/Code/Game Dev/Wriftheart/js';
const RS = '/Users/brettbazaar/Code/Game Dev/wriftheart-rs';
const src = (f) => readFileSync(`${JS}/${f}`, 'utf8');

// --- A recording 2d context: fillRect ops land in `ops` with the live translate. ---
let ops = [];
function recordingCtx() {
  const st = { tx: 0, ty: 0, stack: [], fillStyle: '#000' };
  return {
    get canvas() { return { width: 304, height: 208 }; },
    set fillStyle(v) { st.fillStyle = v; },
    get fillStyle() { return st.fillStyle; },
    fillRect(x, y, w, h) { ops.push([x + st.tx, y + st.ty, w, h, st.fillStyle]); },
    save() { st.stack.push([st.tx, st.ty]); },
    restore() { const p = st.stack.pop(); if (p) { st.tx = p[0]; st.ty = p[1]; } },
    translate(x, y) { st.tx += x; st.ty += y; },
    drawImage() {}, // keeper sprites respawn as live villagers in Rust
    beginPath() {}, ellipse() {}, arc() {}, fill() {}, stroke() {}, clip() {}, rect() {},
    strokeRect() {}, moveTo() {}, lineTo() {}, closePath() {},
    set strokeStyle(_) {}, set globalAlpha(_) {}, set lineWidth(_) {},
  };
}
const fakeCanvas = () => {
  const c = recordingCtx();
  return { width: 304, height: 208, getContext: () => c };
};
globalThis.document = { createElement: fakeCanvas };

const palMatch = src('assets.js').match(/const PALETTE = \{[\s\S]*?\n  \};/);
const PALETTE = eval(`(() => { ${palMatch[0].replace('const PALETTE =', 'return')} })()`);
globalThis.Assets = { PALETTE, bake: (g, p) => ({ grid: g, pal: p }), flipH: (g) => g };
globalThis.clamp = (v, a, b) => Math.max(a, Math.min(b, v));
globalThis.window = globalThis;
globalThis.Sound = { sfx: () => {} };
globalThis.Player = {
  buildFrames: () => ({ down: [{}], up: [{}], left: [{}], right: [{}] }),
  randomLook: () => ({}),
  DEFAULT_LOOK: {},
};
globalThis.Items = undefined;

// tiles/room give Room.COLS etc; buildings is the registry interiors reads.
eval(src('buildings.js') + src('tiles.js') + src('room.js') + src('interiors.js') + '\nglobalThis.__I = Interiors; globalThis.__B = Buildings;');
const Interiors = globalThis.__I;
const Buildings = globalThis.__B;

// Colors: '#rgb'/'#rrggbb'/'rgba(r,g,b,a)' -> 0xRRGGBBAA.
function rgba(col) {
  if (col.startsWith('#')) {
    let h = col.slice(1);
    if (h.length === 3) h = h.split('').map((c) => c + c).join('');
    return (parseInt(h, 16) * 256 + 255) >>> 0;
  }
  const m = col.match(/rgba?\(([\d.]+)[, ]+([\d.]+)[, ]+([\d.]+)(?:[, ]+([\d.]+))?\)/);
  if (!m) throw new Error('color? ' + col);
  const a = m[4] == null ? 255 : Math.round(parseFloat(m[4]) * 255);
  return (((+m[1] << 24) | (+m[2] << 16) | (+m[3] << 8) | a) >>> 0);
}

const KINDS = ['house', 'shop', 'caveshop', ...Object.keys(Buildings.DEFS)];
const T = 16, COLS = 19, ROWS = 13;
let out = `//! interiors_art.rs — GENERATED by tools/extract_interiors.mjs from js/interiors.js.
//! Each kind: the painted scene as (x, y, w, h, 0xRRGGBBAA) fill rects, the solid grid
//! ('#' rows), exit/spawn, interactables, lights, and the folk to spawn live.
//! Do not hand-edit; re-run the extractor instead.
#![allow(clippy::all)]

pub struct InteriorDef {
    pub kind: &'static str,
    pub title: &'static str,
    pub stock: &'static str, // vendor stock kind ("" = not a vendor)
    pub rects: &'static [(i16, i16, i16, i16, u32)],
    pub solid: &'static [&'static str], // ROWS strings of COLS chars, '#' = solid
    pub exit: (i32, i32, i32, i32),
    pub spawn: (i32, i32),
    /// (kind, label, x, y, w, h) — stand in one + press interact.
    pub interact: &'static [(&'static str, &'static str, i32, i32, i32, i32)],
    /// (x, y, still, line) — the keeper (first, still) + patrons, spawned as villagers.
    pub people: &'static [(i32, i32, bool, &'static str)],
    /// (x, y, r, glow_r, gi) — warm light sources for the lighting pass.
    pub lights: &'static [(i32, i32, i32, i32, f32)],
    /// (x, y) — where a stray lore tome could plausibly sit (rolled per building).
    pub book_spots: &'static [(i32, i32)],
}

pub const INTERIORS: &[InteriorDef] = &[
`;
const esc = (s) => String(s || '').replace(/\\/g, '\\\\').replace(/"/g, '\\"');
for (const kind of KINDS) {
  ops = [];
  const it = Interiors.make(kind, 1);
  // Solid grid probed at tile centres (the bottom-walk nuance is re-applied in Rust).
  const rows = [];
  for (let r = 0; r < ROWS; r++) {
    let row = '';
    for (let c = 0; c < COLS; c++) row += it.solidAt(c * T + 8, r * T + 8) ? '#' : '.';
    rows.push(row);
  }
  const rects = ops
    .filter(([x, y, w, h]) => w > 0 && h > 0)
    .map(([x, y, w, h, col]) => `(${Math.round(x)}, ${Math.round(y)}, ${Math.round(w)}, ${Math.round(h)}, 0x${rgba(col).toString(16).padStart(8, '0')})`)
    .join(', ');
  const inter = (it.interactables || [])
    .map((i) => `("${esc(i.kind)}", "${esc(i.label)}", ${i.x}, ${i.y}, ${i.w}, ${i.h})`)
    .join(', ');
  const people = (it.people || [])
    .map((p) => `(${Math.round(p.x)}, ${Math.round(p.y)}, ${!!p.still}, "${esc(p.line)}")`)
    .join(', ');
  const lights = (it.lights || [])
    .map((l) => `(${Math.round(l.x)}, ${Math.round(l.y)}, ${Math.round(l.r)}, ${Math.round(l.glowR || 0)}, ${(l.gi || 0).toFixed(3)})`)
    .join(', ');
  const bookSpots = (it.bookSpots || []).map((sp) => `(${Math.round(sp.x)}, ${Math.round(sp.y)})`).join(', ');
  out += `    InteriorDef {
        kind: "${kind}",
        title: "${esc(it.title)}",
        stock: "${esc(it.stockKind)}",
        rects: &[${rects}],
        solid: &[${rows.map((r) => `"${r}"`).join(', ')}],
        exit: (${it.exit.x}, ${it.exit.y}, ${it.exit.w}, ${it.exit.h}),
        spawn: (${it.spawn.x}, ${it.spawn.y}),
        interact: &[${inter}],
        people: &[${people}],
        lights: &[${lights}],
        book_spots: &[${bookSpots}],
    },\n`;
  console.log(kind, ops.length, 'rects,', (it.people || []).length, 'people,', (it.interactables || []).length, 'interactables');
}
out += `];\n`;
writeFileSync(`${RS}/src/actors/interiors_art.rs`, out);
console.log('kinds:', KINDS.length);
