// extract_relics.mjs — the shard table (js/relics.js LIST + strings) -> src/relics_data.rs.
// Regenerate: node tools/extract_relics.mjs
import { readFileSync, writeFileSync } from 'fs';
globalThis.Assets = { bake: () => null };
eval(readFileSync('/Users/brettbazaar/Code/Game Dev/Wriftheart/js/relics.js', 'utf8') + '; globalThis.Relics = Relics;');
const esc = (s) => JSON.stringify(s);
const rows = Relics.LIST.map((r) => `    Relic { biome: ${esc(r.biome)}, name: ${esc(r.name)}, col: 0x${r.col.slice(1)}, lore: ${esc(r.lore)} },`);
writeFileSync('/Users/brettbazaar/Code/Game Dev/wriftheart-rs/src/relics_data.rs', `// GENERATED by tools/extract_relics.mjs from js/relics.js — do not edit.
//! relics_data.rs — the shards of the Wriftheart: every land's relic (name, colour,
//! lore). Each WORLD holds only ten of them true (World::shard_biomes).

pub struct Relic {
    pub biome: &'static str,
    pub name: &'static str,
    pub col: u32,
    pub lore: &'static str,
}

pub static LIST: &[Relic] = &[
${rows.join('\n')}
];

pub fn by_biome(b: &str) -> Option<&'static Relic> {
    LIST.iter().find(|r| r.biome == b)
}

pub static INTRO: &str = ${esc(Relics.INTRO)};
pub static FINALE: &str = ${esc(Relics.FINALE)};
pub static STORY: &[&str] = &[
${Relics.STORY.map((s) => `    ${esc(s)},`).join('\n')}
];
`);
console.log(`wrote ${Relics.LIST.length} relics`);
