// extract_towns.mjs — town art + layout extraction from the live JS. Outputs:
//   1. src/actors/buildings_art.rs      — GENERATED: every TOWN_FRONTS storefront grid +
//                                         palette, plus WELL_BMP + TORCH_FRAMES.
//   2. tests/data/town_entities_golden.rs — World.getEntities descriptor lists for real
//                                         town rooms across seeds (pins the townEntities
//                                         port bit-exact, npc seeds/lines included).
//
// Pattern (see extract_props.mjs): eval the verbatim sources with Assets.bake stubbed to
// an identity capture; buildings.js is evaluated REAL (town fronts key off its registry).
import { readFileSync, writeFileSync } from 'fs';

const JS = '/Users/brettbazaar/Code/Game Dev/Wriftheart/js';
const RS = '/Users/brettbazaar/Code/Game Dev/wriftheart-rs';
const src = (f) => readFileSync(`${JS}/${f}`, 'utf8');

// --- Stubs ---
const palMatch = src('assets.js').match(/const PALETTE = \{[\s\S]*?\n  \};/);
const PALETTE = eval(`(() => { ${palMatch[0].replace('const PALETTE =', 'return')} })()`);
globalThis.Assets = {
  PALETTE,
  bake: (grid, pal) => ({ grid: grid.map((r) => (Array.isArray(r) ? r.join('') : r)), pal: pal || null }),
  flipH: (g) => (g.grid ? { grid: g.grid.map((r) => r.split('').reverse().join('')), pal: g.pal } : g.map((r) => r.split('').reverse().join(''))),
};
globalThis.clamp = (v, a, b) => Math.max(a, Math.min(b, v));
globalThis.window = globalThis;
globalThis.Items = undefined;
globalThis.Sound = { sfx: () => {} };
globalThis.Player = { buildFrames: () => ({ down: [{}], up: [{}], left: [{}], right: [{}] }), DEFAULT_LOOK: {}, randomLook: () => ({}) };
const noopCtx = new Proxy({}, { get: (t, k) => (k === 'canvas' ? fakeCanvas() : () => noopCtx), set: () => true });
const fakeCanvas = () => ({ width: 0, height: 0, getContext: () => noopCtx });
globalThis.document = { createElement: fakeCanvas };

// entities.js: inject the town internals into scope.
let entSrc = src('entities.js');
let retAt = entSrc.lastIndexOf('\n  return {');
entSrc = entSrc.slice(0, retAt) + '\n  globalThis.__TOWN = { TOWN_FRONTS, WELL_BMP, TORCH_FRAMES, ruinGrid, SKELETON_DOWN };' + entSrc.slice(retAt);

// buildings.js is REAL (the fronts read its registry); world.js runs verbatim.
eval(src('buildings.js') + src('tiles.js') + src('room.js') + entSrc + src('world.js') + '\nglobalThis.__M = { World };');
const { World } = globalThis.__M;
const T = globalThis.__TOWN;

const esc = (s) => s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
const gridRs = (g) => g.map((r) => `        "${esc(r)}",`).join('\n');
const palRs = (pal) =>
  pal
    ? Object.entries(pal)
        .map(([ch, col]) => `('${ch}', 0x${col.replace('#', '')})`)
        .join(', ')
    : '';

// --- 1. buildings_art.rs ---
let art = `//! buildings_art.rs — GENERATED by tools/extract_towns.mjs from js/entities.js
//! (the town-front architecture kit's finished 48x48 grids + palettes, plus the well
//! and the two torch frames). Do not hand-edit; re-run the extractor instead.
#![allow(clippy::all)]

/// (kind, grid rows, palette overrides) — one storefront per building kind.
pub const TOWN_FRONTS: &[(&str, &[&str], &[(char, u32)])] = &[
`;
for (const [kind, bmp] of Object.entries(T.TOWN_FRONTS)) {
  art += `    ("${kind}", &[\n${gridRs(bmp.grid)}\n    ], &[${palRs(bmp.pal)}]),\n`;
}
art += `];

pub const WELL: (&[&str], &[(char, u32)]) = (&[
${gridRs(T.WELL_BMP.grid)}
], &[${palRs(T.WELL_BMP.pal)}]);

pub const TORCH_FRAMES: [(&[&str], &[(char, u32)]); 2] = [
    (&[
${gridRs(T.TORCH_FRAMES[0].grid)}
    ], &[${palRs(T.TORCH_FRAMES[0].pal)}]),
    (&[
${gridRs(T.TORCH_FRAMES[1].grid)}
    ], &[${palRs(T.TORCH_FRAMES[1].pal)}]),
];
`;
// The burnt home village's five ruin shells (game.js buildRuinedVillage's fixed spots) —
// each grid is seeded from its own coords (js: imul hash of x,y), so extract per spot.
art += `
/// (x, y, grid) — the home village's gutted shells at their js coordinates (kind is
/// flavor-only in the js; the art keys off position).
pub const RUINS: &[(i32, i32, &[&str])] = &[
`;
for (const [kind, x, y] of [['inn', 52, 56], ['blacksmith', 252, 56], ['tavern', 60, 156], ['bakery', 244, 156], ['cottage', 150, 170]]) {
  const seed = ((Math.imul(x, 73856093)) ^ (Math.imul(y, 19349663))) >>> 0;
  const g = T.ruinGrid(seed).map((r) => (Array.isArray(r) ? r.join('') : r));
  art += `    (${x}, ${y}, &[\n${gridRs(g)}\n    ]),\n`;
}
art += `];

pub const SKELETON: (&[&str], &[(char, u32)]) = (&[
${gridRs(T.SKELETON_DOWN.grid)}
], &[${palRs(T.SKELETON_DOWN.pal)}]);
`;
writeFileSync(`${RS}/src/actors/buildings_art.rs`, art);
console.log('fronts:', Object.keys(T.TOWN_FRONTS).length, 'well:', T.WELL_BMP.grid.length + 'rows', 'torch frames:', T.TORCH_FRAMES.length);

// --- 2. town golden vectors: the first town rooms spiralling out from the origin. ---
let golden = `// GENERATED by tools/extract_towns.mjs — town-room entity descriptors from the live JS
// (seed, rx, ry, [(kind, sub, x, y, seed, line)]). Do not hand-edit.

pub type TownEnt = (&'static str, &'static str, i32, i32, u32, &'static str);
pub const TOWN_GOLDEN: &[(u32, i32, i32, &[TownEnt])] = &[
`;
let total = 0;
for (const seed of [1337, 42, 90210]) {
  World.setSeed(seed);
  let found = 0;
  for (let rad = 0; rad <= 12 && found < 4; rad++) {
    for (let ry = -rad; ry <= rad && found < 4; ry++) {
      for (let rx = -rad; rx <= rad && found < 4; rx++) {
        if (Math.max(Math.abs(rx), Math.abs(ry)) !== rad) continue;
        if (!World.isTown(rx, ry)) continue;
        const ents = World.getEntities(rx, ry);
        golden += `    (${seed}, ${rx}, ${ry}, &[\n`;
        for (const e of ents) {
          golden += `        ("${e.type}", "${esc(e.kind || '')}", ${e.x}, ${e.y}, ${(e.seed || 0) >>> 0}, "${esc(e.line || '')}"),\n`;
        }
        golden += `    ]),\n`;
        found++;
        total += ents.length;
      }
    }
  }
  console.log(`seed ${seed}: ${found} town rooms`);
}
golden += `];\n`;
writeFileSync(`${RS}/tests/data/town_entities_golden.rs`, golden);
console.log('golden entities total:', total);
