// extract_props.mjs — prop-layer extraction from the live JS. Three outputs:
//   1. src/actors/props_art.rs      — GENERATED art data: bush/boulder/grass/flower/clutter
//                                     grids + palettes + the PROPS anchor table.
//   2. tests/data/treeart_golden.rs — sampled-seed grids from buildOak/buildPine/buildCactus/
//                                     buildDeadtree (the generators are PORTED, not data).
//   3. tests/data/entities_golden.rs— World.getEntities descriptor lists per room (the
//                                     layout keystone: every stream's positions, bit-exact).
//
// Pattern: eval the verbatim sources with Assets.bake stubbed to identity ({grid, pal}),
// and inject module internals into the entities.js IIFE return.
import { readFileSync, writeFileSync } from 'fs';

const JS = '/Users/brettbazaar/Code/Game Dev/Wriftheart/js';
const RS = '/Users/brettbazaar/Code/Game Dev/wriftheart-rs';
const src = (f) => readFileSync(`${JS}/${f}`, 'utf8');

// --- Stubs ---
const palMatch = src('assets.js').match(/const PALETTE = \{[\s\S]*?\n  \};/);
const PALETTE = eval(`(() => { ${palMatch[0].replace('const PALETTE =', 'return')} })()`);
globalThis.Assets = {
  PALETTE,
  bake: (grid, pal) => ({ grid, pal }), // identity capture
  flipH: (g) => g.map((r) => r.split('').reverse().join('')),
};
globalThis.Buildings = { roster: () => [], plan: () => null };
globalThis.clamp = (v, a, b) => Math.max(a, Math.min(b, v));
globalThis.window = globalThis;
globalThis.Items = undefined;
globalThis.Sound = { sfx: () => {} };
// Canvas stub: entities.js paints a few composite sprites (castle, house) at load — we
// don't extract those here, so a do-nothing 2d context suffices.
const noopCtx = new Proxy({}, { get: (t, k) => (k === 'canvas' ? fakeCanvas() : () => noopCtx) , set: () => true });
const fakeCanvas = () => ({ width: 0, height: 0, getContext: () => noopCtx });
globalThis.document = { createElement: fakeCanvas };

// entities.js: inject internals into the IIFE return (the machine-extraction trick).
let entSrc = src('entities.js');
const retAt = entSrc.lastIndexOf('\n  return {');
entSrc =
  entSrc.slice(0, retAt) +
  '\n  globalThis.__ENT = { BUSH_VARIANTS, ORE_BMPS, GRASS_FRAMES: GRASS_FRAMES, FLOWERS, CLUTTER, PROPS, buildOak, buildPine, buildCactus, buildDeadtree };' +
  entSrc.slice(retAt);

// tiles.js + room.js + world.js + entities.js in one scope.
eval(
  src('tiles.js') + src('room.js') + src('world.js') + entSrc +
  '\nglobalThis.__M = { World };',
);
const { World } = globalThis.__M;
const E = globalThis.__ENT;

const gridLit = (g) => '&[' + g.map((r) => JSON.stringify(r)).join(', ') + ']';
const hexOf = (s) => '0x' + s.slice(1);

// ---------- 1. props_art.rs ----------
let art = '// GENERATED by tools/extract_props.mjs — do not edit.\n';
art += '//! props_art.rs — prop art data machine-extracted from js/entities.js (bush variants,\n';
art += '//! boulder ore nodes, grass sway frames + biome tints, flowers, ground clutter, and\n';
art += '//! the prop anchor table). The seeded TREE generators live in props.rs, not here.\n\n';

art += 'pub const BUSH_VARIANTS: &[&[&str]] = &[\n';
for (const b of E.BUSH_VARIANTS) art += `    ${gridLit(b.grid)},\n`;
art += '];\n\n';

// Boulder ore nodes: tier -> 15 grids; the vein chars v/V colour per tier.
art += '/// Ore-node boulders: [tier 1..=5][15 variants], with per-tier vein colours (v, V).\n';
art += 'pub const ORE_NODES: &[(u32, u32, &[&[&str]])] = &[\n';
for (let t = 1; t <= 5; t++) {
  const set = E.ORE_BMPS[t];
  const { v, V } = set[0].pal;
  art += `    (${hexOf(v)}, ${hexOf(V)}, &[\n`;
  for (const b of set) art += `        ${gridLit(b.grid)},\n`;
  art += '    ]),\n';
}
art += '];\n\n';

art += 'pub const GRASS_FRAMES: &[&[&str]] = &[\n';
for (const f of E.GRASS_FRAMES) art += `    ${gridLit(f.grid)},\n`;
art += '];\n\n';

// Grass tints (tint key -> l/g overrides), from the source table.
const tintsMatch = src('entities.js').match(/const GRASS_TINTS = \{[\s\S]*?\n  \};/);
const GRASS_TINTS = eval(`(() => { ${tintsMatch[0].replace('const GRASS_TINTS =', 'return')} })()`);
art += 'pub const GRASS_TINTS: &[(&str, u32, u32)] = &[\n';
for (const [k, o] of Object.entries(GRASS_TINTS)) art += `    ("${k}", ${hexOf(o.l)}, ${hexOf(o.g)}),\n`;
art += '];\n\n';

art += `pub const FLOWER_BASE: &[&str] = ${gridLit(E.FLOWERS[0].grid)};\n`;
art += 'pub const FLOWER_COLS: &[u32] = &[' + E.FLOWERS.map((f) => hexOf(f.pal.p)).join(', ') + '];\n\n';

// Wilderness clutter kinds (the biome CLUTTER tables draw from these).
const CLUTTER_KINDS = ['pebble', 'shrub', 'fern', 'vine', 'crystalshard', 'toadstool', 'twig',
  'deadbush', 'bones', 'scree', 'gravestone', 'pillar', 'ashpile', 'charcoal', 'embers',
  'charredlog', 'lavarock', 'sulfur', 'emberpile', 'obsidianshard', 'bloom'];
art += 'pub const CLUTTER_ART: &[(&str, &[&str])] = &[\n';
for (const k of CLUTTER_KINDS) art += `    ("${k}", ${gridLit(E.CLUTTER[k].grid)}),\n`;
art += '];\n\n';

art += '/// Prop draw anchors + hitboxes (offX, offY, hb_ox, hb_oy, hb_w, hb_h) — js PROPS.\n';
art += 'pub const PROP_ANCHORS: &[(&str, i32, i32, i32, i32, i32, i32)] = &[\n';
for (const [k, p] of Object.entries(E.PROPS)) {
  art += `    ("${k}", ${p.offX}, ${p.offY}, ${p.hb.ox}, ${p.hb.oy}, ${p.hb.w}, ${p.hb.h}),\n`;
}
art += '];\n';
writeFileSync(`${RS}/src/actors/props_art.rs`, art);

// ---------- 2. treeart_golden.rs ----------
const SEEDS = [0, 1, 2, 3, 5, 7, 42, 100, 511, 999, 1337, 2048, 3000, 4095];
let tg = '// GENERATED by tools/extract_props.mjs — do not edit.\n';
tg += '#[allow(clippy::type_complexity)]\n';
tg += 'pub const TREES: &[(&str, u32, &[&str])] = &[\n';
for (const s of SEEDS) {
  tg += `    ("oak", ${s}, ${gridLit(E.buildOak(19 + (s % 3), s))}),\n`;
  tg += `    ("pine", ${s}, ${gridLit(E.buildPine(14 + (s % 5), 54 + (s % 6), s))}),\n`;
  tg += `    ("cactus", ${s}, ${gridLit(E.buildCactus((s >> 5) & 1, 4 + (s % 23)))}),\n`;
  tg += `    ("deadtree", ${s}, ${gridLit(E.buildDeadtree(s))}),\n`;
}
tg += '];\n';
writeFileSync(`${RS}/tests/data/treeart_golden.rs`, tg);

// ---------- 3. entities_golden.rs ----------
const SEED = 1337;
World.setSeed(SEED);
const rooms = [];
for (let ry = -2; ry <= 2; ry++) for (let rx = -2; rx <= 2; rx++) rooms.push([rx, ry]);
rooms.push([-7, -5], [11, 8], [5, 5], [-4, 6]); // far-field variety (deeper tiers, other biomes)
let eg = '// GENERATED by tools/extract_props.mjs — do not edit.\n';
eg += '// (seed, rx, ry, &[(type, sub, x, y, champ, elite)]) — town rooms are skipped (TODO towns).\n';
eg += '#[allow(clippy::type_complexity)]\n';
eg += 'pub const ENTITIES: &[(u32, i32, i32, &[(&str, &str, i32, i32, bool, bool)])] = &[\n';
let total = 0;
for (const [rx, ry] of rooms) {
  if (World.isTown(rx, ry)) continue; // townEntities is its own later port
  const list = World.getEntities(rx, ry).map((e) =>
    `("${e.type}", "${e.kind || e.dest || ''}", ${e.x}, ${e.y}, ${!!e.champ}, ${!!e.elite})`,
  );
  total += list.length;
  eg += `    (${SEED}, ${rx}, ${ry}, &[${list.join(',')}]),\n`;
}
eg += '];\n';
writeFileSync(`${RS}/tests/data/entities_golden.rs`, eg);
console.log(`props_art + ${SEEDS.length * 4} tree grids + entities for ${rooms.length} rooms (${total} entities)`);
