// extract_lore.mjs — the collectible-tome registry from the live JS. Output:
//   src/lore_books.rs — GENERATED: every book (id/title/cat/by/where/spine colour/text)
//   in js LIST order, plus the category colours and the spine-icon grid.
import { readFileSync, writeFileSync } from 'fs';

const JS = '/Users/brettbazaar/Code/Game Dev/Wriftheart/js';
const RS = '/Users/brettbazaar/Code/Game Dev/wriftheart-rs';
const src = (f) => readFileSync(`${JS}/${f}`, 'utf8');

globalThis.Assets = { PALETTE: {}, bake: (g, p) => ({ grid: g, pal: p }) };
globalThis.window = globalThis;
eval(src('lore.js') + '\nglobalThis.__L = Lore;');
const Lore = globalThis.__L;

const esc = (s) => s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
const books = Lore.LIST;
let out = `//! lore_books.rs — GENERATED by tools/extract_lore.mjs from js/lore.js. Every
//! collectible tome, js LIST order (the shelf walks it). Do not hand-edit.
#![allow(clippy::all)]

pub struct Book {
    pub id: &'static str,
    pub title: &'static str,
    pub cat: &'static str,
    pub by: &'static str,
    pub where_: &'static str, // placement pool hint (town/home/tavern/chapel/camp/dungeon/castle/emberfall)
    pub col: u32,             // the category's spine colour
    pub text: &'static str,   // paragraphs split on blank lines; reader wraps + paginates
}

/// The spine-icon grid ('C' = the category colour, 'W' = page edges).
pub const BOOK_GRID: &[&str] = &[
`;
// BOOK_GRID from the source (identity-baked icon grids all share it).
const gridMatch = src('lore.js').match(/const BOOK_GRID = \[(.*?)\];/s);
for (const row of eval('[' + gridMatch[1] + ']')) out += `    "${row}",\n`;
out += `];

pub const BOOKS: &[Book] = &[
`;
for (const b of books) {
  out += `    Book { id: "${b.id}", title: "${esc(b.title)}", cat: "${esc(b.cat)}", by: "${esc(b.by)}", where_: "${b.where}", col: 0x${b.col.replace('#', '')}, text: "${esc(b.text).replace(/\n/g, '\\n')}" },\n`;
}
out += `];

pub fn get(id: &str) -> Option<&'static Book> {
    BOOKS.iter().find(|b| b.id == id)
}
`;
writeFileSync(`${RS}/src/lore_books.rs`, out);
console.log('books:', books.length, 'cats:', new Set(books.map((b) => b.cat)).size);
