// extract_dressing.mjs — golden extractor for room.js's edge-dressing passes (rounded
// terrain corners + scalloped hedges). Evals the VERBATIM live JS with an Assets stub and a
// fillRect-recording ctx; room.draw()'s only fillRect calls are the two dressing passes, so
// the recording IS the dressing. Emits tests/data/dressing_golden.rs.
import { readFileSync, writeFileSync } from 'fs';

const JS = '/Users/brettbazaar/Code/Game Dev/Wriftheart/js';
const src = (f) => readFileSync(`${JS}/${f}`, 'utf8');

// --- Assets stub: the real PALETTE (regexed out of assets.js), bake() -> dummy object ---
const assetsSrc = src('assets.js');
const palMatch = assetsSrc.match(/const PALETTE = \{[\s\S]*?\n  \};/);
if (!palMatch) throw new Error('PALETTE not found');
const PALETTE = eval(`(() => { ${palMatch[0].replace('const PALETTE =', 'return')} })()`);
globalThis.Assets = {
  PALETTE,
  bake: () => ({}),
  flipH: (g) => g.map((r) => r.split('').reverse().join('')),
};

// Generous stubs for modules world.js pokes at (same set the worldmap harness needed).
globalThis.Buildings = { roster: () => [], plan: () => null };
globalThis.clamp = (v, a, b) => Math.max(a, Math.min(b, v));
globalThis.Entities = { clock: () => 0, overlap: () => false };
globalThis.window = globalThis;

// One eval, dependency order (room.js only touches World at call time, so it can precede
// world.js, which reads Room.COLS at load). The tail exports the modules to globalThis.
eval(
  src('tiles.js') +
    src('room.js') +
    src('world.js') +
    '\nglobalThis.__M = { Tiles, Room, World };',
);
const { Room, World } = globalThis.__M;

const SEED = 1337;
World.setSeed(SEED);

const rooms = [];
for (let ry = -2; ry <= 2; ry++) for (let rx = -2; rx <= 2; rx++) rooms.push([rx, ry]);
rooms.push([-7, -5], [11, 8]); // far-field + negative world-pixel coords for the edge hash

let out = '// GENERATED by extract_dressing.mjs — do not edit.\n';
out += '// (seed, rx, ry, &[(x, y, w, h, rgb)]) recorded from room.js draw() fillRects.\n';
out += '#[allow(clippy::type_complexity)] // generated golden data, mirrors the JS record shape\n';
out += 'pub const DRESSING: &[(u32, i32, i32, &[(i32, i32, i32, i32, u32)])] = &[\n';
let total = 0;
for (const [rx, ry] of rooms) {
  const map = World.getMap(rx, ry);
  const room = Room.make(map, rx * Room.COLS, ry * Room.ROWS);
  const rec = [];
  const ctx = {
    fillStyle: '#000000',
    fillRect(x, y, w, h) { rec.push([x, y, w, h, this.fillStyle]); },
    drawImage() {},
  };
  room.draw(ctx, 0, 0);
  total += rec.length;
  const rects = rec
    .map(([x, y, w, h, c]) => `(${x},${y},${w},${h},0x${c.slice(1)})`)
    .join(',');
  out += `    (${SEED}, ${rx}, ${ry}, &[${rects}]),\n`;
}
out += '];\n';
writeFileSync('/Users/brettbazaar/Code/Game Dev/wriftheart-rs/tests/data/dressing_golden.rs', out);
console.log(`wrote ${rooms.length} rooms, ${total} rects`);
