// extract_gear.mjs — the wearable-gear catalog from the live JS (armor + stat-row
// trinkets + gear-flag trinkets). Output:
//   src/gear_data.rs — GENERATED: ItemDef literals for every js head/body/feet piece
//     and the trinkets the rs registry doesn't carry yet, icons + palettes + stats
//     verbatim. items.rs chains this table behind DEFS in get().
// Skipped on purpose: pieces already in src/items.rs (uniques batch 1, luckyhook,
// guildseal, pocketwatch), and bubblering (its auto-block wires into app/shield.rs
// with its own increment).
import { readFileSync, writeFileSync } from 'fs';

const JS = '/Users/brettbazaar/Code/Game Dev/Wriftheart/js';
const RS = '/Users/brettbazaar/Code/Game Dev/wriftheart-rs';
let src = readFileSync(`${JS}/items.js`, 'utf8');

globalThis.Assets = {
  PALETTE: {},
  bake: (g, p) => ({ grid: g, pal: p || null }),
  flipH: (g) => g,
};
globalThis.window = globalThis;
globalThis.Sound = { sfx: () => {} };
globalThis.Input = { held: () => false, pressed: () => false };
eval(src + '\nglobalThis.__I = Items;');
const Items = globalThis.__I;

// The rs registry already carries these — do not re-emit.
const HAVE = new Set([
  // items.rs today: tools/consumables/materials + the uniques batch + hall trinkets.
  'pocketwatch', 'luckyhook', 'guildseal',
  'bellclapper', 'boarheart', 'brambleband', 'emberfang', 'gravecoin', 'grudgepurse',
  'harvestknot', 'hollowbone', 'midastooth', 'owltalisman', 'riftsplinter', 'saintsglass',
  'saltcrown', 'soullocket', 'stillwaterpearl', 'wardensknuckle', 'wintershard', 'wispstone',
  'boomerang',
  // bubblering's auto-block wires into app/shield.rs with its own increment.
  'bubblering',
]);

const WANT_KINDS = new Set(['HEAD', 'BODY', 'FEET', 'TRINKET']);
const ids = Items.ids ? Items.ids() : null;
// items.js may not expose ids(); walk the known catalog via loot/registry probing.
const probe = [];
for (const re of [/define\('([a-z0-9]+)'/g, /\{ id: '([a-z0-9]+)'/g]) {
  let m;
  while ((m = re.exec(src))) probe.push(m[1]);
}
const seen = new Set();
const rows = [];
for (const id of probe) {
  if (seen.has(id) || HAVE.has(id)) continue;
  seen.add(id);
  const d = Items.get(id);
  if (!d || !WANT_KINDS.has(d.kind)) continue;
  if (!d.icon || !d.icon.grid) continue;
  rows.push({ id, d });
}

const esc = (s) => s.replace(/’/g, "'").replace(/"/g, '\\"').replace(/[^\x20-\x7e]/g, '');
const hex = (c) => `0x${c.replace('#', '')}`;
let out = `//! gear_data.rs — GENERATED by tools/extract_gear.mjs from js/items.js. The wearable
//! catalog: every js armor piece (head/body/feet) + the stat-row and gear-flag
//! trinkets, icons and stats verbatim. items::get chains this behind DEFS.
//! Do not hand-edit; re-run the extractor.
#![allow(clippy::all)]

use crate::items::{ItemDef, Rarity, BASE};

pub static GEAR_DEFS: &[ItemDef] = &[
`;
const RAR = { common: 'Common', uncommon: 'Uncommon', rare: 'Rare', epic: 'Epic', legendary: 'Legendary' };
for (const { id, d } of rows) {
  const icon = d.icon.grid.map((r) => `"${r}"`).join(', ');
  const pal = d.icon.pal
    ? Object.entries(d.icon.pal).map(([ch, c]) => `('${ch}', ${hex(c)})`).join(', ')
    : '';
  const stats = d.stats
    ? Object.entries(d.stats).map(([k, v]) => `("${k}", ${Number.isInteger(v) ? v + '.0' : v})`).join(', ')
    : '';
  const flags = [];
  for (const f of ['light', 'clock', 'compass', 'coneLight', 'lure', 'nightowl']) {
    if (d[f]) flags.push(`"${f.toLowerCase()}"`);
  }
  out += `    ItemDef {
        id: "${id}", name: "${esc(d.name)}", kind: "${d.kind}", rarity: Rarity::${RAR[d.rarity || 'common']},
        slot: Some("${d.slot}"),${d.price ? ` price: Some(${d.price}),` : ''}
        icon: &[${icon}],${pal ? `\n        icon_pal: &[${pal}],` : ''}${stats ? `\n        stats: &[${stats}],` : ''}${flags.length ? `\n        flags: &[${flags.join(', ')}],` : ''}
        desc: "${esc(d.desc)}", ..BASE
    },
`;
}
out += `];
`;
writeFileSync(`${RS}/src/gear_data.rs`, out);
console.log(`gear_data.rs: ${rows.length} pieces — ${rows.map((r) => r.id).join(', ')}`);
