// extract_weather.mjs — golden fixtures for the weather sim (js/weather.js weatherFor).
// Regenerate: node tools/extract_weather.mjs
import { readFileSync, writeFileSync } from 'fs';
globalThis.Settings = { reduceFlash: () => false };
const src = readFileSync('/Users/brettbazaar/Code/Game Dev/Wriftheart/js/weather.js', 'utf8')
  .replace('return { update,', 'return { weatherFor, update,'); // expose the inner roll
eval(src + '; globalThis.Weather = Weather;');
const BIOMES = ['grassland','forest','desert','mountains','arctic','swamp','graveyard','burnt','mushroom','chaos','stormreach','galewind','hollowwood','suncoast','saltwastes','embermaw','blackdeep','wriftscar','gloammoor','tarmire'];
const lines = [];
for (const seed of [1337, 42])
  for (const season of ['SPRING','SUMMER','FALL','WINTER'])
    for (let period = 0; period < 9; period++)
      lines.push(`${seed} ${season} p${period} ` + BIOMES.map((b) => Weather.weatherFor(b, season, period, seed)).join(','));
writeFileSync('/Users/brettbazaar/Code/Game Dev/wriftheart-rs/tests/data/weather_golden.rs',
`// GENERATED by tools/extract_weather.mjs from the live js/weather.js — do not edit.
pub static WEATHER_GOLDEN: &[&str] = &[
${lines.map((l) => `    ${JSON.stringify(l)},`).join('\n')}
];
`);
console.log(`wrote ${lines.length} lines`);
