// extract_stock.mjs — the vendor stock tables from the live JS. Output:
//   src/stock_tables.rs — GENERATED: the effective post-init STOCK/GUARANTEED tables
//     (items.js pushes RECIPE_BPS blueprint ids into STOCK at module init, so the
//     literals in the source are NOT the runtime tables) + the WILD pools/weights.
//   tests/stock_parity.rs — GENERATED goldens: shopStock's full id selection
//     (procedural '~' wares stripped — the generator hasn't ported) across seeds,
//     pinning the Rust shuffle + pick to the js rng draw-for-draw.
import { readFileSync, writeFileSync } from 'fs';

const JS = '/Users/brettbazaar/Code/Game Dev/Wriftheart/js';
const RS = '/Users/brettbazaar/Code/Game Dev/wriftheart-rs';
let src = readFileSync(`${JS}/items.js`, 'utf8');

globalThis.Assets = { PALETTE: {}, bake: (g, p) => ({ grid: g, pal: p }), flipH: (g) => g };
globalThis.window = globalThis;
globalThis.Sound = { sfx: () => {} };
// Expose the module-private tables (post-init, after the RECIPE_BPS pushes).
src = src.replace(
  'return { define,',
  'return { __STOCK: STOCK, __GUARANTEED: GUARANTEED, __WILD_POOLS: WILD_POOLS, __WILD_CATS: WILD_CATS, define,',
);
if (!src.includes('__STOCK')) throw new Error('items.js return-shape changed — update the patch');
eval(src + '\nglobalThis.__I = Items;');
const Items = globalThis.__I;
const { __STOCK: STOCK, __GUARANTEED: GUARANTEED, __WILD_POOLS: WILD_POOLS, __WILD_CATS: WILD_CATS } = Items;

const idList = (ids) => ids.map((id) => `"${id}"`).join(', ');
let out = `//! stock_tables.rs — GENERATED by tools/extract_stock.mjs from js/items.js. The
//! EFFECTIVE post-init vendor tables (items.js pushes RECIPE_BPS blueprint ids into
//! STOCK/LOOT_POOLS at module init). Do not hand-edit; re-run the extractor.
#![allow(clippy::all)]

/// Shop stock by vendor kind (js STOCK) — the rotating catalogue a vendor curates 4 from.
pub static STOCK: &[(&str, &[&str])] = &[
`;
for (const [k, ids] of Object.entries(STOCK)) out += `    ("${k}", &[${idList(ids)}]),\n`;
out += `];

/// Staples a vendor ALWAYS carries (js GUARANTEED).
pub static GUARANTEED: &[(&str, &[&str])] = &[
`;
for (const [k, ids] of Object.entries(GUARANTEED)) out += `    ("${k}", &[${idList(ids)}]),\n`;
out += `];

/// Wild-shop category pools (js WILD_POOLS).
pub static WILD_POOLS: &[(&str, &[&str])] = &[
`;
for (const [k, ids] of Object.entries(WILD_POOLS)) out += `    ("${k}", &[${idList(ids)}]),\n`;
out += `];

/// Wild-shop category draw weights (js WILD_CATS).
pub static WILD_CATS: &[(&str, f64)] = &[
`;
for (const [k, w] of WILD_CATS) out += `    ("${k}", ${Number.isInteger(w) ? w + '.0' : w}),\n`;
out += `];
`;
writeFileSync(`${RS}/src/stock_tables.rs`, out);
console.log(`stock_tables.rs: ${Object.keys(STOCK).length} stock kinds, ${Object.keys(GUARANTEED).length} guaranteed, ${Object.keys(WILD_POOLS).length} wild pools`);

// --- Goldens: the full (pre-registry-filter) fixed selection per kind × seed. ---
const KINDS = Object.keys(STOCK);
const SEEDS = [1337, 42, 90210, 7, 0xdeadbeef];
let test = `//! stock_parity.rs — GENERATED by tools/extract_stock.mjs. Golden vectors from the
//! LIVE js shopStock: the fixed id selection (guaranteed + curated 4, procedural '~'
//! wares stripped) must match the js rng draw-for-draw, for every kind × seed.

#[test]
fn shop_stock_selection_matches_js() {
    let golden: &[(&str, u32, &[&str])] = &[
`;
for (const kind of KINDS) {
  for (const seed of SEEDS) {
    const ids = Items.shopStock(kind, seed >>> 0, 3).map((e) => e.id).filter((id) => !id.startsWith('~'));
    test += `        ("${kind}", ${seed >>> 0}, &[${idList(ids)}]),\n`;
  }
}
test += `    ];
    for (kind, seed, want) in golden {
        let got = wriftheart::stock::shop_stock_ids(kind, *seed);
        assert_eq!(&got, want, "kind={kind} seed={seed}");
    }
}
`;
writeFileSync(`${RS}/tests/stock_parity.rs`, test);
console.log(`stock_parity.rs: ${KINDS.length * SEEDS.length} golden rows`);
