// extract_dungeon.mjs — golden fixtures for the dungeon GENERATOR port. Evaluates the
// verbatim js/dungeon.js (render side inert — only generate() runs) and dumps every
// floor's rooms/doors/keywork/decor/pits/enemies as flat strings. tests/dungeon_parity.rs
// rebuilds the same strings from src/dungeon and compares.
//
// Regenerate: node tools/extract_dungeon.mjs
import { readFileSync, writeFileSync } from 'fs';

const JS = '/Users/brettbazaar/Code/Game Dev/Wriftheart/js';
const RS = '/Users/brettbazaar/Code/Game Dev/wriftheart-rs';

globalThis.Room = { COLS: 19, ROWS: 13, PX_W: 304, PX_H: 208 };
globalThis.clamp = (v, a, b) => Math.max(a, Math.min(b, v));
eval(readFileSync(`${JS}/dungeon.js`, 'utf8') + '; globalThis.Dungeon = Dungeon;');

const CASES = [
  ['crypt2', 1337, 'crypt', { floors: 2 }],
  ['minicave', 42, 'cave', { floors: 1, roomCount: 5 }],
  ['saltmaze', 99, 'saltmaze', { floors: 5, maze: true }],
  ['guildhall', 7, 'guildhall', { guildhall: true }],
  ['rift', 2024, 'riftvault', { floors: 1, roomCount: 9, noLocks: true }],
  ['ruinsdefault', 555, 'ruins', {}],
  ['tomb4', 31337, 'tomb', { floors: 4 }],
];

const lines = [];
for (const [id, seed, theme, opts] of CASES) {
  const d = Dungeon.generate(seed, theme, opts);
  lines.push(`case ${id} theme=${d.theme} floors=${d.numFloors}`);
  d.floors.forEach((fl, f) => {
    const keys = [...fl.rooms.keys()].map((k) => k.split(',').map(Number)).sort((a, b) => a[1] - b[1] || a[0] - b[0]);
    for (const [rx, ry] of keys) {
      const r = fl.rooms.get(`${rx},${ry}`);
      const dch = (v) => (v === 'wide' ? 'w' : v ? 'o' : '-');
      const doors = dch(r.doors.n) + dch(r.doors.s) + dch(r.doors.w) + dch(r.doors.e);
      const ch = r.chest ? `${r.chest.x},${r.chest.y}` : '-';
      const pits = (r.pits || []).map(([c, rr]) => `${c},${rr}`).join(';') || '-';
      const dn = r.stairsDown ? `${r.stairsDown.rx},${r.stairsDown.ry}` : '-';
      const up = r.stairsUp ? `${r.stairsUp.rx},${r.stairsUp.ry}` : '-';
      lines.push(
        `${id} f${f} r${rx},${ry} t=${r.type} d=${doors} ch=${ch} k=${r.key ? 1 : 0} bk=${r.bosskey ? 1 : 0} sec=${r.secret ? `${r.secret.c},${r.secret.r}` : '-'} pits=${pits} dn=${dn} up=${up} gw=${r.gwing || '-'} mir=${r.mirror ? 1 : 0}`
      );
      const dec = (r.decor || []).map((dd) => `${dd.kind}@${dd.c},${dd.r}${dd.detail ? '*' : ''}${dd.corner ? ':' + dd.corner : ''}`).join(';') || '-';
      lines.push(`${id} f${f} dec r${rx},${ry} ${dec}`);
      const foes = (r.enemies || []).map((e) => `${e.kind}@${e.x},${e.y}`).join(';') || '-';
      lines.push(`${id} f${f} foe r${rx},${ry} ${foes}`);
    }
    const locks = [...fl.locked].sort().map((k) => k + (fl.ornate.has(k) ? '!' : '')).join(';') || '-';
    lines.push(`${id} f${f} lock ${locks}`);
    lines.push(`${id} f${f} deep ${fl.deepKey || '-'} gim ${fl.gimmick || '-'}`);
  });
}

const out = `// GENERATED by tools/extract_dungeon.mjs from the live js/dungeon.js — do not edit.
pub static DUNGEON_GOLDEN: &[&str] = &[
${lines.map((l) => `    ${JSON.stringify(l)},`).join('\n')}
];
`;
writeFileSync(`${RS}/tests/data/dungeon_golden.rs`, out);
console.log(`wrote ${lines.length} golden lines`);
