// extract_people.mjs — the villager identity data from the live JS. Output:
//   src/people_data.rs — GENERATED: name pools, keeper professions, friendship lines.
//   tests/people_parity.rs — GENERATED goldens: name/gender/title/taste/birthday/line
//     for a seed sweep, pinning the Rust bit-mixing to the js formulas exactly.
import { readFileSync, writeFileSync } from 'fs';

const JS = '/Users/brettbazaar/Code/Game Dev/Wriftheart/js';
const RS = '/Users/brettbazaar/Code/Game Dev/wriftheart-rs';

globalThis.clamp = (v, a, b) => Math.max(a, Math.min(b, v));
globalThis.window = globalThis;
eval(readFileSync(`${JS}/people.js`, 'utf8') + '\nglobalThis.__P = People;');
const P = globalThis.__P;

// Reach the pools/lines through the source literals (they're not exported).
const src = readFileSync(`${JS}/people.js`, 'utf8');
const arr = (name) => eval('[' + src.match(new RegExp(`const ${name} = \\[(.*?)\\];`, 's'))[1] + ']');
const NAMES_F = arr('NAMES_F'), NAMES_M = arr('NAMES_M'), FRIENDLY = arr('FRIENDLY'), CONFIDANT = arr('CONFIDANT');
const PROF = eval('({' + src.match(/const PROF = \{(.*?)\};/s)[1] + '})');

const list = (xs) => xs.map((s) => `"${s.replace(/"/g, '\\"')}"`).join(', ');
let out = `//! people_data.rs — GENERATED by tools/extract_people.mjs from js/people.js. Name
//! pools, keeper professions, and friendship dialogue, verbatim. Do not hand-edit.
#![allow(clippy::all)]

pub static NAMES_F: &[&str] = &[${list(NAMES_F)}];
pub static NAMES_M: &[&str] = &[${list(NAMES_M)}];

/// Keepers wear their trade — building kind -> "THE SMITH" style (js PROF).
pub static PROF: &[(&str, &str)] = &[
`;
for (const [k, v] of Object.entries(PROF)) out += `    ("${k}", "${v}"),\n`;
out += `];

/// 3+ hearts (js FRIENDLY).
pub static FRIENDLY: &[&str] = &[
`;
for (const s of FRIENDLY) out += `    "${s.replace(/"/g, '\\"')}",\n`;
out += `];

/// 7+ hearts (js CONFIDANT).
pub static CONFIDANT: &[&str] = &[
`;
for (const s of CONFIDANT) out += `    "${s.replace(/"/g, '\\"')}",\n`;
out += `];
`;
writeFileSync(`${RS}/src/people_data.rs`, out);
console.log(`people_data.rs: ${NAMES_F.length}F/${NAMES_M.length}M names, ${Object.keys(PROF).length} trades, ${FRIENDLY.length}+${CONFIDANT.length} lines`);

// --- Goldens: a seed sweep through every helper. ---
const SEEDS = [0, 1, 1337, 42, 90210, 0xdeadbeef, 0x9e3779b9, 123456789, 7, 0xffffffff];
let test = `//! people_parity.rs — GENERATED by tools/extract_people.mjs. Golden vectors from the
//! LIVE js people.js: identity/taste/birthday/line formulas must match bit-for-bit.

use wriftheart::people;

#[test]
fn identity_matches_js() {
    let golden: &[(u32, &str, &str, &str)] = &[ // seed, gender, name, title(blacksmith)
`;
for (const s of SEEDS) {
  const u = s >>> 0;
  test += `        (${u}, "${P.genderFor(u)}", "${P.nameFor(u)}", "${P.titleFor(u, 'blacksmith')}"),\n`;
}
test += `    ];
    for (seed, gender, name, title) in golden {
        assert_eq!(people::gender_for(*seed), *gender, "seed={seed}");
        assert_eq!(people::name_for(*seed), *name, "seed={seed}");
        assert_eq!(people::title_for(*seed, "blacksmith"), *title, "seed={seed}");
    }
}

#[test]
fn tastes_and_birthdays_match_js() {
    let golden: &[(u32, &str, &str, i32, i32)] = &[ // seed, love, hate, season, day
`;
for (const s of SEEDS) {
  const u = s >>> 0;
  const t = P.tasteFor(u), b = P.birthdayFor(u);
  test += `        (${u}, "${t.love}", "${t.hate}", ${b.season}, ${b.day}),\n`;
}
test += `    ];
    for (seed, love, hate, season, day) in golden {
        let t = people::taste_for(*seed);
        assert_eq!(t.love, *love, "seed={seed}");
        assert_eq!(t.hate, *hate, "seed={seed}");
        let b = people::birthday_for(*seed);
        assert_eq!((b.season, b.day), (*season, *day), "seed={seed}");
    }
}

#[test]
fn lines_match_js() {
    let golden: &[(u32, i32, i64, &str)] = &[ // seed, pts, day, line
`;
for (const s of SEEDS) {
  const u = s >>> 0;
  for (const [pts, day] of [[0, 3], [350, 5], [780, 11], [1000, 28]]) {
    test += `        (${u}, ${pts}, ${day}, "${P.lineFor(u, pts, day, 'WELCOME IN.')}"),\n`;
  }
}
test += `    ];
    for (seed, pts, day, line) in golden {
        assert_eq!(people::line_for(*seed, *pts, *day, "WELCOME IN."), *line, "seed={seed} pts={pts}");
    }
}
`;
writeFileSync(`${RS}/tests/people_parity.rs`, test);
console.log(`people_parity.rs: ${SEEDS.length} seeds x 3 suites`);
