//! deathlines.rs — the random epitaph pool under "YOU DIED" (GENERATED from
//! js/deathlines.js by tools/extract_deathlines.mjs — do not hand-edit; the font renders
//! A-Z 0-9 + limited punctuation, which the source pool already respects).

pub const LINES: &[&str] = &[
    "Ashes to ashes.",
    "Your watch has ended.",
    "The dark takes us all.",
    "Rest now, wanderer.",
    "Dust returns to dust.",
    "Even heroes fall.",
    "The night outlasted you.",
    "Your story ends here.",
    "Gone, but not forgotten.",
    "The cold ground welcomes you.",
    "Another grave for the hills.",
    "Silence claims you.",
    "The lantern gutters out.",
    "You join the fallen.",
    "Sleep, brave one.",
    "The road ends in shadow.",
    "Your blood waters the roots.",
    "A short song, well sung.",
    "Twilight, and then nothing.",
    "The hero is dead. Long live the hero.",
    "Here lies Baz. He tried.",
    "The candle, snuffed.",
    "All flames flicker out.",
    "The world goes quiet without you.",
    "Your name fades from the stone.",
    "Carried home on your shield.",
    "The crows have gathered.",
    "One last breath, and gone.",
    "The map forgets you.",
    "Rest, you have earned it.",
    "The long sleep begins.",
    "Bow your head, traveller.",
    "The end of a brave little life.",
    "Worms must eat, brave knight.",
    "Stars wink out, one by one.",
    "Your shadow lingers a moment, then fades.",
    "Skill issue.",
    "Have you tried not dying?",
    "That looked like it hurt.",
    "Oof.",
    "Well, that happened.",
    "Press F to pay respects.",
    "You died doing what you loved: not dodging.",
    "Tutorial island claims another.",
    "The floor was lava. It always is.",
    "Death by confidence.",
    "You blinked. It got you.",
    "Statistically, this was likely.",
    "A bold strategy. It did not work.",
    "Maybe walk AROUND the spikes next time.",
    "Your HP reached zero. Classic.",
    "Womp womp.",
    "The goblins send their regards.",
    "Did you forget to drink the potion?",
    "Yes, that was the wrong button.",
    "You can do anything except survive.",
    "Nature is healing. You are not.",
    "Achievement unlocked: Worm Food.",
    "It was super effective.",
    "You have died of dysentery. Just kidding.",
    "Big mistakes were made.",
    "10 out of 10 would die again.",
    "Critical hit to the ego.",
    "Brave. Stupid. Dead.",
    "The math was not mathing.",
    "Caught in 4K.",
    "Speedrun to the afterlife.",
    "You played yourself.",
    "A flawless run, until it was not.",
    "The enemy used violence. It was effective.",
    "Should have brought a bigger sword.",
    "Imagine surviving. Couldn't be you.",
    "Your insurance does not cover this.",
    "Refund denied.",
    "Task failed successfully.",
    "Gravity remains undefeated.",
    "You ran out of plot armor.",
    "The cake was a lie. So was your defense.",
    "Held W. Found death.",
    "Not the W you wanted.",
    "Buffering... and you are out of buffer.",
    "Stop, he is already dead.",
    "Is that all you had?",
    "Pathetic.",
    "I expected more.",
    "Was that supposed to hurt me?",
    "You were never going to win.",
    "Kneel.",
    "Another would-be hero, undone.",
    "The Wriftheart laughs.",
    "Your courage was adorable.",
    "Run home to your village. Oh, wait.",
    "You should have stayed in bed.",
    "Tell me, did it feel like progress?",
    "I have killed a thousand of you.",
    "The shards were never yours to take.",
    "Cute. Try harder.",
    "You came so far to lose like this?",
    "I will keep your sword as a souvenir.",
    "All that effort. For nothing.",
    "Did you truly think you mattered?",
    "Sleep, little flame. The dark is patient.",
    "Get up. The world still needs you.",
    "You will get them next time.",
    "Failure is just practice.",
    "Dust yourself off, hero.",
    "The bravest fall the most.",
    "One more try. You have got this.",
    "Even the moon must set to rise.",
    "Your village would be proud.",
    "Heroes are made of second chances.",
    "Breathe. Begin again.",
    "Every legend has a rough draft.",
    "Tomorrow, you fight again.",
    "Scars are just stories now.",
    "Keep going. The shards are waiting.",
    "You are stronger than that goblin thinks.",
    "Fall seven times, stand up eight.",
    "The realm believes in you. So do I.",
    "Defeat is a door, not a wall.",
    "Rest up. Adventure is patient.",
    "Not the end. Just a checkpoint.",
    "So close to home.",
    "The journey was the treasure.",
    "You fought for something larger than you.",
    "The village will never know you tried.",
    "A long way from where you started.",
    "You wanted to see the sea one more time.",
    "There were still things left to say.",
    "The campfire waits, cold and unlit.",
    "Somewhere, a quest goes unfinished.",
    "You carried hope as far as you could.",
    "The morning will come without you.",
    "Your footprints stop here.",
    "All that wandering, and this is the rest.",
    "The stars you named keep shining.",
    "You never did learn to swim.",
    "Some doors stay closed forever.",
    "The letter home was never sent.",
    "You were almost a legend.",
    "Goodbyes are heavier than swords.",
    "The road remembers, even if no one else does.",
    "Git gud.",
    "Have you considered leveling up?",
    "Your save file weeps.",
    "Respawn anxiety intensifies.",
    "The dev did not playtest this part.",
    "This is a feature, not a bug.",
    "Loading new mistakes...",
    "The RNG was not your friend today.",
    "Frame-perfect failure.",
    "Lag is not a valid excuse here.",
    "Insert coin to continue.",
    "Your controller did nothing wrong.",
    "Somewhere a leaderboard sighs.",
    "Pixels return to the void.",
    "Error 404: hero not found.",
    "The hitbox was bigger than you thought.",
    "You found the secret death ending.",
    "Patch notes: you, nerfed.",
    "The tutorial is unskippable for a reason.",
    "Achievement progress: 0%.",
    "Have you tried turning yourself off and on?",
    "The narrator did not see that coming either.",
    "Press start to suffer.",
    "Your build was a meme build.",
    "That was not in the strategy guide.",
    "You really dropped the ball. And the HP.",
    "Looks like you bit the dust biscuit.",
    "That was a grave error.",
    "You are dead-icated to this, at least.",
    "Rest in pixels.",
    "You went out with a wimper, not a bang.",
    "A dead end, literally.",
    "You have shuffled off this mortal tile.",
    "Knight to nowhere.",
    "Your luck finally ran sword.",
    "That fight was a real heartbreaker.",
    "You flatlined the vibe.",
    "Hasta la vista, Baz.",
    "Curtains. The dramatic kind.",
    "Game of moans.",
    "You were swordly missed.",
    "A real cliff-hanger. You hung. You fell.",
    "Out of HP and out of luck.",
    "This is the plot twist nobody wanted.",
    "You met a grave situation.",
    "Dead.",
    "Splat.",
    "Yikes.",
    "Brutal.",
    "Done.",
    "Lights out.",
    "Game over, man.",
    "And scene.",
    "Finito.",
    "Nope.",
    "Such is life.",
    "The end.",
    "Goodnight.",
    "Wasted.",
    "Defeated.",
    "Curtains.",
    "Fin.",
    "Toast.",
    "Kaput.",
    "So it goes.",
    "We are all just borrowing time.",
    "The universe is indifferent to your build.",
    "Death is only a change of rooms.",
    "Entropy always collects its debt.",
    "You returned what was never yours: the breath.",
    "All rivers run to the same dark sea.",
    "Nothing is lost. It only changes shape.",
    "The wheel turns, and you turn with it.",
    "To die is to finish the joke of living.",
    "Stardust you were, stardust again.",
    "The candle does not fear the dark.",
    "Even the mountains die, only slower.",
    "Your atoms have other appointments.",
    "Time is a circle, and so is this.",
    "Every ending feeds a beginning.",
    "The void says hello.",
    "You were a brief, bright accident.",
    "Forever is just a long today.",
    "The dream dreams on without the dreamer.",
    "Silence is the loudest answer.",
    "A pigeon witnessed this. It told no one.",
    "Your last thought was about soup.",
    "Somewhere, a kettle is boiling.",
    "The moon is made of regrets tonight.",
    "Three goblins are now arguing over your hat.",
    "A bard is already writing a worse version.",
    "The grass grew back. You did not.",
    "Your boots outlived you. Rude.",
    "A snail crosses the battlefield, unbothered.",
    "Even the slime feels a little bad.",
    "The cave has seen better heroes. Not many.",
    "You will be a cautionary tavern tale.",
    "A spider inherits your loot.",
    "The wind carries your hat away.",
    "Mushrooms will attend the funeral.",
    "Your ghost forgets why it is here.",
    "The merchant raises his prices anyway.",
    "A frog observed everything. Judgmentally.",
    "Your sword is embarrassed to be seen with you.",
    "The fireflies hold a tiny vigil.",
    "A goblin did that. A GOBLIN.",
    "Spider: 1. Hero: 0.",
    "The slime absorbed your dignity.",
    "Death by tiny mushroom. Majestic.",
    "Burned to a crisp. Smells like courage.",
    "Poison: the slow handshake of doom.",
    "You drowned. The water won.",
    "Down you go. Mind the rocks.",
    "A trap you walked into. Twice.",
    "The boss did not even try its second phase.",
    "It was a bat. Killed by a bat.",
    "The dark ate your health bar.",
    "Spikes: nature's punctuation.",
    "You hugged the fire. It did not hug back.",
    "That arrow knew your name.",
    "The cave-in sends its apologies.",
    "A wolf pack RSVP'd to your funeral.",
    "Lava: still hot, who knew.",
    "The pit was deeper than your plans.",
    "Stung, bitten, and now buried.",
    "The wand misfired. So did you.",
    "Out-jogged by a skeleton.",
    "Flattened by something you did not read.",
    "The bear was not a hugger.",
    "A pebble. A single, fatal pebble.",
    "You lost a staring contest with a sword.",
    "The fog rolled in and took the rest.",
    "Eaten. The cave is well fed.",
    "Frozen mid-victory pose.",
    "The current had other plans.",
    "GG. No re.",
    "Touch grass. Oh, you are under it now.",
    "L. Take the L.",
    "Ratio'd by a goblin.",
    "Caught lacking.",
    "Down bad. Then just down.",
    "It is giving... deceased.",
    "No cap, you got bodied.",
    "Sherlock could not find your defense.",
    "You fell off. Literally.",
    "Cringe. Fatal cringe.",
    "Speedran your own demise.",
    "Hold this L for me, would you.",
    "Mid run. Tragic end.",
    "Bro thought he was him.",
    "Certified hood classic: dying.",
    "POV: you forgot to block.",
    "Main character energy. Side character ending.",
    "Tried to clutch. Got clutched.",
    "That was a diff. A skill diff.",
    "A winner is just a loser who respawned.",
    "Your potential remains theoretical.",
    "Great things take time. You ran out.",
    "The early goblin gets the hero.",
    "When one door closes, a coffin opens.",
    "Believe in yourself, said no enemy ever.",
    "Hard work pays off. Eventually. Not today.",
    "Dream big. Dodge bigger.",
    "Confidence is silent. So are you now.",
    "Patience is a virtue you did not buy.",
    "Adventure favors the living. Sorry.",
    "Reach for the stars, fall in the moat.",
    "You missed the swing that mattered.",
    "Be the hero you wish to see. Briefly.",
    "Today's loss is tomorrow's lesson.",
    "Slow and steady gets eaten too.",
    "Your comfort zone misses you.",
    "Bravery is fear that died first.",
    "Tomorrow needs you. Today is unconvinced.",
    "A journey of a thousand steps ends in one pit.",
    "The minstrels will exaggerate this.",
    "Your tab at the tavern goes unpaid.",
    "The blacksmith kept your deposit.",
    "Three taverns will claim you drank there.",
    "A statue, perhaps. A small one. Maybe.",
    "The king will not notice. He never does.",
    "Your quest is now somebody else's problem.",
    "The guild revokes your membership.",
    "No refunds at the apothecary.",
    "The innkeeper sighs and changes the sheets.",
    "Bards argue over your final words.",
    "The town crier mispronounces your name.",
    "Your bounty goes uncollected.",
    "A peasant finds your boots. Lucky peasant.",
    "The tavern dog will miss you most.",
    "Your map is now scrap parchment.",
    "The wizard saw this coming. He says.",
    "Filed under: heroes, former.",
    "The chapel adds a small, sad bell.",
    "Even the gravedigger looks tired.",
    "The stars do not pause for the brave.",
    "You were a comma in a long sentence.",
    "Night folds you into its pocket.",
    "The sea keeps what the sea takes.",
    "A brief flame against an old dark.",
    "The mountains will not remember the climber.",
    "You borrowed light, and the loan came due.",
    "Snow falls the same on heroes and weeds.",
    "The river does not mourn the leaf.",
    "Every dawn is paid for by a dusk.",
    "You go where all the songs end.",
    "The wind unlearns your name.",
    "Dust dances where you used to stand.",
    "The horizon keeps its promises to no one.",
    "A single breath, returned to the world.",
    "The roots know you better than the sky.",
    "Time, that old thief, has your purse now.",
    "You set with the sun and did not rise.",
    "The dark was here first. It stays longest.",
    "Quiet now. The story breathes without you.",
    "The goblins are forming a union over this.",
    "A turnip witnessed your final moment.",
    "Your last words were just vibes.",
    "Somewhere, a chicken clucks knowingly.",
    "The mushrooms have started a rumor.",
    "A very polite ghost takes your spot.",
    "The trees pretend they did not see.",
    "Your hat files for emancipation.",
    "A snail laps you, again.",
    "The moon left a one-star review.",
    "Your shadow is updating its resume.",
    "A bee attended. Out of respect.",
    "The slime throws a small wet party.",
    "Your inventory feels lighter already.",
    "A frog says what we are all thinking.",
    "The campfire crackles, unimpressed.",
    "Squirrels divide your estate.",
    "The dungeon redecorates around you.",
    "A worm becomes the protagonist now.",
    "Your spleen has left the chat.",
    "Even I did not script that one.",
    "The narrator pours one out for you.",
    "I would offer commentary, but wow.",
    "Let the record show: you tried.",
    "I have seen worse. Not much worse.",
    "We will gloss over that in the retelling.",
    "Off the record, that was rough.",
    "The author looks away politely.",
    "I am contractually obligated to say: oof.",
    "Between us, that enemy was not even strong.",
    "I will pretend I did not narrate that.",
    "The story shrugs and turns the page.",
    "Plot armor was out of stock.",
    "We do not talk about run number this.",
    "I rate that death three skulls out of five.",
    "Somewhere the script supervisor is crying.",
    "Cut. Reset. From the top.",
    "That was not the ending I outlined.",
    "The footnotes will be unkind.",
    "And the crowd goes... silent.",
    "You died hungry. Tragic on two counts.",
    "Your soup is getting cold.",
    "Should have packed more sandwiches.",
    "Death before breakfast. Bold.",
    "The bread you saved is now a relic.",
    "Out of potions, out of snacks, out of luck.",
    "Your last apple rolls into the abyss.",
    "A hero marches on its stomach. Yours stopped.",
    "The stew at home will go to waste.",
    "Empty flask, empty hope.",
    "You skipped lunch for THIS.",
    "Hangry, then just gone.",
    "The tavern pie will never know your love.",
    "Crumbs to crumbs.",
    "A full heart, an empty plate.",
    "Damage taken: yes. Damage dealt: debatable.",
    "Survival rate: rounding error.",
    "0 HP and 100% commitment.",
    "Your KDR weeps quietly.",
    "Deaths: plus one. Morale: minus ten.",
    "Defense stat: decorative.",
    "Crit chance against you: apparently 100%.",
    "You rolled a one. Spiritually.",
    "Average run time: not long enough.",
    "Hit points: a suggestion, ignored.",
    "Luck stat: currently on vacation.",
    "Experience gained: a humbling kind.",
    "Your win streak was a typo.",
    "Final score: a participation skull.",
    "The odds were posted. You did not read them.",
    "Brave and bold, but the story turned cold.",
    "Swift was the sword, slow was the dodge.",
    "You came, you saw, you got conquered.",
    "Big dreams, small shield.",
    "Quick to fight, quicker to fall.",
    "A flash of steel, a sudden still.",
    "Bright the spark, brief the burn.",
    "Loud the charge, soft the thud.",
    "Bold of heart, short of breath.",
    "Grand the plan, grim the end.",
    "Yoinked.",
    "Deleted.",
    "Bonked.",
    "Expired.",
    "Fumbled.",
    "Cooked.",
    "Folded.",
    "Vanished.",
    "Snuffed.",
    "Retired. Permanently.",
    "Concluded.",
    "Whoops.",
    "Sayonara.",
    "Adios.",
    "Curtain call.",
    "You have died of overconfidence.",
    "You have died of poor positioning.",
    "You have died of one more room.",
    "You have died of greed. The chest was a trap.",
    "You have died of forgetting to heal.",
    "You have died of looking the wrong way.",
    "You have died of trusting that bridge.",
    "You have died of a fair fight, unfairly.",
    "You have died of bad timing.",
    "You have died of curiosity. Classic.",
    "You have died of standing still.",
    "You have died of running in.",
    "You have died of believing the tutorial.",
    "You have died of vibes alone.",
    "You have died of saying watch this.",
    "You had one job: stay alive.",
    "Hero, dismissed. See the front desk.",
    "Performance review: needs improvement.",
    "Your hero license is hereby revoked.",
    "Promoted to ghost, effective immediately.",
    "Adventuring is not for everyone. Clearly.",
    "Resume updated: former hero.",
    "You are now between quests. Forever.",
    "Severance pay: one rusty sword.",
    "You clocked out early. Way early.",
    "The guild's exit interview is brief.",
    "Demoted to legend, posthumously.",
    "Your apprenticeship ends abruptly.",
    "Back to the job market, ghost.",
    "Heroism: not a great career fit.",
    "In memoriam: a hero, sort of.",
    "Breaking: hero stops, abruptly.",
    "Obituary: kept it short.",
    "Today in the realm: a sad little thud.",
    "Headline: brave, then horizontal.",
    "Reported missing. Found flat.",
    "Front page: nothing. You were page nine.",
    "The scrolls record a small footnote.",
    "Late edition: hero, late.",
    "Press release: oof, comma, ouch.",
    "At least the scenery was nice.",
    "At least you looked cool. Briefly.",
    "At least the goblin remembers you.",
    "At least you did not rage quit.",
    "At least your hair looked great.",
    "At least you found out what that did.",
    "Well, at least it was quick.",
    "At least nobody filmed it. Probably.",
    "At least the boss respects you now.",
    "At least the worms eat well tonight.",
    "Folded faster than a tavern chair.",
    "Dropped quicker than a hot coal.",
    "Gone faster than free mead.",
    "Lasted shorter than a candle in rain.",
    "Faded quicker than morning mist.",
    "Crumpled like wet parchment.",
    "Wilted faster than picked flowers.",
    "Fell harder than the autumn leaves.",
    "Out quicker than a snuffed match.",
    "Done faster than a goblin's lunch.",
    "The village stays unavenged. For now.",
    "The shards will find another bearer.",
    "Your home remains in ashes.",
    "The Wriftheart sleeps a little easier.",
    "Ten shards, and you are not their hero.",
    "The dark castle gate stays shut.",
    "Somewhere, a bell tolls for the village.",
    "The quest log keeps your unfinished line.",
    "Your family's name waits to be cleared.",
    "The rift widens while you rest.",
    "Forecast: grim, with scattered grief.",
    "Today: overcast, with sudden endings.",
    "Light rain, heavy heart, no pulse.",
    "Cold front moving in. So are you.",
    "Fog rolling in. Hero rolling out.",
    "Sunny elsewhere. Not for you.",
    "High of zero. HP, that is.",
    "Storms ahead. You will miss them.",
    "Clear skies. Unclear future.",
    "Chance of revival: see CONTINUE.",
    "That went poorly.",
    "A minor setback. The fatal kind.",
    "Slightly worse than planned.",
    "Not your finest hour. Or minute.",
    "A little bit dead.",
    "The worst thing to ever happen. Ever.",
    "Catastrophe. Utter. Complete. Final.",
    "The single greatest defeat. Yours.",
    "A modest apocalypse, just for you.",
    "Technically, a learning experience.",
    "A blade. A blink. The long quiet.",
    "Cold cave, warm blood, the end.",
    "One step too far. Silence.",
    "The last torch bows out.",
    "Snow on a still sword.",
    "Wind. A name, unspoken.",
    "Dusk, a sigh, then dark.",
    "The river takes the leaf.",
    "Small heart, large hush.",
    "Petals fall on a quiet shield.",
    "Checkpoint? You did not reach one.",
    "Your loot stays in the dungeon, mocking you.",
    "Respawn available. Pride not included.",
    "The chest you wanted is still locked.",
    "New game minus: confidence.",
    "The difficulty was set to yes.",
    "Continue? The game dares you.",
    "Your build needed one more level.",
    "Try the other path. This one bites.",
    "Autosaved into a bad decision.",
    "Your five-star adventure gets one star.",
    "Swipe left on that decision.",
    "You got left on read by the reaper.",
    "No bars in this dungeon. No luck either.",
    "Out of office: deceased.",
    "Your subscription to living has lapsed.",
    "Unsubscribed from the mortal coil.",
    "Buffering life... connection lost.",
    "Your warranty did not cover goblins.",
    "Terms accepted: you, defeated.",
    "A crow takes notes for next time.",
    "The cave bats applaud politely.",
    "A rat unionizes your leftovers.",
    "The wolves write a thank-you note.",
    "A deer watches, then keeps grazing.",
    "Owls hoot what sounds like told you so.",
    "The spiders weave a small tribute.",
    "A fox steals the credit and your coin.",
    "Pigeons coo your eulogy, badly.",
    "The fish were not impressed either.",
    "You are braver than yesterday already.",
    "The realm will wait while you regroup.",
    "Heroes rust, then shine again.",
    "Take the loss. Keep the lesson.",
    "Your courage outlives this moment.",
    "Stand up. The story is not done.",
    "You fell forward. That still counts.",
    "The next run is yours. I can feel it.",
    "Even now, you are still the hero.",
    "Begin again, a little wiser.",
    "Predictable. Like the last one.",
    "You fight like the village you lost.",
    "I have already forgotten your face.",
    "Was that your best? How sad.",
    "The shards laugh in their vaults.",
    "Come back when you can hold a sword.",
    "You are a footnote in my long story.",
    "Try the front door next time. Bolder.",
    "Your hope was the funniest part.",
    "Another candle for my collection.",
    "You really axed for it.",
    "A grave miscalculation.",
    "You are bone-tired now. Permanently.",
    "That ghost of a chance? Gone.",
    "You met your maker, and your taker.",
    "Stone cold. Like the floor.",
    "Your luck took a stab in the dark.",
    "A slime-y way to go.",
    "You got the point. Several, actually.",
    "Plot holes are easier to climb out of.",
    "Squished.",
    "Zapped.",
    "Iced.",
    "Toppled.",
    "Skewered.",
    "Outdone.",
    "Stilled.",
    "Ousted.",
    "Felled.",
    "Undone.",
    "You have died of just one more hit.",
    "You have died of holding the wrong way.",
    "You have died of forgetting the pattern.",
    "You have died of a confident misstep.",
    "You have died of reading too slowly.",
    "You have died of healing one tick late.",
    "You have died of the scenic route.",
    "You have died of poking the obvious trap.",
    "You have died of saying it is fine.",
    "You have died of main-character syndrome.",
    "Right on schedule.",
    "I will take it from here.",
    "Mind the step. There it is.",
    "You are expected. This way.",
    "No need to pack. You travel light now.",
    "I do enjoy the punctual ones.",
    "Same time next run?",
    "Do not keep the ferryman waiting.",
    "I have your name on the list. Again.",
    "Come along. The dark is cozy.",
    "You get used to it. Mostly.",
    "Hold still. This part is easy.",
    "Funny, you looked taller alive.",
    "Welcome to the quiet club.",
    "I knew you would drop in.",
    "Your table for one is ready.",
    "The scythe says hello.",
    "Tea? We have eternity.",
    "You are not the first today.",
    "Step into the shade.",
    "Final grade: F, for fallen.",
    "You failed the dodge portion.",
    "Test results: deceased, see notes.",
    "Points off for dying.",
    "Did not study the boss. It shows.",
    "Pop quiz: you forgot to live.",
    "Marked absent from the rest of the game.",
    "Extra credit denied. So was survival.",
    "Report card: needs more potions.",
    "An A for effort, a Z for outcome.",
    "And he is DOWN! The crowd gasps.",
    "A swing, a miss, a tragedy.",
    "He shoots, he misses, he expires.",
    "Folks, that is a career-ender.",
    "Replay shows: yeah, that was bad.",
    "And the goblin takes the title.",
    "No timeouts left. No HP left.",
    "That is a flag on the play. And a funeral.",
    "Benched. For eternity.",
    "The comeback was not televised.",
    "And that is how you get cooked.",
    "Lightly seared, then served.",
    "A pinch of courage, a dash of doom.",
    "Reduced to nothing over high heat.",
    "Today's special: regret, well done.",
    "You folded like a souffle.",
    "Marinated in bad decisions.",
    "Chef's kiss of death.",
    "Overcooked. Under-prepared.",
    "Plated and done.",
    "Exit, pursued by a goblin.",
    "And the curtain falls. Heavily.",
    "A tragedy in one short act.",
    "Bravo. Now stay down for the bow.",
    "The understudy is up next.",
    "Alas, poor hero. We knew you, briefly.",
    "Intermission. A permanent one.",
    "The audience demands a refund.",
    "Encore? Press CONTINUE.",
    "That was the dramatic kind of dead.",
    "And that is that.",
    "Nothing personal. Just fatal.",
    "This is the part where you stop.",
    "The story does not need you anymore.",
    "You were a verb. Now you are a noun.",
    "Existence: revoked.",
    "Here ends the you of it all.",
    "The plot continues. You do not.",
    "You have reached the end of you.",
    "Off you pop, into the nothing.",
    "They will say you were brave. Mostly.",
    "They will round up when they tell it.",
    "They will name a pothole after you.",
    "They will misremember it fondly.",
    "They will say the goblin was bigger.",
    "They will whisper your name. Probably.",
    "They will toast you, then order more.",
    "They will say you almost made it.",
    "They will blame the lag.",
    "They will say it was a good run.",
    "The swamp keeps your boots.",
    "The graveyard adds another regular.",
    "The desert drinks what is left of you.",
    "The snow tucks you in for good.",
    "The forest closes over the gap.",
    "The cave echoes one last oof.",
    "The marsh bubbles a small goodbye.",
    "The ruins gain a fresh ghost.",
    "The dunes shift to cover the spot.",
    "The frost writes your name in white.",
    "To absent friends. Like you.",
    "Here is to a short, loud life.",
    "Cheers, hero. The mead is on us.",
    "Raise a glass. Lower a hero.",
    "One for the road you did not finish.",
    "To the brave and briefly alive.",
    "Bottoms up. You are bottoms down.",
    "A toast: may the next one dodge.",
    "Drink up. The legend rounds its edges.",
    "Skol, to the fallen flame.",
    "Dear hero: you have been let go.",
    "Re: your survival. Regretfully, no.",
    "To whom it may concern: oof.",
    "Dear adventurer, please try again.",
    "Notice: the realm requires a new hero.",
    "Sincerely, the goblin that won.",
    "P.S. you should have run.",
    "Attached: your remaining HP. (None.)",
    "Yours in the dirt, the dungeon.",
    "Signed, sealed, delivered, deceased.",
    "Imagine the loot you will not get.",
    "Imagine surviving that. Wild, right?",
    "Imagine the village's face. Oh.",
    "Imagine if you had healed. Just imagine.",
    "Imagine being remembered. Aim for that.",
    "Imagine the sequel. You are not in it.",
    "Imagine the high score. Now let it go.",
    "Imagine dodging. Truly, picture it.",
    "Imagine a world where you blocked.",
    "Imagine that, but with a pulse.",
    "Uninstall? No, just respawn.",
    "That was not it, chief.",
    "Hard mode, harder ending.",
    "You got speedrun by a goblin.",
    "No heals, no chill, no pulse.",
    "The lobby misses you. Briefly.",
    "Disconnected from life.",
    "Your K/D took emotional damage.",
    "That is a yikes from the chat.",
    "Respawn timer: your call.",
    "The dark does not count its winnings.",
    "You were weather. Now you are climate.",
    "The void files you under M, for moot.",
    "Light forgets the lamp it left.",
    "You return to the great unbothered.",
    "The cosmos shrugs in your size.",
    "All maps end at the same blank edge.",
    "You were a spark the night out-waited.",
    "The silence had room for one more.",
    "Even echoes eventually agree to stop.",
    "Here fell one who would not flee.",
    "They tried the hard way. It tried back.",
    "Brief of life, long of nerve.",
    "Loved the quest. It did not love back.",
    "Sword high, guard low, here lies rest.",
    "A small stone, a big heart, a still field.",
    "Wandered far, rests near.",
    "Kept the faith, lost the fight.",
    "Their lantern lit the way for others.",
    "Gone ahead to scout the dark.",
    "A committee of moths reviewed your run.",
    "Your last sneeze had better timing.",
    "The dungeon gift shop sells out of you.",
    "A goose saw this and left, honking.",
    "Your ghost asks for the manager.",
    "The floor tiles vote to keep you.",
    "A traveling salesman steps over you.",
    "Your echo files a complaint.",
    "The torches dim out of awkwardness.",
    "A beetle inherits the realm. Crawl on.",
    "You learned the room. Now beat it.",
    "Failure today, footnote tomorrow.",
    "You are one run closer. Truly.",
    "The hero is not the one who never falls.",
    "Shake it off. Steel up. Go again.",
    "You have more tries than the goblin does.",
    "Your grit is the real loot.",
    "This is where comebacks are born.",
    "Lace up. The realm still hopes.",
    "You will laugh about this run later.",
    "Boom. Gone.",
    "Pop.",
    "Thud.",
    "Lights down.",
    "And rest.",
    "Out.",
    "Sayonara, hero.",
    "Welp.",
    "Curtains, friend.",
    "Tapped out.",
    "You have died of one bad pixel.",
    "You have died of looting under fire.",
    "You have died of the long way around.",
    "You have died of a brave dumb idea.",
    "You have died of not pressing block.",
    "You have died of a misjudged jump.",
    "You have died of greed and a goblin.",
    "You have died of the second mistake.",
    "You have died of underestimating slime.",
    "You have died of being you. Heroically.",
    "The goblin tells this story for years.",
    "You made one goblin very happy.",
    "A goblin frames your sword on its wall.",
    "The goblin did not even break a sweat.",
    "You are the goblin's favorite memory.",
    "The goblin thanks the academy.",
    "A goblin writes home about you.",
    "The goblin keeps your hat as a trophy.",
    "You taught a goblin to believe.",
    "The goblin files you under easy.",
    "The merchant marks you down. Literally.",
    "Your coin purse outlived you.",
    "No sale. No survivor.",
    "The shopkeeper sighs and restocks.",
    "Your debt passes to your next of kin.",
    "Everything must go. You did.",
    "The economy did not notice.",
    "Bargain of the day: your leftover gear.",
    "The merchant offers a funeral discount.",
    "Buy low, sell high, die suddenly.",
    "You are here. Permanently.",
    "Off the map, off the mortal coil.",
    "The compass points to nowhere now.",
    "X marks your spot. The final one.",
    "You took a wrong turn at the abyss.",
    "Recalculating... no routes remain.",
    "The map adds a small skull here.",
    "You found the edge. It found you.",
    "Lost, then found, then lost again.",
    "The road home grew one ghost longer.",
    "The bard sings of your brief, brave stand.",
    "A ballad, mostly accurate, mostly sad.",
    "The bard needed a tragic verse anyway.",
    "They will hum it wrong at the tavern.",
    "Three chords and a sniffle for you.",
    "The chorus is just a long sigh.",
    "A B-side at best, sadly.",
    "The bard rhymes your name with flame.",
    "Your song is short but it slaps.",
    "Even the bard tears up. A little.",
    "Achievement: Down Bad, Down Fast.",
    "Trophy unlocked: Worm Buffet.",
    "Badge earned: Professional Faller.",
    "Milestone: first of many deaths.",
    "Rare drop: a humbling experience.",
    "100% completion of dying.",
    "New title earned: The Fallen.",
    "Streak ended. A new streak begins.",
    "Collectible found: your own demise.",
    "Leaderboard updated: you, near bottom.",
    "A cold snap, and so did your run.",
    "Hail to the fallen. Literal hail.",
    "Skies grey, mood greyer.",
    "A drizzle of doom, lightly salted.",
    "Frost advisory: too late.",
    "The sun set on time. You did not.",
    "Thunder applauds. Or mocks. Unclear.",
    "A gentle breeze carries you off.",
    "Visibility low. Survivability lower.",
    "Cloudy with a high chance of dead.",
    "You fell with your face to the foe.",
    "No retreat in you. Only this.",
    "You spent your last breath fighting.",
    "Honor intact. Body, less so.",
    "You did not yield. You ran out.",
    "A noble end, if a sudden one.",
    "You went down swinging. Always.",
    "They will not say you flinched.",
    "Your courage never once blinked.",
    "Defeated, never disgraced.",
    "Your last words: I got this.",
    "Your final thought: oh, THAT button.",
    "Famous last words: it is just one goblin.",
    "Your last words: hold my potion.",
    "You whispered: worth it. Debatable.",
    "Last words: I will dodge next ti-",
    "You said trust me. We did. Oops.",
    "Final words: what does this lever do?",
    "You muttered: almost had it.",
    "Your last word was just a vowel.",
    "The dungeon thanks you for visiting.",
    "Another room, another regular guest.",
    "The walls have seen this before.",
    "The dungeon keeps what wanders in.",
    "You are part of the decor now.",
    "The torches will remember you. Briefly.",
    "The dungeon does not do refunds.",
    "Welcome, the dungeon purrs. Stay.",
    "The floor was happy to meet you.",
    "The dark hallway adds a footnote.",
    "Good news: it is over. Bad news: so are you.",
    "Good news: no more goblins. For you.",
    "Good news: you can stop trying so hard.",
    "Bad news travels fast. You went faster.",
    "Good news: you are famous. Posthumously.",
    "Half-empty, fully expired.",
    "Silver lining: a free trip downstairs.",
    "On the bright side: there is no side.",
    "Glass half full of regret.",
    "The upside: you can finally rest.",
    "To live is to eventually not.",
    "The brave die once. You confirmed it.",
    "All things end. You, notably, just did.",
    "What is a hero but a delayed epitaph?",
    "Mortality: still undefeated.",
    "The only sure quest is this one.",
    "Every map has this same blank edge.",
    "We all speedrun the same ending.",
    "Death is just lag with commitment.",
    "The candle envies no flame now.",
    "Aw, you were doing so well. Sort of.",
    "So close. Well, not that close.",
    "You had a plan. It had other plans.",
    "Nearly heroic. We will take nearly.",
    "Almost is a nice place to visit.",
    "You gave it 60%. It needed 100.",
    "Points for enthusiasm, none for living.",
    "A for ambition, see me after class.",
    "You will get it. Eventually. Maybe.",
    "Hey, most of that run was great.",
    "You never finished your sandwich.",
    "That side quest stays open forever.",
    "You meant to upgrade that armor.",
    "The shortcut was the long way after all.",
    "You should have saved that potion.",
    "One more level would have done it.",
    "You wanted to pet the dog first.",
    "That treasure stays buried with you.",
    "You left the stove on, probably.",
    "So many doors, and now none.",
    "You become the warning in every tavern.",
    "Drinks are cheaper than your mistakes.",
    "The regulars raise a quiet mug.",
    "They will retell this with more dragons.",
    "A stranger buys a round in your honor.",
    "The story grows a sword each telling.",
    "You are now a cautionary limerick.",
    "The barkeep adds your tab to legend.",
    "They swear you fought ten. It was one.",
    "Your legend doubles by closing time.",
    "Crumpled.",
    "Splattered.",
    "Goner.",
    "Flattened.",
    "Demised.",
    "Departed.",
    "Keeled.",
    "Bested.",
    "Finished.",
    "Smote.",
    "You have died of one greedy step.",
    "You have died of a heroic faceplant.",
    "You have died of trusting the railing.",
    "You have died of the victory lap.",
    "You have died of forgetting to look up.",
    "You have died of an avoidable thing.",
    "You have died of style over substance.",
    "You have died of the last 1 HP.",
    "You have died of the goblin you ignored.",
    "You have died of overdrawn HP.",
    "The credits roll early for you.",
    "You speedwalked into the void.",
    "A moment of silence. There, done.",
    "The afterlife has a short queue today.",
    "You picked the wrong room to be brave in.",
    "Even your shadow tapped out.",
    "The boss never learned your name. Oh well.",
    "You went where the maps cannot.",
    "Your luck filed for divorce.",
    "The grass is greener. You are under it.",
    "A hero-shaped hole in the plot.",
    "The reaper double-checks the list. Yep.",
    "You blinked at the worst time.",
    "The dungeon air thanks you for the snack.",
    "Your final pose was almost cool.",
    "A round of applause, then a shovel.",
    "You ran out of brave before HP.",
    "The world keeps spinning. You stopped.",
    "That was the bad ending. There are more.",
    "Your sequel is a prequel now.",
    "A small thud, a big quiet.",
    "You found out. We all warned you.",
    "The torch you carried gutters and dies.",
    "Better luck, braver hero.",
    "Your name joins the long, quiet list.",
];
