//! gear_data.rs — GENERATED by tools/extract_gear.mjs from js/items.js. The wearable
//! catalog: every js armor piece (head/body/feet) + the stat-row and gear-flag
//! trinkets, icons and stats verbatim. items::get chains this behind DEFS.
//! Do not hand-edit; re-run the extractor.
#![allow(clippy::all)]

use crate::items::{ItemDef, Rarity, BASE};

pub static GEAR_DEFS: &[ItemDef] = &[
    ItemDef {
        id: "lantern", name: "Lantern", kind: "TRINKET", rarity: Rarity::Uncommon,
        slot: Some("trinket"), price: Some(80),
        icon: &["...KK...", "..KPPK..", ".KPooPK.", ".KooooK.", ".KooooK.", ".KPooPK.", "..KKKK..", "........"],
        flags: &["light"],
        desc: "Equip in a trinket slot to light your way at night.", ..BASE
    },
    ItemDef {
        id: "leathercap", name: "Leather Cap", kind: "HEAD", rarity: Rarity::Common,
        slot: Some("head"), price: Some(60),
        icon: &["........", "..dddd..", ".dDDDDd.", "dDDDDDDd", "dDDDDDDd", ".dddddd.", "........", "........"],
        stats: &[("defense", 1.0)],
        desc: "A simple cap. +1 Armor.", ..BASE
    },
    ItemDef {
        id: "ironhelm", name: "Iron Helm", kind: "HEAD", rarity: Rarity::Rare,
        slot: Some("head"), price: Some(350),
        icon: &["..aaaa..", ".aAAAAa.", "aAAAAAAa", "aAKKKKAa", "aAAAAAAa", ".aA..Aa.", "..a..a..", "........"],
        stats: &[("defense", 2.0)],
        desc: "Sturdy steel. +2 Armor.", ..BASE
    },
    ItemDef {
        id: "minerhelm", name: "Miner's Helmet", kind: "HEAD", rarity: Rarity::Uncommon,
        slot: Some("head"), price: Some(130),
        icon: &["..aaaa..", ".aAAAAa.", "aAPPPPAa", "aAyooyAa", "aAAAAAAa", "aAAAAAAa", ".aaaaaa.", "........"],
        stats: &[("defense", 1.0)],
        flags: &["conelight"],
        desc: "A lamp-lit helm; casts a cone of light where you look. +1 Armor.", ..BASE
    },
    ItemDef {
        id: "leathervest", name: "Leather Vest", kind: "BODY", rarity: Rarity::Uncommon,
        slot: Some("body"), price: Some(140),
        icon: &[".D....D.", ".DDDDDD.", ".DddddD.", ".DddddD.", ".DddddD.", ".DDDDDD.", "..D..D..", "........"],
        stats: &[("defense", 1.0), ("maxhp", 1.0)],
        desc: "Padded hide. +1 Armor, +1 HP.", ..BASE
    },
    ItemDef {
        id: "chainmail", name: "Chainmail", kind: "BODY", rarity: Rarity::Rare,
        slot: Some("body"), price: Some(380),
        icon: &[".a....a.", ".aAaAaA.", ".AaAaAa.", ".aAaAaA.", ".AaAaAa.", ".aAaAaA.", "..a..a..", "........"],
        stats: &[("defense", 2.0)],
        desc: "Linked rings. +2 Armor.", ..BASE
    },
    ItemDef {
        id: "platemail", name: "Plate Mail", kind: "BODY", rarity: Rarity::Epic,
        slot: Some("body"), price: Some(1100),
        icon: &[".A....A.", ".AWWWWA.", ".AWAAWA.", ".AWAAWA.", ".AWWWWA.", ".AAAAAA.", "..A..A..", "........"],
        stats: &[("defense", 3.0)],
        desc: "Heavy plate. +3 Armor.", ..BASE
    },
    ItemDef {
        id: "leatherboots", name: "Leather Boots", kind: "FEET", rarity: Rarity::Common,
        slot: Some("feet"), price: Some(60),
        icon: &[".D....D.", ".D....D.", ".D....D.", ".D....D.", ".DD..DD.", "DDD.DDD.", "ddd.ddd.", "........"],
        stats: &[("defense", 1.0)],
        desc: "Tough soles. +1 Armor.", ..BASE
    },
    ItemDef {
        id: "travelboots", name: "Traveler Boots", kind: "FEET", rarity: Rarity::Rare,
        slot: Some("feet"), price: Some(350),
        icon: &[".b....b.", "lb....bl", ".b....b.", ".b....b.", ".bb..bb.", "bbb.bbb.", "AAA.AAA.", "........"],
        stats: &[("move", 0.15)],
        desc: "Light and quick. +Move speed.", ..BASE
    },
    ItemDef {
        id: "compass", name: "Compass", kind: "TRINKET", rarity: Rarity::Epic,
        slot: Some("trinket"), price: Some(800),
        icon: &["..pppp..", ".p.r..p.", "p..r...p", "p..r...p", "p...A..p", "p...A..p", ".p....p.", "..pppp.."],
        icon_pal: &[('p', 0xc8a84a), ('r', 0xd82800), ('A', 0xdcdce4)],
        flags: &["compass"],
        desc: "Equip for a live minimap on your HUD.", ..BASE
    },
    ItemDef {
        id: "regenring", name: "Ring of Regen", kind: "TRINKET", rarity: Rarity::Epic,
        slot: Some("trinket"), price: Some(1200),
        icon: &["...l....", "..lGl...", ".P...P..", "P.....P.", "P.....P.", ".P...P..", "..PPP...", "........"],
        stats: &[("regen", 1.0)],
        desc: "Slowly mends your wounds.", ..BASE
    },
    ItemDef {
        id: "luckamulet", name: "Lucky Amulet", kind: "TRINKET", rarity: Rarity::Rare,
        slot: Some("trinket"), price: Some(400),
        icon: &["........", "...P....", "...P....", "..ggg...", ".gGlGg..", ".glGlg..", "..ggg...", "........"],
        stats: &[("luck", 0.1)],
        desc: "Fortune favors you. +10% drops.", ..BASE
    },
    ItemDef {
        id: "greedcharm", name: "Greed Charm", kind: "TRINKET", rarity: Rarity::Uncommon,
        slot: Some("trinket"), price: Some(200),
        icon: &["........", "...P....", "..PPP...", ".PpppP..", ".PpPpP..", ".PpppP..", "..PPP...", "........"],
        stats: &[("coin", 0.15)],
        desc: "Coins are worth more. +15% gold.", ..BASE
    },
    ItemDef {
        id: "vigorpendant", name: "Vigor Pendant", kind: "TRINKET", rarity: Rarity::Epic,
        slot: Some("trinket"), price: Some(600),
        icon: &["...P....", ".rr.rr..", "rrrrrrr.", "rrrrrrr.", ".rrrrr..", "..rrr...", "...r....", "........"],
        stats: &[("maxhp", 2.0)],
        desc: "Bolsters your vitality. +2 HP.", ..BASE
    },
    ItemDef {
        id: "paddedcoif", name: "Padded Coif", kind: "HEAD", rarity: Rarity::Common,
        slot: Some("head"),
        icon: &["........", "..DDDD..", ".DddddD.", "DddddddD", "DddddddD", ".DDDDDD.", "........", "........"],
        stats: &[("defense", 1.0)],
        desc: "Quilted cloth. +1 Armor.", ..BASE
    },
    ItemDef {
        id: "bronzehelm", name: "Bronze Helm", kind: "HEAD", rarity: Rarity::Uncommon,
        slot: Some("head"),
        icon: &["..pppp..", ".pSSSSp.", "pSSSSSSp", "pSSKKSSp", "pSSSSSSp", ".pS..Sp.", "..p..p..", "........"],
        stats: &[("defense", 1.0), ("maxhp", 1.0)],
        desc: "Beaten bronze. +1 Armor, +1 HP.", ..BASE
    },
    ItemDef {
        id: "rangerhood", name: "Ranger Hood", kind: "HEAD", rarity: Rarity::Uncommon,
        slot: Some("head"),
        icon: &["..gggg..", ".gGGGGg.", "gGGGGGGg", "gGsssGGg", "gGGGGGGg", ".gGGGGg.", "..gGGg..", "........"],
        stats: &[("defense", 1.0), ("move", 0.05)],
        desc: "Light hood. +1 Armor, +Move.", ..BASE
    },
    ItemDef {
        id: "hornedhelm", name: "Horned Helm", kind: "HEAD", rarity: Rarity::Rare,
        slot: Some("head"),
        icon: &["A......A", "A.aaaa.A", ".aAAAAa.", "aAAKKAAa", "aAAAAAAa", ".aA..Aa.", "..a..a..", "........"],
        stats: &[("defense", 2.0), ("knock", 0.5)],
        desc: "Fearsome iron horns. +2 Armor, +Knockback.", ..BASE
    },
    ItemDef {
        id: "magehat", name: "Mage Hat", kind: "HEAD", rarity: Rarity::Rare,
        slot: Some("head"),
        icon: &["...b....", "..bb....", "..bBb...", ".bbPb...", ".bbBbb..", "bBBBBBb.", "bbbbbbbb", "........"],
        stats: &[("maxmana", 3.0), ("spell", 0.1)],
        desc: "A starlit cap. +3 MP, +10% Spell.", ..BASE
    },
    ItemDef {
        id: "dragonhelm", name: "Dragon Helm", kind: "HEAD", rarity: Rarity::Epic,
        slot: Some("head"),
        icon: &["r......r", "rr.rr.rr", ".rRRRRr.", "rRRKKRRr", "rRRRRRRr", ".rR..Rr.", "..r..r..", "........"],
        stats: &[("defense", 3.0), ("maxhp", 1.0)],
        desc: "Scaled and crested. +3 Armor, +1 HP.", ..BASE
    },
    ItemDef {
        id: "crownofvalor", name: "Crown of Valor", kind: "HEAD", rarity: Rarity::Legendary,
        slot: Some("head"),
        icon: &["........", "P.P.P.P.", "PPPPPPP.", "PPPPPPP.", "PPrPrPP.", "PPPPPPP.", ".PPPPP..", "........"],
        stats: &[("defense", 2.0), ("maxhp", 2.0), ("melee", 0.1)],
        desc: "A king's crown. +2 Armor, +2 HP, +10% Melee.", ..BASE
    },
    ItemDef {
        id: "clothtunic", name: "Cloth Tunic", kind: "BODY", rarity: Rarity::Common,
        slot: Some("body"),
        icon: &[".g....g.", ".gggggg.", ".gggggg.", ".gggggg.", ".gggggg.", ".gggggg.", "..g..g..", "........"],
        stats: &[("maxhp", 1.0)],
        desc: "Simple cloth. +1 HP.", ..BASE
    },
    ItemDef {
        id: "studdedleather", name: "Studded Leather", kind: "BODY", rarity: Rarity::Uncommon,
        slot: Some("body"),
        icon: &[".D....D.", ".DDDDDD.", ".DADADD.", ".DdAdAd.", ".DADADD.", ".DDDDDD.", "..D..D..", "........"],
        stats: &[("defense", 1.0), ("move", 0.05)],
        desc: "Riveted hide. +1 Armor, +Move.", ..BASE
    },
    ItemDef {
        id: "scalemail", name: "Scale Mail", kind: "BODY", rarity: Rarity::Rare,
        slot: Some("body"),
        icon: &[".b....b.", ".bBbBbB.", ".BbBbBb.", ".bBbBbB.", ".BbBbBb.", ".bBbBbB.", "..b..b..", "........"],
        stats: &[("defense", 2.0), ("maxhp", 1.0)],
        desc: "Overlapping scales. +2 Armor, +1 HP.", ..BASE
    },
    ItemDef {
        id: "magerobe", name: "Mage Robe", kind: "BODY", rarity: Rarity::Rare,
        slot: Some("body"),
        icon: &[".x....x.", ".xxxxxx.", ".xXxxXx.", ".xxPxxx.", ".xXxxXx.", ".xxxxxx.", ".xx..xx.", ".x....x."],
        icon_pal: &[('x', 0xb85cf0), ('X', 0x6a28a8), ('f', 0xa8e6ff), ('F', 0x3f93d2)],
        stats: &[("defense", 1.0), ("maxmana", 4.0), ("spell", 0.15)],
        desc: "Woven with sigils. +4 MP, +15% Spell.", ..BASE
    },
    ItemDef {
        id: "dragonscale", name: "Dragonscale", kind: "BODY", rarity: Rarity::Epic,
        slot: Some("body"),
        icon: &[".r....r.", ".rRrRrR.", ".RrRrRr.", ".rRrRrR.", ".RrRrRr.", ".rRrRrR.", "..r..r..", "........"],
        stats: &[("defense", 3.0), ("maxhp", 2.0)],
        desc: "Wyrmhide plate. +3 Armor, +2 HP.", ..BASE
    },
    ItemDef {
        id: "aegisplate", name: "Aegis Plate", kind: "BODY", rarity: Rarity::Legendary,
        slot: Some("body"),
        icon: &[".A....A.", ".AWWWWA.", ".AWPPWA.", ".AWPPWA.", ".AWWWWA.", ".AAAAAA.", "..A..A..", "........"],
        stats: &[("defense", 4.0), ("maxhp", 2.0)],
        desc: "Hallowed bulwark. +4 Armor, +2 HP.", ..BASE
    },
    ItemDef {
        id: "sandals", name: "Sandals", kind: "FEET", rarity: Rarity::Common,
        slot: Some("feet"),
        icon: &["........", ".S....S.", ".SssSsS.", ".SSSSSS.", "SSSSSSSS", ".S.SS.S.", "........", "........"],
        stats: &[("move", 0.05)],
        desc: "Bare and breezy. +Move.", ..BASE
    },
    ItemDef {
        id: "swiftboots", name: "Swift Boots", kind: "FEET", rarity: Rarity::Uncommon,
        slot: Some("feet"),
        icon: &[".l.g..g.", "lg.g..g.", ".g.g..g.", ".g.g..g.", ".gg.gg..", "ggg.ggg.", "GGG.GGG.", "........"],
        stats: &[("move", 0.1)],
        desc: "Featherlight. ++Move.", ..BASE
    },
    ItemDef {
        id: "ironcladgreaves", name: "Ironclad Greaves", kind: "FEET", rarity: Rarity::Rare,
        slot: Some("feet"),
        icon: &["..A..A..", ".AA..AA.", ".AA..AA.", ".AA..AA.", ".AA..AA.", ".AAA.AAA", "AAAAAAAA", "nnn.nnn."],
        stats: &[("defense", 2.0)],
        desc: "Heavy plated boots. +2 Armor.", ..BASE
    },
    ItemDef {
        id: "bootsofhaste", name: "Boots of Haste", kind: "FEET", rarity: Rarity::Epic,
        slot: Some("feet"),
        icon: &[".l......", "lb.b..b.", ".b.b..b.", ".b.b..b.", ".bb.bb..", "bbb.bbb.", "BBB.BBB.", "........"],
        stats: &[("move", 0.12), ("haste", 0.08)],
        desc: "Winged speed. +Move, +Attack Speed.", ..BASE
    },
    ItemDef {
        id: "sevenleague", name: "Seven-League Boots", kind: "FEET", rarity: Rarity::Legendary,
        slot: Some("feet"),
        icon: &[".P....P.", ".b....b.", ".b....b.", ".bP..Pb.", ".b....b.", ".bb..bb.", "Pbb.bbP.", "BBB.BBB."],
        stats: &[("move", 0.25)],
        desc: "Each stride covers leagues. +++Move.", ..BASE
    },
    ItemDef {
        id: "powerring", name: "Ring of Power", kind: "TRINKET", rarity: Rarity::Uncommon,
        slot: Some("trinket"),
        icon: &["...r....", "..rrr...", ".P...P..", "P.....P.", "P.....P.", ".P...P..", "..PPP...", "........"],
        stats: &[("melee", 0.1)],
        desc: "+10% Melee damage.", ..BASE
    },
    ItemDef {
        id: "swiftcharm", name: "Swift Charm", kind: "TRINKET", rarity: Rarity::Uncommon,
        slot: Some("trinket"),
        icon: &["........", "...P....", "...P....", "..lll...", ".lglgl..", ".llgll..", "..lll...", "........"],
        stats: &[("haste", 0.06)],
        desc: "+Attack Speed.", ..BASE
    },
    ItemDef {
        id: "lodestone", name: "Lodestone", kind: "TRINKET", rarity: Rarity::Uncommon,
        slot: Some("trinket"),
        icon: &["........", ".r...r..", ".r...r..", ".r...r..", ".rA.Ar..", ".rrArr..", "..rrr...", "........"],
        stats: &[("magnet", 1.0)],
        desc: "Draws nearby loot to you.", ..BASE
    },
    ItemDef {
        id: "gamblerscoin", name: "Gambler's Coin", kind: "TRINKET", rarity: Rarity::Uncommon,
        slot: Some("trinket"),
        icon: &["..PPPP..", ".PpPPpP.", "PPKPKPP.", "PPPKPPP.", "PPKPKPP.", ".PpPPpP.", "..PPPP..", "........"],
        stats: &[("luck", 0.08), ("coin", 0.1)],
        desc: "+8% drops, +10% gold.", ..BASE
    },
    ItemDef {
        id: "manacrystal", name: "Mana Crystal", kind: "TRINKET", rarity: Rarity::Uncommon,
        slot: Some("trinket"),
        icon: &["...w....", "..wbw...", ".wbBbw..", "wbBBBbw.", ".wbBbw..", "..wbw...", "...w....", "........"],
        stats: &[("maxmana", 4.0)],
        desc: "+4 Max MP.", ..BASE
    },
    ItemDef {
        id: "critring", name: "Ring of Precision", kind: "TRINKET", rarity: Rarity::Rare,
        slot: Some("trinket"),
        icon: &["...W....", "..WPW...", ".P...P..", "P.....P.", "P.....P.", ".P...P..", "..PPP...", "........"],
        stats: &[("crit", 0.1)],
        desc: "+10% Critical chance.", ..BASE
    },
    ItemDef {
        id: "magefocus", name: "Mage Focus", kind: "TRINKET", rarity: Rarity::Rare,
        slot: Some("trinket"),
        icon: &["........", "...P....", "...P....", "..bbb...", ".bBwBb..", ".bwBwb..", "..bbb...", "........"],
        stats: &[("spell", 0.12), ("maxmana", 2.0)],
        desc: "+12% Spell, +2 MP.", ..BASE
    },
    ItemDef {
        id: "ironheart", name: "Iron Heart", kind: "TRINKET", rarity: Rarity::Rare,
        slot: Some("trinket"),
        icon: &["........", "..a.a...", ".aAaAa..", ".aAAAa..", "..aAAa..", "...Aa...", "........", "........"],
        stats: &[("maxhp", 2.0), ("defense", 1.0)],
        desc: "+2 HP, +1 Armor.", ..BASE
    },
    ItemDef {
        id: "titangrip", name: "Titan Grip", kind: "TRINKET", rarity: Rarity::Rare,
        slot: Some("trinket"),
        icon: &["........", "..AAAA..", ".AAAAAA.", ".AnAnAA.", ".AAAAAA.", "..AAAA..", "...AA...", "........"],
        stats: &[("knock", 1.0)],
        desc: "Your blows fling foes far. +Knockback.", ..BASE
    },
    ItemDef {
        id: "focuslens", name: "Focusing Lens", kind: "TRINKET", rarity: Rarity::Rare,
        slot: Some("trinket"),
        icon: &["..AAAA..", ".AwwwwA.", "AwbBbwA.", "AwBKBwA.", "AwbBbwA.", ".AwwwwA.", "..AAAA..", "........"],
        stats: &[("spell", 0.1), ("manaregen", 1.0)],
        desc: "+10% Spell, faster mana regen.", ..BASE
    },
    ItemDef {
        id: "berserkertotem", name: "Berserker Totem", kind: "TRINKET", rarity: Rarity::Epic,
        slot: Some("trinket"),
        icon: &["..rrr...", ".rWrWr..", ".rrrrr..", ".rKrKr..", "..rrr...", "...r....", "...r....", "........"],
        stats: &[("melee", 0.25), ("defense", -1.0)],
        desc: "Rage over caution. +25% Melee, -1 Armor.", ..BASE
    },
    ItemDef {
        id: "vampirefang", name: "Vampire Fang", kind: "TRINKET", rarity: Rarity::Epic,
        slot: Some("trinket"),
        icon: &["...P....", "...P....", "..WrW...", ".WrrrW..", "..WrW...", "...r....", "...W....", "........"],
        stats: &[("leech", 0.08)],
        desc: "Strikes drink life. +Lifesteal.", ..BASE
    },
    ItemDef {
        id: "arcanesigil", name: "Arcane Sigil", kind: "TRINKET", rarity: Rarity::Epic,
        slot: Some("trinket"),
        icon: &["...x....", "..xXx...", ".x.X.x..", "xXXXXXx.", ".x.X.x..", "..xXx...", "...x....", "........"],
        icon_pal: &[('x', 0xb85cf0), ('X', 0x6a28a8), ('f', 0xa8e6ff), ('F', 0x3f93d2)],
        stats: &[("spell", 0.25), ("maxmana", 3.0)],
        desc: "+25% Spell, +3 MP.", ..BASE
    },
    ItemDef {
        id: "assassinmark", name: "Assassin's Mark", kind: "TRINKET", rarity: Rarity::Epic,
        slot: Some("trinket"),
        icon: &["........", "...W....", "...X....", "...X....", "..XXX...", "...x....", "...x....", "........"],
        icon_pal: &[('x', 0xb85cf0), ('X', 0x6a28a8), ('f', 0xa8e6ff), ('F', 0x3f93d2)],
        stats: &[("crit", 0.15), ("critmult", 0.5)],
        desc: "+15% Crit, +50% Crit damage.", ..BASE
    },
    ItemDef {
        id: "phoenixfeather", name: "Phoenix Feather", kind: "TRINKET", rarity: Rarity::Legendary,
        slot: Some("trinket"),
        icon: &["......P.", ".....Po.", "....Poo.", "...Poro.", "..Pooro.", ".Pooro..", "..Pro...", "..P....."],
        stats: &[("maxhp", 3.0), ("regen", 1.0)],
        desc: "Ever-renewing. +3 HP, +Regen.", ..BASE
    },
    ItemDef {
        id: "warlordbanner", name: "Warlord's Banner", kind: "TRINKET", rarity: Rarity::Legendary,
        slot: Some("trinket"),
        icon: &[".P....P.", ".PrrrrP.", ".PrPrrP.", ".PrrPrP.", ".PrrrrP.", "..rrrr..", "...rr...", "....r..."],
        stats: &[("melee", 0.3), ("crit", 0.1)],
        desc: "Lead the charge. +30% Melee, +10% Crit.", ..BASE
    },
];
