//! people_data.rs — GENERATED by tools/extract_people.mjs from js/people.js. Name
//! pools, keeper professions, and friendship dialogue, verbatim. Do not hand-edit.
#![allow(clippy::all)]

pub static NAMES_F: &[&str] = &["MARA", "ISOLDE", "HALLIE", "SIBYL", "ROSAMUND", "GRETA", "TILLY", "PIPPA", "VERA", "ELSPETH", "IDA", "NELL", "WREN", "MAUDE", "ODESSA", "SYLVIE", "PETRA", "FERN", "HESTER", "CORA", "MARIGOLD", "SAFFRON", "INA", "AGATHA", "LUNE", "BLYTHE", "OPAL", "TANSY", "SORREL", "BREN"];
pub static NAMES_M: &[&str] = &["DUN", "TOMMEN", "GARRICK", "ORIN", "FENN", "CASPER", "ANSEL", "MORDECAI", "STELLAN", "HUGO", "BARNABY", "COLM", "EDMUND", "THADDEUS", "GILES", "PERCIVAL", "RUFUS", "EAMON", "LEOPOLD", "ALDOUS", "BRAM", "IVES", "OTIS", "WALLACE", "DREW", "FOSTER", "HAROLD", "CEDRIC", "MERRICK", "VOLLO"];

/// Keepers wear their trade — building kind -> "THE SMITH" style (js PROF).
pub static PROF: &[(&str, &str)] = &[
    ("blacksmith", "THE SMITH"),
    ("armory", "THE ARMORER"),
    ("store", "THE GROCER"),
    ("magic", "THE MAGICIAN"),
    ("alchemist", "THE ALCHEMIST"),
    ("jeweler", "THE JEWELER"),
    ("fletcher", "THE FLETCHER"),
    ("trader", "THE TRADER"),
    ("inn", "THE INNKEEP"),
    ("church", "THE PRIEST"),
    ("temple", "THE PRIEST"),
    ("tavern", "THE TAVERNER"),
    ("library", "THE LIBRARIAN"),
    ("bakery", "THE BAKER"),
    ("townhall", "THE CLERK"),
    ("ghall", "THE STEWARD"),
];

/// 3+ hearts (js FRIENDLY).
pub static FRIENDLY: &[&str] = &[
    "GOOD TO SEE YOU AGAIN.",
    "YOU ALWAYS TURN UP ON THE FINE DAYS.",
    "SAVED YOU A SEAT BY THE FIRE.",
    "THE TOWN FEELS SAFER WITH YOU ABOUT.",
    "HEARD YOU WERE BACK - GLAD OF IT.",
    "YOU LOOK WELL. THE ROAD SUITS YOU.",
    "MY DOOR IS ALWAYS OPEN TO YOU.",
    "TELL ME EVERYTHING WHEN YOU HAVE TIME.",
    "I TOLD THE NEIGHBORS ALL ABOUT YOU.",
    "YOU MISSED SOME WEATHER YESTERDAY.",
    "STAY FOR SUPPER SOMETIME, WILL YOU?",
    "THE ROADS ARE KINDER WHEN YOU WALK THEM.",
    "I KEPT AN EAR OUT FOR NEWS OF YOU.",
    "EVERY TOWN SHOULD HAVE ONE OF YOU.",
];

/// 7+ hearts (js CONFIDANT).
pub static CONFIDANT: &[&str] = &[
    "I ONLY TELL MY REAL FRIENDS THIS SORT OF THING.",
    "WHEN THE BELLS RING WRONG, STAY INDOORS. TRUST ME.",
    "I BURIED SOMETHING ONCE. NEVER FOUND IT AGAIN. KEEP A SHOVEL.",
    "THE OLD FOLK SAY THE STONES SING IF YOU KNOW THE TUNE.",
    "IF I WERE YOUNGER I WOULD BE OUT THERE WITH YOU.",
    "YOU ARE THE BEST THING TO HAPPEN TO THIS TOWN IN YEARS.",
    "SOME NIGHTS I HEAR THE HEART BEATING UNDER EVERYTHING. DO YOU?",
    "MY GRANDMOTHER SWORE THE RIFTS BREATHE IN WINTER.",
    "IF I VANISH ONE DAY, CHECK THE DEEP ROADS FIRST.",
    "I KEEP A LITTLE COIN UNDER THE THIRD FLOORBOARD. NOW YOU KNOW.",
    "YOU COULD KNOCK AT MIDNIGHT AND I WOULD STILL POUR TEA.",
    "WHATEVER THE CASTLE TOOK FROM US, YOU GIVE SOME OF IT BACK.",
];
