// GENERATED by tools/extract_relics.mjs from js/relics.js — do not edit.
//! relics_data.rs — the shards of the Wriftheart: every land's relic (name, colour,
//! lore). Each WORLD holds only ten of them true (World::shard_biomes).

pub struct Relic {
    pub biome: &'static str,
    pub name: &'static str,
    pub col: u32,
    pub lore: &'static str,
}

pub static LIST: &[Relic] = &[
    Relic { biome: "grassland", name: "Verdant Tear", col: 0x3cdc5a, lore: "The first green thing to fall. Where it landed the meadows woke, and the world remembered how to be gentle." },
    Relic { biome: "forest", name: "Heartwood Seed", col: 0x1f9e3a, lore: "It took root in the eldest tree. The forest grew tall to hide it, and taller still to guard it." },
    Relic { biome: "desert", name: "Sunstone", col: 0xfcd000, lore: "It blazed so fierce the rivers fled and the sand drank the sky. Even now it hoards the light." },
    Relic { biome: "mountains", name: "Stormcore", col: 0x9ab0e0, lore: "It rolled to the roof of the world and slept in the stone. Thunder is only the shard, dreaming." },
    Relic { biome: "swamp", name: "Mire Pearl", col: 0x7fa838, lore: "It sank into the black water and would not drown. The bog grew thick to keep its secret." },
    Relic { biome: "graveyard", name: "Gravebloom", col: 0xc8b8e8, lore: "It fell among the dead and would not let them rest. They keep its vigil to this day." },
    Relic { biome: "arctic", name: "Frostpetal", col: 0xaee6ff, lore: "It froze the instant it touched the earth, and the winter never ended. Cold is its long, patient grief." },
    Relic { biome: "burnt", name: "Emberseed", col: 0xfc7030, lore: "It would not stop burning. The wood gave itself to the fire rather than let the shard go cold." },
    Relic { biome: "mushroom", name: "Sporecrown", col: 0xff5cae, lore: "It fell soft and strange. The fungus rose to wear it, and dreams have leaked from that grove ever since." },
    Relic { biome: "chaos", name: "Voidshard", col: 0xb060f0, lore: "The deepest wound. Here the Wriftheart bled out, and from here the unmaking still spreads." },
    Relic { biome: "petalwood", name: "Petalglass", col: 0xff9ad0, lore: "It fell soft as a blossom and never stopped falling. The wood blooms out of season, out of spite, out of love." },
    Relic { biome: "honeyglade", name: "Amberdrop", col: 0xf0b840, lore: "It landed in the hives, and the honey of that summer never crystallised. Sweetness is its long memory." },
    Relic { biome: "bluebell", name: "Belltear", col: 0x7a8ae8, lore: "It came down among the queens own flowers. The bells nod when no wind moves them. Some say they are still greeting her." },
    Relic { biome: "greenmaw", name: "Vinecore", col: 0x3faf4f, lore: "The jungle swallowed it in a season and has been growing toward it ever since, from every direction at once." },
    Relic { biome: "prismwastes", name: "Splitlight", col: 0x9ad8e8, lore: "It broke the light when it broke the ground. Every shadow in the wastes points toward where it sleeps." },
    Relic { biome: "suncoast", name: "Tidegold", col: 0xe8d080, lore: "It sank where the sea once stood, and the sea followed it down. The harbour bells still answer its turning." },
    Relic { biome: "stormreach", name: "Skygrief", col: 0x8098d8, lore: "The sky will not leave this one alone. The thunder is an argument the clouds have been losing for three centuries." },
    Relic { biome: "tarmire", name: "Blackdrop", col: 0x8a8a58, lore: "The mire closed over it without a ripple and has been perfectly, unnaturally patient ever since." },
    Relic { biome: "galewind", name: "Howlstone", col: 0xa8c0b0, lore: "It struck the steppe and the air has been fleeing the sound of it ever since. The wind is the echo that never landed." },
    Relic { biome: "saltwastes", name: "Brinestar", col: 0xd8e0e8, lore: "It drank an inland sea and left the salt as a monument. What sleeps beneath the crust is still thirsty." },
    Relic { biome: "hollowwood", name: "Palewisp", col: 0xc9cfc0, lore: "It fell into the fog, or became it. The wood hides it the way a magician hides a coin: everywhere, and nowhere, and watching you guess." },
    Relic { biome: "witherlands", name: "Rotgleam", col: 0x96a050, lore: "It lay untaken longest of all, and the rot grew thoughtful around it. Do not listen to what grows there." },
    Relic { biome: "embermaw", name: "Cinderfang", col: 0xf05828, lore: "It bit into the far south and never let go. The land burns slow around it, patient as a banked hearth." },
    Relic { biome: "blackdeep", name: "Nightseed", col: 0x6a6ab0, lore: "It fell farther than any other - down past the sun, into the Starless Deep. The dark down there grew around it like a pearl." },
    Relic { biome: "wriftscar", name: "Wriftglass", col: 0xc060ff, lore: "The shard that never left the wound. Where it lies the land turned to glass, and the glass remembers being whole. The last, and the nearest to the break." },
    Relic { biome: "emberscar", name: "Slagheart", col: 0xf0602c, lore: "It sank into the molten scar and set the rock to slow boil. The land has been trying to close over it for an age, and failing." },
    Relic { biome: "gloammoor", name: "Fenlight", col: 0x8aa060, lore: "It drowned in the blighted fen and would not go dark. The marsh-lights are only the shard, calling for something that never comes." },
    Relic { biome: "starhollow", name: "Deepstar", col: 0x8a7ad8, lore: "It fell through the hollow into the void-lit dark and hung there, a false star, patient and cold, watching the way down." },
];

pub fn by_biome(b: &str) -> Option<&'static Relic> {
    LIST.iter().find(|r| r.biome == b)
}

pub static INTRO: &str = "The Wriftheart shattered, and the world with it. Ten shards sank into ten lands. Clear each land's dungeon, take back its shard, and make the world whole.";
pub static FINALE: &str = "Ten shards, one heart. The Wriftheart beats again in your hands. Return to where it all began, for something on the far side of the wound has felt it wake.";
pub static STORY: &[&str] = &[
    "Long ago, the world was whole.",
    "It was held together by the Wriftheart, a single gem at the heart of all creation.",
    "Then it shattered. From the wound bled Chaos, warping the farthest lands and twisting their beasts into corrupted things.",
    "But the Wriftheart did not die. It broke into ten shards, and each sank into the heart of a different land, taking on its nature.",
    "The old maps whisper that one who gathers all ten shards may mend the Wriftheart... or claim the power that remains within it.",
    "Seek out the shattered pieces of the Wriftheart, and face what waits beyond the wound.",
];
