//! stock_tables.rs — GENERATED by tools/extract_stock.mjs from js/items.js. The
//! EFFECTIVE post-init vendor tables (items.js pushes RECIPE_BPS blueprint ids into
//! STOCK/LOOT_POOLS at module init). Do not hand-edit; re-run the extractor.
#![allow(clippy::all)]

/// Shop stock by vendor kind (js STOCK) — the rotating catalogue a vendor curates 4 from.
pub static STOCK: &[(&str, &[&str])] = &[
    ("general", &["potion", "greaterpotion", "bombs", "lantern", "pocketwatch", "satchel", "antidote", "tonic", "chicken"]),
    ("blacksmith", &["shield", "bpmace", "bpchainmail"]),
    ("armory", &[]),
    ("magic", &["wand", "firerune", "frostrune", "stormrune", "venomrune", "manapotion", "elixir", "manaelixir", "magehat", "magerobe", "magefocus", "arcanesigil", "manacrystal", "bpstormrune", "bpvenomrune", "bpmanacrystal"]),
    ("alchemist", &["potion", "greaterpotion", "elixir", "manapotion", "bombs", "antidote", "tonic", "manaelixir", "bpmanapotion", "bpelixir", "bpmanaelixir"]),
    ("jeweler", &["regenring", "luckamulet", "greedcharm", "vigorpendant", "bubblering", "powerring", "critring", "swiftcharm", "ironheart", "gamblerscoin", "vampirefang", "phoenixfeather", "compass", "bpcritring", "bpluckamulet"]),
    ("fletcher", &["bow", "arrow", "springboots", "boomerang", "bpgrapple", "bpspringboots"]),
    ("trader", &["lantern", "pocketwatch", "satchel", "satchel2", "bombs", "potion", "tonic", "lodestone", "shovel", "treasuremap", "arrow"]),
    ("farm", &["turnipseed", "potatoseed", "carrotseed", "wheatseed", "tomatoseed", "pepperseed", "pumpkinseed", "cranberryseed", "chicken", "cow"]),
    ("produce", &["turnip", "potato", "carrot", "wheat", "tomato", "pepper", "pumpkin", "cranberry", "turnipseed", "carrotseed", "tomatoseed", "pumpkinseed"]),
];

/// Staples a vendor ALWAYS carries (js GUARANTEED).
pub static GUARANTEED: &[(&str, &[&str])] = &[
    ("general", &["herb", "meat", "bpcook", "bpfarmtable"]),
    ("blacksmith", &["copper", "bpforge"]),
    ("armory", &["leather"]),
    ("magic", &["gem", "bpenchanter"]),
    ("alchemist", &["herb", "bpalchemy"]),
    ("jeweler", &["gem", "copper", "bpjeweler"]),
    ("fletcher", &["leather", "bpfletcher", "arrow"]),
    ("farm", &["bpfarmtable", "bpwell", "hoe", "wateringcan", "milkpail"]),
    ("produce", &["herb", "egg"]),
];

/// Wild-shop category pools (js WILD_POOLS).
pub static WILD_POOLS: &[(&str, &[&str])] = &[
    ("material", &["wood", "stone", "fiber", "string", "hardwood", "ironbark", "voidwood", "petalwood", "greenheart", "copper", "iron", "silver", "gold", "mithril", "voidsteel", "herb", "rareherb", "leather", "silk", "gem"]),
    ("consumable", &["potion", "greaterpotion", "elixir", "manapotion", "manaelixir", "antidote", "tonic", "bombs", "bandage", "sleepingbag"]),
    ("tool", &["lantern", "pocketwatch", "shovel", "treasuremap", "hoe", "wateringcan", "milkpail", "satchel", "satchel2", "minerhelm", "ironpick", "ironaxe", "silverpick", "lodestone"]),
    ("seed", &["turnipseed", "potatoseed", "carrotseed", "wheatseed", "tomatoseed", "pepperseed", "pumpkinseed", "cranberryseed"]),
    ("misc", &["bow", "arrow", "boomerang", "springboots", "bubblering", "grapplehook", "chicken", "cow"]),
    ("trinket", &["regenring", "luckamulet", "greedcharm", "vigorpendant", "powerring", "critring", "swiftcharm", "ironheart", "gamblerscoin", "vampirefang", "phoenixfeather", "compass"]),
    ("blueprint", &["bpforge", "bpalchemy", "bpenchanter", "bpjeweler", "bpfletcher", "bpcook", "bpfarmtable", "bpgrapple"]),
];

/// Wild-shop category draw weights (js WILD_CATS).
pub static WILD_CATS: &[(&str, f64)] = &[
    ("material", 3.0),
    ("consumable", 3.0),
    ("tool", 2.0),
    ("seed", 1.5),
    ("misc", 2.0),
    ("weapon", 2.0),
    ("armor", 2.0),
    ("trinket", 1.5),
    ("blueprint", 1.2),
];
