// GENERATED from js/tiles.js — do not edit. Regenerate via the extraction harness.
// Raw tile art grids + the code table + ground texture defs from the JS reference.

pub const ART: &[(&str, [&str; 16])] = &[
    ("ground", ["yyyyyyyyyyyyyyyy", "yyyyyyyyyyyyyyyy", "yyyyYyyyyyyyyyyy", "yyyyyyyyyyyyyYyy", "yyyyyyyyyyyyyyyy", "yyyyyyyyYyyyyyyy", "yyyyyyyyyyyyyyyy", "yyyyyyyyyyyyyyyy", "yyYyyyyyyyyyyyyy", "yyyyyyyyyyyyyyyy", "yyyyyyyyyyyYyyyy", "yyyyyyyyyyyyyyyy", "yyyyyyyYyyyyyyyy", "yyyyyyyyyyyyyyyy", "yyyyyyyyyyyyyyYy", "yyyyyyyyyyyyyyyy"]),
    ("tree", ["GGlGGGGGGGGlGGGG", "GGGGGGGEGGGGGGGG", "GlGGGGGlGGGGGGlG", "GGGGGGGGGGGGGGGG", "GGGGGlGGGGEGGGGG", "GGlGGGGGGGGGGlGG", "GGGGGGGGGlGGGGGG", "GEGGGlGGGGGGGGGE", "GGGGGGGGGGlGGGGG", "GlGGGGGGGGGGGlGG", "GGGGGGlGGEGGGGGG", "GGGGGGGGGGGGlGGG", "GGGlGGGGGlGGGGGG", "GGGGGGGEGGGGGGGG", "GGGGGlGGGGGGGlGG", "GGlGGGGGGGGGGGGG"]),
    ("rock", ["yyyaaaaaaaaayyyy", "yyaaAAAaaaaaayyy", "yaaAAaaaaaaaaayy", "aaaaaaaaaaaaaaay", "aaAaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaa", "aaaaaaaaaaAaaaaa", "aaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaa", "aaaaAaaaaaaaaaaa", "aaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaa", "yaaaaaaaaaaaaaay", "yyaaaaaaaaaaaayy", "yyyaaaaaaaaaayyy", "yyyyyaaaaaayyyyy"]),
    ("water", ["VVVVVVVVVVVVVVVV", "VwwVVVwwVVVVwwVV", "VVVVVVVVVVVVVVVV", "VVVVVVVVVVVVVVVV", "wwVVVVwwVVVwwVVV", "VVVVVVVVVVVVVVVV", "VVVVVVVVVVVVVVVV", "VVwwVVVVwwVVVVww", "VVVVVVVVVVVVVVVV", "VVVVVVVVVVVVVVVV", "wwVVVwwVVVVwwVVV", "VVVVVVVVVVVVVVVV", "VVVVVVVVVVVVVVVV", "VVwwVVVwwVVVwwVV", "VVVVVVVVVVVVVVVV", "VVVVVVVVVVVVVVVV"]),
    ("dirt", ["DDDDDDDDDDDDDDDD", "DDDdDDDDDDDdDDDD", "DDDDDDDDDDDDDDDD", "DdDDDDDdDDDDDDDD", "DDDDDDDDDDDDDdDD", "DDDDDdDDDDDDDDDD", "DDDDDDDDDDdDDDDD", "DDDdDDDDDDDDDDDD", "DDDDDDDDDdDDDDDD", "DdDDDDDDDDDDDdDD", "DDDDDDdDDDDDDDDD", "DDDDDDDDDDDDdDDD", "DDDdDDDDDdDDDDDD", "DDDDDDDDDDDDDDDD", "DDDDDdDDDDDDDdDD", "DDDDDDDDDDDDDDDD"]),
    ("dirtroad", ["DDDdDDDDDDDYDDDD", "DDDDDDDYDDDDDDDD", "DYDDDDDDDDDdDDDD", "DDDDDdDDDDDDDDYD", "DDDDDDDDDYDDDDDD", "DdDDDDDDDDDDDdDD", "DDDDDYDDDdDDDDDD", "DDDDDDDDDDDDYDDD", "DYDDDdDDDDDDDDDD", "DDDDDDDDDYDDDdDD", "DDDdDDDDDDDDDDDD", "DDDDDDYDDDDDDYDD", "DdDDDDDDDDdDDDDD", "DDDDDYDDDDDDDDDD", "DDDDDDDDDdDDDYDD", "DYDDDdDDDDDDDDDD"]),
    ("grassland", ["GGGGGGGGGGGGGGGG", "GGlGGGGGGGGlGGGG", "GGGGGGGGGGGGGGGG", "GlGGGGGlGGGGGGGG", "GGGGGGGGGGGGGlGG", "GGGGGlGGGGGGGGGG", "GGGGGGGGGGlGGGGG", "GGGlGGGGGGGGGGGG", "GGGGGGGGGlGGGGGG", "GlGGGGGGGGGGGlGG", "GGGGGGlGGGGGGGGG", "GGGGGGGGGGGGlGGG", "GGGlGGGGGlGGGGGG", "GGGGGGGGGGGGGGGG", "GGGGGlGGGGGGGlGG", "GGGGGGGGGGGGGGGG"]),
    ("voidglass", ["zzzzzzzzzzzzzzzz", "zzczzzzzzzzvzzzz", "zzzzzzzzzzzzzzzz", "zvzzzzzczzzzzzzz", "zzzzzzzzzzzzzczz", "zzzzzvzzzzzzzzzz", "zzzzzzzzzzvzzzzz", "zzzczzzzzzzzzzzz", "zzzzzzzzzczzzzzz", "zvzzzzzzzzzzzczz", "zzzzzzczzzzzzzzz", "zzzzzzzzzzzzvzzz", "zzzvzzzzzczzzzzz", "zzzzzzzzzzzzzzzz", "zzzzzczzzzzzzvzz", "zzzzzzzzzzzzzzzz"]),
    ("bog", ["EEEEEEEEEEEEEEEE", "EEQEEEEEEEdEEEEE", "EEEEEEEEEEEEEEEE", "EQEEEEEdEEEEEEEE", "EEEEEEEEEEEEEQEE", "EEEEEQEEEEEEEEEE", "EEEEEEEEEEdEEEEE", "EEEdEEEEEEEEEEEE", "EEEEEEEEEQEEEEEE", "EQEEEEEEEEEEEdEE", "EEEEEEQEEEEEEEEE", "EEEEEEEEEEEEQEEE", "EEEdEEEEEQEEEEEE", "EEEEEEEEEEEEEEEE", "EEEEEQEEEEEEEdEE", "EEEEEEEEEEEEEEEE"]),
    ("mud", ["dddddddddddddddd", "ddDddddddddQdddd", "dddddddddddddddd", "dDddddDdddddddDd", "ddddddddddddQddd", "dddddDdddddddddd", "ddddddddddDddddd", "dDddddddddddddDd", "ddddddddDddddddd", "dQdddddddddddQdd", "ddddddDddddddddd", "ddddddddddddDddd", "dddDdddddQdddddd", "dddddddddddddddd", "dDdddQddddddDddd", "dddddddddddddddd"]),
    ("thicket", ["GGGEGGGEGGGEGGGE", "GGEQGGEQGGEQGGEQ", "EQQdEQQdEQQdEQQd", "EEQEEEQEEEQEEEQE", "GGGEGGGEGGGEGGGE", "GGEQGGEQGGEQGGEQ", "EQQdEQQdEQQdEQQd", "EEQEEEQEEEQEEEQE", "GGGEGGGEGGGEGGGE", "GGEQGGEQGGEQGGEQ", "EQQdEQQdEQQdEQQd", "EEQEEEQEEEQEEEQE", "GGGEGGGEGGGEGGGE", "GGEQGGEQGGEQGGEQ", "EQQdEQQdEQQdEQQd", "EEQEEEQEEEQEEEQE"]),
    ("deadgrass", ["QQQQQQQQQQQQQQQQ", "QQdQQQQQQQQdQQQQ", "QQQQQQQQQQQQQQQQ", "QdQQQQQdQQQQQQQQ", "QQQQQQQQQQQQQdQQ", "QQQQQdQQQQQQQQQQ", "QQQQQQQQQQdQQQQQ", "QQQdQQQQQQQQQQQQ", "QQQQQQQQQdQQQQQQ", "QdQQQQQQQQQQQdQQ", "QQQQQQdQQQQQQQQQ", "QQQQQQQQQQQQdQQQ", "QQQdQQQQQdQQQQQQ", "QQQQQQQQQQQQQQQQ", "QQQQQdQQQQQQQdQQ", "QQQQQQQQQQQQQQQQ"]),
    ("gravedirt", ["nnnnnnnnnnnnnnnn", "nnannnnnnnnannnn", "nnnnnnnnnnnnnnnn", "nannnnnannnnnnnn", "nnnnnnnnnnnnannn", "nnnnnannnnnnnnnn", "nnnnnnnnnnannnnn", "nnnannnnnnnnnnnn", "nnnnnnnnnannnnnn", "nannnnnnnnnnnann", "nnnnnnannnnnnnnn", "nnnnnnnnnnnnannn", "nnnannnnnannnnnn", "nnnnnnnnnnnnnnnn", "nnnnnannnnnnnann", "nnnnnnnnnnnnnnnn"]),
    ("ruinwall", ["AaaanaaanaaanAaa", "aaaanaaanaaanaaa", "aaaanaaanaaanaaa", "nnnnnnnnnnnnnnnn", "aanaaanaaanaaana", "aanaaanKaanaaana", "aanaaanaaanaaana", "nnnnnnnnnnnnnnnn", "AaaanaaanaaanAaa", "aaaanaaanaaanaaa", "aaaanaaanaaanaaa", "nnnnnnnnnnnnnnnn", "aanaaanaaanaaana", "aanaaanaaanaKana", "aanaaanaaanaaana", "nnnnnnnnnnnnnnnn"]),
    ("bridge", [".dddddddddddddd.", ".dDDDDDDDDDDDDd.", ".dDDDDDDDDDDDDd.", ".dDDDDDDDDDDDDd.", ".dddddddddddddd.", ".dDDDDDDDDDDDDd.", ".dDDDDDDDDDDDDd.", ".dDDDDDDDDDDDDd.", ".dddddddddddddd.", ".dDDDDDDDDDDDDd.", ".dDDDDDDDDDDDDd.", ".dDDDDDDDDDDDDd.", ".dddddddddddddd.", ".dDDDDDDDDDDDDd.", ".dDDDDDDDDDDDDd.", ".dDDDDDDDDDDDDd."]),
    ("bridgeH", ["................", "dddddddddddddddd", "dDDDdDDDdDDDdDDD", "dDDDdDDDdDDDdDDD", "dDDDdDDDdDDDdDDD", "dDDDdDDDdDDDdDDD", "dDDDdDDDdDDDdDDD", "dDDDdDDDdDDDdDDD", "dDDDdDDDdDDDdDDD", "dDDDdDDDdDDDdDDD", "dDDDdDDDdDDDdDDD", "dDDDdDDDdDDDdDDD", "dDDDdDDDdDDDdDDD", "dDDDdDDDdDDDdDDD", "dddddddddddddddd", "................"]),
    ("bridgeX", ["dDDDdDDDdDDDdDDD", "DDDDDDDDDDDDDDDD", "DDDDDDDDDDDDDDDD", "DDDDDDDDDDDDDDDD", "dDDDdDDDdDDDdDDD", "DDDDDDDDDDDDDDDD", "DDDDDDDDDDDDDDDD", "DDDDDDDDDDDDDDDD", "dDDDdDDDdDDDdDDD", "DDDDDDDDDDDDDDDD", "DDDDDDDDDDDDDDDD", "DDDDDDDDDDDDDDDD", "dDDDdDDDdDDDdDDD", "DDDDDDDDDDDDDDDD", "DDDDDDDDDDDDDDDD", "DDDDDDDDDDDDDDDD"]),
    ("path", ["YYYYYYYYYYYYYYYY", "YyyyyyyyyyyyyyyY", "YyyyyyyyyyyyyyyY", "YyyyyyyyyyyyyyyY", "YyyyyyyyyyyyyyyY", "YyyyyyyyyyyyyyyY", "YyyyyyyyyyyyyyyY", "YyyyyyyyyyyyyyyY", "YyyyyyyyyyyyyyyY", "YyyyyyyyyyyyyyyY", "YyyyyyyyyyyyyyyY", "YyyyyyyyyyyyyyyY", "YyyyyyyyyyyyyyyY", "YyyyyyyyyyyyyyyY", "YyyyyyyyyyyyyyyY", "YYYYYYYYYYYYYYYY"]),
    ("rockwall", ["AaaaaaaAaaaaaaaa", "aaaanaaaaaaaaAaa", "aanaaaaaaanaaaaa", "aanaaaAaaanaaAaa", "nnnaaaaaaannnnaa", "aaaaaannaaaaaana", "aaAaaaanaaaAaana", "aaaaaaanaaaaaaaa", "aaaaannnaaaaaAaa", "aannaaaaaaaaanna", "aanaaaAaaaaaanaa", "aanaaaaaaaAaanaa", "aaaaaaaaaannnaaa", "nnaaaaaaaanaaaaa", "aaaaAaaaaanaaaAa", "aaaaaaaaaanaaaaa"]),
    ("sandstone", ["yYYYYYYyYYYYYYYY", "YYYYdYYYYYYYYyYY", "YYdYYYYYYYdYYYYY", "YYdYYYyYYYdYYyYY", "dddYYYYYYYddddYY", "YYYYYYddYYYYYYdY", "YYyYYYYdYYYyYYdY", "YYYYYYYdYYYYYYYY", "YYYYYdddYYYYYyYY", "YYddYYYYYYYYYddY", "YYdYYYyYYYYYYdYY", "YYdYYYYYYYyYYdYY", "YYYYYYYYYYdddYYY", "ddYYYYYYYYdYYYYY", "YYYYyYYYYYdYYYyY", "YYYYYYYYYYdYYYYY"]),
    ("icewall", ["WffffffWffffffff", "ffffFffffffffWff", "ffFfffffffFfffff", "ffFfffWfffFffWff", "FFFfffffffFFFFff", "ffffffFFffffffFf", "ffWffffFfffWffFf", "fffffffFffffffff", "fffffFFFfffffWff", "ffFFfffffffffFFf", "ffFfffWffffffFff", "ffFfffffffWffFff", "ffffffffffFFFfff", "FFffffffffFfffff", "ffffWfffffFfffWf", "ffffffffffFfffff"]),
    ("charredwall", ["annnnnnannnnnnnn", "nnnnKnnnnnnnnann", "nnKnnnnnnnKnnnnn", "nnKnnnannnKnnann", "KKKnnnnnnnKKKKnn", "nnnnnnKKnnnnnnKn", "nnannnnKnnnannKn", "nnnnnnnKnnnnnnnn", "nnnnnKKKnnnnnann", "nnKKnnnnnnnnnKKn", "nnKnnnannnnnnKnn", "nnKnnnnnnnannKnn", "nnnnnnnnnnKKKnnn", "KKnnnnnnnnKnnnnn", "nnnnannnnnKnnnan", "nnnnnnnnnnKnnnnn"]),
    ("shroomwall", ["luuuuuuluuuuuuuu", "uuuuUuuuuuuuuluu", "uuUuuuuuuuUuuuuu", "uuUuuuluuuUuuluu", "UUUuuuuuuuUUUUuu", "uuuuuuUUuuuuuuUu", "uuluuuuUuuuluuUu", "uuuuuuuUuuuuuuuu", "uuuuuUUUuuuuuluu", "uuUUuuuuuuuuuUUu", "uuUuuuluuuuuuUuu", "uuUuuuuuuuluuUuu", "uuuuuuuuuuUUUuuu", "UUuuuuuuuuUuuuuu", "uuuuluuuuuUuuulu", "uuuuuuuuuuUuuuuu"]),
    ("chaoswall", ["mxxxxxxmxxxxxxxx", "xxxxXxxxxxxxxmxx", "xxXxxxxxxxXxxxxx", "xxXxxxmxxxXxxmxx", "XXXxxxxxxxXXXXxx", "xxxxxxXXxxxxxxXx", "xxmxxxxXxxxmxxXx", "xxxxxxxXxxxxxxxx", "xxxxxXXXxxxxxmxx", "xxXXxxxxxxxxxXXx", "xxXxxxmxxxxxxXxx", "xxXxxxxxxxmxxXxx", "xxxxxxxxxxXXXxxx", "XXxxxxxxxxXxxxxx", "xxxxmxxxxxXxxxmx", "xxxxxxxxxxXxxxxx"]),
    ("obsidian", ["AaaaaaaAaaaaaaaa", "aaaaKaaaaaaaaAaa", "aaKaaaaaaaKaaaaa", "aaKaaaAaaaKaaAaa", "KKKaaaaaaaKKKKaa", "aaaaaaKKaaaaaaKa", "aaAaaaaKaaaAaaKa", "aaaaaaaKaaaaaaaa", "aaaaaKKKaaaaaAaa", "aaKKaaaaaaaaaKKa", "aaKaaaAaaaaaaKaa", "aaKaaaaaaaAaaKaa", "aaaaaaaaaaKKKaaa", "KKaaaaaaaaKaaaaa", "aaaaAaaaaaKaaaAa", "aaaaaaaaaaKaaaaa"]),
    ("gnarlwood", ["DddddddDdddddddd", "ddddKddddddddDdd", "ddKdddddddKddddd", "ddKdddDdddKddDdd", "KKKdddddddKKKKdd", "ddddddKKddddddKd", "ddDddddKdddDddKd", "dddddddKdddddddd", "dddddKKKdddddDdd", "ddKKdddddddddKKd", "ddKdddDddddddKdd", "ddKdddddddDddKdd", "ddddddddddKKKddd", "KKddddddddKddddd", "ddddDdddddKdddDd", "ddddddddddKddddd"]),
    ("junglewall", ["lGGGGGGlGGGGGGGG", "GGGGEGGGGGGGGlGG", "GGEGGGGGGGEGGGGG", "GGEGGGlGGGEGGlGG", "EEEGGGGGGGEEEEGG", "GGGGGGEEGGGGGGEG", "GGlGGGGEGGGlGGEG", "GGGGGGGEGGGGGGGG", "GGGGGEEEGGGGGlGG", "GGEEGGGGGGGGGEEG", "GGEGGGlGGGGGGEGG", "GGEGGGGGGGlGGEGG", "GGGGGGGGGGEEEGGG", "EEGGGGGGGGEGGGGG", "GGGGlGGGGGEGGGlG", "GGGGGGGGGGEGGGGG"]),
    ("crystalwall", ["cxxxxxxcxxxxxxxx", "xxxxXxxxxxxxxcxx", "xxXxxxxxxxXxxxxx", "xxXxxxcxxxXxxcxx", "XXXxxxxxxxXXXXxx", "xxxxxxXXxxxxxxXx", "xxcxxxxXxxxcxxXx", "xxxxxxxXxxxxxxxx", "xxxxxXXXxxxxxcxx", "xxXXxxxxxxxxxXXx", "xxXxxxcxxxxxxXxx", "xxXxxxxxxxcxxXxx", "xxxxxxxxxxXXXxxx", "XXxxxxxxxxXxxxxx", "xxxxcxxxxxXxxxcx", "xxxxxxxxxxXxxxxx"]),
    ("cavewall", ["annnnnnannnnnnnn", "nnnnKnnnnnnnnann", "nnKnnnnnnnKnnnnn", "nnKnnnannnKnnann", "KKKnnnnnnnKKKKnn", "nnnnnnKKnnnnnnKn", "nnannnnKnnnannKn", "nnnnnnnKnnnnnnnn", "nnnnnKKKnnnnnann", "nnKKnnnnnnnnnKKn", "nnKnnnannnnnnKnn", "nnKnnnnnnnannKnn", "nnnnnnnnnnKKKnnn", "KKnnnnnnnnKnnnnn", "nnnnannnnnKnnnan", "nnnnnnnnnnKnnnnn"]),
    ("gravepath", ["aaaanaaaanaaaana", "aAaanaaaanaaAana", "aaaanaaAanaaaana", "nnnnnnnnnnnnnnnn", "aanaaaaanaaanaaa", "aanaaAaanaaanaAa", "aanaaaaanaAanaaa", "nnnnnnnnnnnnnnnn", "aaaanaaaanaaaana", "aAaanaaaanaaaana", "aaaanaAaanaaAana", "nnnnnnnnnnnnnnnn", "aanaaaaanaaanaaa", "aanaAaaanaaanaaa", "aanaaaaanaaanaAa", "nnnnnnnnnnnnnnnn"]),
    ("snow", ["WWWWWWWWWWWWWWWW", "WfWWWWWWWWWWWWWW", "WWWWfWWWWWWWWWWW", "WWWWWWWWWWWWWfWW", "WWWWWWWWWWWWWWWW", "WWWWWWWWfWWWWWWW", "WWWWWWWWWWWWWWWW", "WWWWWWWWWWWWWWWW", "WWfWWWWWWWWWWWWW", "WWWWWWWWWWWWWWWW", "WWWWWWWWWWWfWWWW", "WWWWWWWWWWWWWWWW", "WWWWWWWfWWWWWWWW", "WWWWWWWWWWWWWWWW", "WWWWWWWWWWWWWWfW", "WWWWWWWWWWWWWWWW"]),
    ("ice", ["FFFFFFFFFFFFFFFF", "FfFFFFFFFFFFFFFF", "FFFFfFFFFFFFFFFF", "FFFFFFFFFFFFFfFF", "FFFFFFFFFFFFFFFF", "FFFFFFFFfFFFFFFF", "FFFFFFFFFFFFFFFF", "FFFFFFFFFFFFFFFF", "FFfFFFFFFFFFFFFF", "FFFFFFFFFFFFFFFF", "FFFFFFFFFFFfFFFF", "FFFFFFFFFFFFFFFF", "FFFFFFFfFFFFFFFF", "FFFFFFFFFFFFFFFF", "FFFFFFFFFFFFFFfF", "FFFFFFFFFFFFFFFF"]),
    ("ash", ["nnnnnnnnnnnnnnnn", "nKnnnnnnnnnnnnnn", "nnnnKnnnnnnnnnnn", "nnnnnnnnnnnnnKnn", "nnnnnnnnnnnnnnnn", "nnnnnnnnKnnnnnnn", "nnnnnnnnnnnnnnnn", "nnnnnnnnnnnnnnnn", "nnKnnnnnnnnnnnnn", "nnnnnnnnnnnnnnnn", "nnnnnnnnnnnKnnnn", "nnnnnnnnnnnnnnnn", "nnnnnnnKnnnnnnnn", "nnnnnnnnnnnnnnnn", "nnnnnnnnnnnnnnKn", "nnnnnnnnnnnnnnnn"]),
    ("spore", ["llllllllllllllll", "lmllllllllllllll", "llllmlllllllllll", "lllllllllllllmll", "llllllllllllllll", "llllllllmlllllll", "llllllllllllllll", "llllllllllllllll", "llmlllllllllllll", "llllllllllllllll", "lllllllllllmllll", "llllllllllllllll", "lllllllmllllllll", "llllllllllllllll", "llllllllllllllml", "llllllllllllllll"]),
    ("chaosground", ["XXXXXXXXXXXXXXXX", "XxXXXXXXXXXXXXXX", "XXXXxXXXXXXXXXXX", "XXXXXXXXXXXXXxXX", "XXXXXXXXXXXXXXXX", "XXXXXXXXxXXXXXXX", "XXXXXXXXXXXXXXXX", "XXXXXXXXXXXXXXXX", "XXxXXXXXXXXXXXXX", "XXXXXXXXXXXXXXXX", "XXXXXXXXXXXxXXXX", "XXXXXXXXXXXXXXXX", "XXXXXXXxXXXXXXXX", "XXXXXXXXXXXXXXXX", "XXXXXXXXXXXXXXxX", "XXXXXXXXXXXXXXXX"]),
    ("basalt", ["nnnnnnnnnnnnnnnn", "nannnnnnnnnnnnnn", "nnnnannnnnnnnnnn", "nnnnnnnnnnnnnann", "nnnnnnnnnnnnnnnn", "nnnnnnnnannnnnnn", "nnnnnnnnnnnnnnnn", "nnnnnnnnnnnnnnnn", "nnannnnnnnnnnnnn", "nnnnnnnnnnnnnnnn", "nnnnnnnnnnnannnn", "nnnnnnnnnnnnnnnn", "nnnnnnnannnnnnnn", "nnnnnnnnnnnnnnnn", "nnnnnnnnnnnnnnan", "nnnnnnnnnnnnnnnn"]),
    ("lava", ["rrrrrrrrrrrrrrrr", "rPrrrrrrrrrrrrrr", "rrrrPrrrrrrrrrrr", "rrrrrrrrrrrrrPrr", "rrrrrrrrrrrrrrrr", "rrrrrrrrPrrrrrrr", "rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr", "rrPrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr", "rrrrrrrrrrrPrrrr", "rrrrrrrrrrrrrrrr", "rrrrrrrPrrrrrrrr", "rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrPr", "rrrrrrrrrrrrrrrr"]),
    ("rotleaf", ["dddddddddddddddd", "dndddddddddddddd", "ddddnddddddddddd", "dddddddddddddndd", "dddddddddddddddd", "ddddddddnddddddd", "dddddddddddddddd", "dddddddddddddddd", "ddnddddddddddddd", "dddddddddddddddd", "dddddddddddndddd", "dddddddddddddddd", "dddddddndddddddd", "dddddddddddddddd", "ddddddddddddddnd", "dddddddddddddddd"]),
    ("jungle", ["GGGGGGGGGGGGGGGG", "GgGGGGGGGGGGGGGG", "GGGGgGGGGGGGGGGG", "GGGGGGGGGGGGGgGG", "GGGGGGGGGGGGGGGG", "GGGGGGGGgGGGGGGG", "GGGGGGGGGGGGGGGG", "GGGGGGGGGGGGGGGG", "GGgGGGGGGGGGGGGG", "GGGGGGGGGGGGGGGG", "GGGGGGGGGGGgGGGG", "GGGGGGGGGGGGGGGG", "GGGGGGGgGGGGGGGG", "GGGGGGGGGGGGGGGG", "GGGGGGGGGGGGGGgG", "GGGGGGGGGGGGGGGG"]),
    ("crystalground", ["XXXXXXXXXXXXXXXX", "XcXXXXXXXXXXXXXX", "XXXXcXXXXXXXXXXX", "XXXXXXXXXXXXXcXX", "XXXXXXXXXXXXXXXX", "XXXXXXXXcXXXXXXX", "XXXXXXXXXXXXXXXX", "XXXXXXXXXXXXXXXX", "XXcXXXXXXXXXXXXX", "XXXXXXXXXXXXXXXX", "XXXXXXXXXXXcXXXX", "XXXXXXXXXXXXXXXX", "XXXXXXXcXXXXXXXX", "XXXXXXXXXXXXXXXX", "XXXXXXXXXXXXXXcX", "XXXXXXXXXXXXXXXX"]),
    ("caverock", ["nnnnnnnnnnnnnnnn", "nKnnnnnnnnnnnnnn", "nnnnKnnnnnnnnnnn", "nnnnnnnnnnnnnKnn", "nnnnnnnnnnnnnnnn", "nnnnnnnnKnnnnnnn", "nnnnnnnnnnnnnnnn", "nnnnnnnnnnnnnnnn", "nnKnnnnnnnnnnnnn", "nnnnnnnnnnnnnnnn", "nnnnnnnnnnnKnnnn", "nnnnnnnnnnnnnnnn", "nnnnnnnKnnnnnnnn", "nnnnnnnnnnnnnnnn", "nnnnnnnnnnnnnnKn", "nnnnnnnnnnnnnnnn"]),
    ("meadow", ["gggggggggggggggg", "gPgggggggggggggg", "ggggPggggggggggg", "gggggggggggggPgg", "gggggggggggggggg", "ggggggggPggggggg", "gggggggggggggggg", "gggggggggggggggg", "ggPggggggggggggg", "gggggggggggggggg", "gggggggggggPgggg", "gggggggggggggggg", "gggggggPgggggggg", "gggggggggggggggg", "ggggggggggggggPg", "gggggggggggggggg"]),
    ("bluemeadow", ["llllllllllllllll", "lFllllllllllllll", "llllFlllllllllll", "lllllllllllllFll", "llllllllllllllll", "llllllllFlllllll", "llllllllllllllll", "llllllllllllllll", "llFlllllllllllll", "llllllllllllllll", "lllllllllllFllll", "llllllllllllllll", "lllllllFllllllll", "llllllllllllllll", "llllllllllllllFl", "llllllllllllllll"]),
    ("wetsand", ["YYYYYYYYYYYYYYYY", "YyYYYYYYYYYYYYYY", "YYYYyYYYYYYYYYYY", "YYYYYYYYYYYYYyYY", "YYYYYYYYYYYYYYYY", "YYYYYYYYyYYYYYYY", "YYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYY", "YYyYYYYYYYYYYYYY", "YYYYYYYYYYYYYYYY", "YYYYYYYYYYYyYYYY", "YYYYYYYYYYYYYYYY", "YYYYYYYyYYYYYYYY", "YYYYYYYYYYYYYYYY", "YYYYYYYYYYYYYYyY", "YYYYYYYYYYYYYYYY"]),
    ("stormrock", ["nnnnnnnnnnnnnnnn", "nFnnnnnnnnnnnnnn", "nnnnFnnnnnnnnnnn", "nnnnnnnnnnnnnFnn", "nnnnnnnnnnnnnnnn", "nnnnnnnnFnnnnnnn", "nnnnnnnnnnnnnnnn", "nnnnnnnnnnnnnnnn", "nnFnnnnnnnnnnnnn", "nnnnnnnnnnnnnnnn", "nnnnnnnnnnnFnnnn", "nnnnnnnnnnnnnnnn", "nnnnnnnFnnnnnnnn", "nnnnnnnnnnnnnnnn", "nnnnnnnnnnnnnnFn", "nnnnnnnnnnnnnnnn"]),
    ("tar", ["KKKKKKKKKKKKKKKK", "KnKKKKKKKKKKKKKK", "KKKKnKKKKKKKKKKK", "KKKKKKKKKKKKKnKK", "KKKKKKKKKKKKKKKK", "KKKKKKKKnKKKKKKK", "KKKKKKKKKKKKKKKK", "KKKKKKKKKKKKKKKK", "KKnKKKKKKKKKKKKK", "KKKKKKKKKKKKKKKK", "KKKKKKKKKKKnKKKK", "KKKKKKKKKKKKKKKK", "KKKKKKKnKKKKKKKK", "KKKKKKKKKKKKKKKK", "KKKKKKKKKKKKKKnK", "KKKKKKKKKKKKKKKK"]),
    ("steppe", ["QQQQQQQQQQQQQQQQ", "QyQQQQQQQQQQQQQQ", "QQQQyQQQQQQQQQQQ", "QQQQQQQQQQQQQyQQ", "QQQQQQQQQQQQQQQQ", "QQQQQQQQyQQQQQQQ", "QQQQQQQQQQQQQQQQ", "QQQQQQQQQQQQQQQQ", "QQyQQQQQQQQQQQQQ", "QQQQQQQQQQQQQQQQ", "QQQQQQQQQQQyQQQQ", "QQQQQQQQQQQQQQQQ", "QQQQQQQyQQQQQQQQ", "QQQQQQQQQQQQQQQQ", "QQQQQQQQQQQQQQyQ", "QQQQQQQQQQQQQQQQ"]),
    ("salt", ["WWWWWWWWWWWWWWWW", "WAWWWWWWWWWWWWWW", "WWWWAWWWWWWWWWWW", "WWWWWWWWWWWWWAWW", "WWWWWWWWWWWWWWWW", "WWWWWWWWAWWWWWWW", "WWWWWWWWWWWWWWWW", "WWWWWWWWWWWWWWWW", "WWAWWWWWWWWWWWWW", "WWWWWWWWWWWWWWWW", "WWWWWWWWWWWAWWWW", "WWWWWWWWWWWWWWWW", "WWWWWWWAWWWWWWWW", "WWWWWWWWWWWWWWWW", "WWWWWWWWWWWWWWAW", "WWWWWWWWWWWWWWWW"]),
    ("blight", ["QQQQQQQQQQQQQQQQ", "QxQQQQQQQQQQQQQQ", "QQQQxQQQQQQQQQQQ", "QQQQQQQQQQQQQxQQ", "QQQQQQQQQQQQQQQQ", "QQQQQQQQxQQQQQQQ", "QQQQQQQQQQQQQQQQ", "QQQQQQQQQQQQQQQQ", "QQxQQQQQQQQQQQQQ", "QQQQQQQQQQQQQQQQ", "QQQQQQQQQQQxQQQQ", "QQQQQQQQQQQQQQQQ", "QQQQQQQxQQQQQQQQ", "QQQQQQQQQQQQQQQQ", "QQQQQQQQQQQQQQxQ", "QQQQQQQQQQQQQQQQ"]),
];

#[allow(clippy::type_complexity)] // generated data table
pub const CODES: &[(char, &str, bool, &[(char, u32)])] = &[
    ('.', "ground", false, &[]),
    ('T', "tree", true, &[('l', 0x2a6634), ('g', 0x154a1f), ('G', 0x0c3014), ('E', 0x04180a)]),
    ('R', "rock", true, &[]),
    ('~', "water", true, &[]),
    ('_', "path", false, &[]),
    ('=', "dirtroad", false, &[]),
    ('p', "gravepath", false, &[]),
    ('B', "bridge", false, &[]),
    ('M', "rockwall", true, &[]),
    ('S', "sandstone", true, &[]),
    ('J', "thicket", true, &[]),
    ('X', "ruinwall", true, &[]),
    ('I', "icewall", true, &[]),
    ('H', "charredwall", true, &[]),
    ('U', "shroomwall", true, &[]),
    ('Z', "chaoswall", true, &[]),
    ('O', "obsidian", true, &[]),
    ('N', "gnarlwood", true, &[]),
    ('G', "tree", true, &[('l', 0x2a6634), ('g', 0x154a1f), ('G', 0x0c3014), ('E', 0x04180a)]),
    ('Y', "crystalwall", true, &[]),
    ('C', "cavewall", true, &[]),
];

pub const GROUND_DEFS: &[(&str, char, char, &str)] = &[
    ("sand", 'y', 'Y', "ground"),
    ("snow", 'W', 'f', "snow"),
    ("ice", 'F', 'f', "ice"),
    ("basalt", 'n', 'a', "basalt"),
    ("lava", 'r', 'P', "lava"),
    ("rotleaf", 'd', 'n', "rotleaf"),
    ("ash", 'n', 'K', "ash"),
    ("spore", 'l', 'm', "spore"),
    ("chaosground", 'X', 'x', "chaosground"),
    ("dirt", 'D', 'd', "dirt"),
    ("grass", 'G', 'l', "grassland"),
    ("voidglass", 'z', 'v', "voidglass"),
    ("bog", 'E', 'Q', "bog"),
    ("mud", 'd', 'D', "mud"),
    ("deadgrass", 'Q', 'd', "deadgrass"),
    ("gravedirt", 'n', 'a', "gravedirt"),
    ("jungle", 'G', 'g', "jungle"),
    ("crystalground", 'X', 'c', "crystalground"),
    ("caverock", 'n', 'K', "caverock"),
    ("meadow", 'g', 'P', "meadow"),
    ("bluemeadow", 'l', 'F', "bluemeadow"),
    ("wetsand", 'Y', 'y', "wetsand"),
    ("stormrock", 'n', 'F', "stormrock"),
    ("tar", 'K', 'n', "tar"),
    ("steppe", 'Q', 'y', "steppe"),
    ("salt", 'W', 'A', "salt"),
    ("blight", 'Q', 'x', "blight"),
];
